(()=>{"use strict";
const KEY="joyofphonetics-v4";
const defaults={favorites:[],lab:[],annotations:{},sessions:[],activity:[],coder:"Sergey",coachDraft:{},blind:false};
const JP=window.JP={idea:[],gmu:[],all:[],byId:new Map(),state:{...defaults},ready:false};
function loadLocal(){try{const raw=localStorage.getItem(KEY);if(raw)JP.state={...defaults,...JSON.parse(raw)}}catch(e){}}
function save(){localStorage.setItem(KEY,JSON.stringify(JP.state))}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function title(v){return String(v||"").replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function record(id){return JP.byId.get(id)||null}
function log(action,detail=""){JP.state.activity.unshift({t:new Date().toISOString(),coder:JP.state.coder,action,detail:String(detail)});JP.state.activity=JP.state.activity.slice(0,500);save();if(window.JPResearch?.renderActivity)window.JPResearch.renderActivity()}
function favorite(id,on){const s=new Set(JP.state.favorites);on?s.add(id):s.delete(id);JP.state.favorites=[...s];save();log(on?"favorite:add":"favorite:remove",id)}
function addLab(id){if(!id||JP.state.lab.includes(id))return true;if(JP.state.lab.length>=4){alert("Audio Lab supports up to four references.");return false}JP.state.lab.push(id);save();log("lab:add",id);updateLabCount();if(window.JPLab?.render)window.JPLab.render();if(window.JPCoach?.refreshSamples)window.JPCoach.refreshSamples();return true}
function removeLab(id){JP.state.lab=JP.state.lab.filter(x=>x!==id);save();log("lab:remove",id);updateLabCount();if(window.JPLab?.render)window.JPLab.render();if(window.JPCoach?.refreshSamples)window.JPCoach.refreshSamples()}
function updateLabCount(){const el=document.getElementById("labCount");if(el)el.textContent=JP.state.lab.length?`(${JP.state.lab.length})`:""}
function go(view){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===view));window.scrollTo({top:0,behavior:"smooth"});if(view==="lab"&&window.JPLab?.render)window.JPLab.render();if(view==="coach"&&window.JPCoach?.render)window.JPCoach.render();if(view==="research"&&window.JPResearch?.render)window.JPResearch.render()}
function download(name,text,type="application/json"){const blob=new Blob([text],{type});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),800)}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch(e){const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand("copy");ta.remove();return ok}}
function normalizedRecord(r,source){if(source==="idea")return {...r,source_kind:"idea",search_blob:[r.label,r.country,r.area,r.region,r.title,r.description].filter(Boolean).join(" ").toLowerCase()};return {...r,source_kind:"gmu",region:"GMU standardized corpus",country:"",area:r.native_language,search_blob:[r.label,r.native_language,r.title,r.description].filter(Boolean).join(" ").toLowerCase()}}
async function loadArchives(){const [a,b]=await Promise.all([fetch("./archive-index.json").then(r=>{if(!r.ok)throw new Error("IDEA index failed");return r.json()}),fetch("./gmu-index.json").then(r=>{if(!r.ok)throw new Error("GMU index failed");return r.json()})]);JP.idea=(a.records||[]).map(r=>normalizedRecord(r,"idea"));JP.gmu=(b.records||[]).map(r=>normalizedRecord(r,"gmu"));JP.all=[...JP.idea,...JP.gmu];JP.byId=new Map(JP.all.map(r=>[r.id,r]));JP.ready=true;document.getElementById("statIdea").textContent=JP.idea.length.toLocaleString();document.getElementById("statGmu").textContent=JP.gmu.length.toLocaleString();document.getElementById("statLang").textContent=new Set(JP.gmu.map(x=>x.native_language)).size.toLocaleString();updateLabCount()}
function sampleOption(r){const meta=r.source_kind==="gmu"?`GMU · ${r.native_language}`:`IDEA · ${r.area||r.country}`;return `<option value="${esc(r.id)}">${esc(r.label)} — ${esc(meta)}</option>`}
function sourceCard(r){if(!r)return '<div class="sourcecard empty">Choose a sample.</div>';const meta=r.source_kind==="gmu"?`${r.native_language} · standardized passage · playable here`:`${r.area||r.country} · ${r.region} · opens at IDEA`;return `<strong>${esc(r.label)}</strong><br><span>${esc(meta)}</span><br><a href="${esc(r.source_url)}" target="_blank" rel="noreferrer">Open source ↗</a>`}
function sharePayload(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj))))}
function parseShare(s){try{return JSON.parse(decodeURIComponent(escape(atob(s))))}catch(e){return null}}
function checkSharedSession(){const h=location.hash.match(/^#session=(.+)$/);if(!h)return;const data=parseShare(h[1]);if(!data)return;JP.state.coachDraft={...JP.state.coachDraft,...data};save();setTimeout(()=>{go("coach");window.JPCoach?.render()},400)}
loadLocal();
document.addEventListener("DOMContentLoaded",async()=>{document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>go(b.dataset.view)));document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.go)));const coder=document.getElementById("coderSelect");coder.value=JP.state.coder||"Sergey";coder.addEventListener("change",()=>{JP.state.coder=coder.value;save();document.getElementById("activeCoderLabel").textContent=coder.value;log("coder:switch",coder.value);window.JPResearch?.render()});document.getElementById("activeCoderLabel").textContent=JP.state.coder;try{await loadArchives();window.JPDiscover?.init();window.JPLab?.init();window.JPCoach?.init();window.JPResearch?.init();checkSharedSession()}catch(e){document.getElementById("resultCount").textContent="Could not load archive indexes";document.getElementById("resultHint").textContent=e.message}if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})});
Object.assign(JP,{save,esc,title,record,log,favorite,addLab,removeLab,go,download,copyText,sampleOption,sourceCard,sharePayload,parseShare,updateLabCount});
})();