(()=>{"use strict";
const JP=window.JP;
let mediaRecorder=null,chunks=[],recordUrl=null,startTs=0,timer=null,blindRevealed=false,randomRecord=null;
const loops=new Map();
function loopState(id){if(!loops.has(id))loops.set(id,{a:0,b:null,on:false});return loops.get(id)}
function fmtTime(s){s=Math.max(0,Number(s)||0);return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`}
function rateControl(audio,host){const wrap=document.createElement("div");wrap.className="rate";wrap.innerHTML='Speed <input type="range" min=".55" max="1.25" value="1" step=".05"><span>1.00×</span>';const r=wrap.querySelector("input"),s=wrap.querySelector("span");r.oninput=()=>{audio.playbackRate=Number(r.value);s.textContent=Number(r.value).toFixed(2)+"×"};host.appendChild(wrap)}
function loopControls(r,a,host){const s=loopState(r.id),wrap=document.createElement("div");wrap.className="looptools";wrap.innerHTML=`<button class="btn small" data-la>Set A</button><button class="btn small" data-lb>Set B</button><button class="btn small" data-loop>${s.on?"Loop ON":"Loop A–B"}</button><button class="btn small" data-restart>↺ A</button><span data-loopread>${fmtTime(s.a)} → ${s.b==null?"—":fmtTime(s.b)}</span>`;const read=()=>{wrap.querySelector("[data-loopread]").textContent=`${fmtTime(s.a)} → ${s.b==null?"—":fmtTime(s.b)}`;wrap.querySelector("[data-loop]").textContent=s.on?"Loop ON":"Loop A–B"};wrap.querySelector("[data-la]").onclick=()=>{s.a=a.currentTime;if(s.b!=null&&s.b<=s.a)s.b=null;read();JP.log("loop:set-a",`${r.id} ${s.a.toFixed(2)}`)};wrap.querySelector("[data-lb]").onclick=()=>{s.b=a.currentTime;if(s.b<=s.a){alert("B must be after A.");s.b=null}read();JP.log("loop:set-b",`${r.id} ${s.b??""}`)};wrap.querySelector("[data-loop]").onclick=()=>{if(s.b==null){alert("Set A and B first.");return}s.on=!s.on;read();if(s.on){a.currentTime=s.a;a.play().catch(()=>{})}};wrap.querySelector("[data-restart]").onclick=()=>{a.currentTime=s.a;a.play().catch(()=>{})};a.addEventListener("timeupdate",()=>{if(s.on&&s.b!=null&&a.currentTime>=s.b){a.currentTime=s.a;a.play().catch(()=>{})}});host.appendChild(wrap)}
function slot(r,i){const blind=JP.state.blind&&!blindRevealed,title=blind?`Reference ${String.fromCharCode(65+i)}`:r.label,meta=blind?"Identity hidden for ear training":r.source_kind==="gmu"?`${r.native_language} · GMU standardized sample`:`${r.area||r.country} · IDEA`;return `<article class="labslot" data-slot-id="${JP.esc(r.id)}"><span class="sourcepill ${r.source_kind}">${r.source_kind==="gmu"?"GMU":"IDEA"}</span><h3>${JP.esc(title)}</h3><p class="resultmeta">${JP.esc(meta)}</p><p class="muted" data-labmeta="${JP.esc(r.id)}"></p>${r.source_kind==="gmu"?`<audio controls preload="metadata" src="${JP.esc(r.audio_url)}"></audio><div class="slotrate"></div><div class="slotloop"></div>`:`<p class="muted">IDEA audio remains on the source page.</p>`}<div class="resultactions"><a class="btn small" href="${JP.esc(r.source_url)}" target="_blank" rel="noreferrer">Source ↗</a><button class="btn small" data-remove-lab="${JP.esc(r.id)}">Remove</button></div></article>`}
function render(){const rows=JP.state.lab.map(JP.record).filter(Boolean);document.getElementById("labSlots").innerHTML=rows.length?rows.map(slot).join(""):'<div class="panel">Add references from Discover. GMU samples can play directly here; IDEA samples open at the source.</div>';document.querySelectorAll("[data-remove-lab]").forEach(b=>b.onclick=()=>JP.removeLab(b.dataset.removeLab));rows.forEach(async r=>{const card=document.querySelector(`[data-slot-id="${CSS.escape(r.id)}"]`);if(!card)return;if(r.source_kind==="gmu"){const a=card.querySelector("audio");rateControl(a,card.querySelector(".slotrate"));loopControls(r,a,card.querySelector(".slotloop"));const m=await JP.fetchGmuMeta(r),el=card.querySelector("[data-labmeta]");if(el)el.textContent=JP.metaSummary(m)}});document.getElementById("blindPanel").hidden=!JP.state.blind;document.getElementById("blindToggle").textContent=JP.state.blind?"Exit blind mode":"Blind ear-test mode";if(!JP.state.blind)blindRevealed=false;renderRandom()}
function ensureRandomUI(){const p=document.getElementById("blindPanel");if(document.getElementById("randomEarTest"))return;const d=document.createElement("div");d.id="randomEarTest";d.innerHTML='<hr><div class="panelhead"><div><span class="eyebrow">Random challenge</span><h3>Unknown GMU speaker</h3></div><button class="btn" id="newRandomEar">New random speaker</button></div><p class="muted">Listen before revealing the native-language label. Write the cues you hear, not a stereotype.</p><audio id="randomEarAudio" controls></audio><div id="randomEarReveal" class="sourcecard empty">Identity hidden.</div>';p.appendChild(d);document.getElementById("newRandomEar").onclick=newRandom}
function newRandom(){if(!JP.gmu.length)return;randomRecord=JP.gmu[Math.floor(Math.random()*JP.gmu.length)];const a=document.getElementById("randomEarAudio");a.src=randomRecord.audio_url;a.playbackRate=1;document.getElementById("randomEarReveal").innerHTML="Identity hidden.";document.getElementById("blindGuess").value="";JP.log("ear-test:random",randomRecord.id)}
function renderRandom(){if(!JP.state.blind)return;ensureRandomUI();if(!randomRecord)newRandom()}
function revealRandom(){blindRevealed=true;if(randomRecord){const h=document.getElementById("randomEarReveal");if(h)h.innerHTML=`<strong>${JP.esc(randomRecord.label)}</strong><br>${JP.esc(randomRecord.native_language)}<br><a href="${JP.esc(randomRecord.source_url)}" target="_blank">Open source ↗</a>`}render();JP.log("ear-test:reveal",document.getElementById("blindGuess").value)}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){alert("Microphone recording is not supported in this browser.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"});if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(blob);const p=document.getElementById("takePlayer");p.src=recordUrl;p.hidden=false;document.getElementById("takeActions").hidden=false;document.getElementById("downloadTake").onclick=()=>{const a=document.createElement("a");a.href=recordUrl;a.download=`joy-of-phonetics-take-${new Date().toISOString().replace(/[:.]/g,"-")}.webm`;a.click()};JP.log("practice:record",Math.round(blob.size/1024)+"KB")};mediaRecorder.start();startTs=Date.now();document.getElementById("recordBtn").disabled=true;document.getElementById("stopBtn").disabled=false;timer=setInterval(()=>{const sec=Math.floor((Date.now()-startTs)/1000);document.getElementById("recordTimer").textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`},250)}catch(e){alert("Microphone permission was not granted.")}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=="inactive")mediaRecorder.stop();clearInterval(timer);document.getElementById("recordBtn").disabled=false;document.getElementById("stopBtn").disabled=true}
function init(){document.getElementById("blindToggle").onclick=()=>{JP.state.blind=!JP.state.blind;blindRevealed=false;JP.save();render()};document.getElementById("revealBlind").onclick=revealRandom;document.getElementById("recordBtn").onclick=startRecording;document.getElementById("stopBtn").onclick=stopRecording;document.getElementById("takeRate").oninput=e=>document.getElementById("takePlayer").playbackRate=Number(e.target.value);document.getElementById("localReference").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const p=document.getElementById("localReferencePlayer");p.src=URL.createObjectURL(f);p.hidden=false;JP.log("practice:local-reference",f.name)};render()}
window.JPLab={init,render};
})();