// On-demand, hand-written page instructions. No chat service, tracking or form access.
const ROOT='/research/';
const content={
 home:{path:'',guide:'help/#navigation-help',en:['Where to begin',['Choose GUCHNA for Belarusian music discovery. The current listening test needs an invitation.','Choose MAPA to explore historical periods and the political context of Belarusian lands.','The archive tools below support file documentation and metadata work. Their saved data does not move automatically into the listening pilot.']],be:['З чаго пачаць',['Выберыце «Гучна» для пошуку беларускай музыкі. Для цяперашняга тэставання патрэбнае запрашэнне.','Выберыце MAPA, каб даследаваць гістарычныя перыяды і палітычны кантэкст беларускіх земляў.','Архіўныя інструменты ніжэй дапамагаюць дакументаваць файлы і метаданыя. Захаваныя там даныя не пераносяцца аўтаматычна ў музычны пілот.']]},
 mapa:{path:'atlas/mapa/',guide:'help/#mapa',en:['Read the historical map',['Select a year or historical stage before comparing the map.','Switch between “Neighboring states” and “Belarusian lands” to change the context shown.','Select a city and read the period notes and sources. A modern Belarus outline is a reference, not the border of every historical state.']],be:['Як чытаць гістарычную мапу',['Спачатку выберыце год або гістарычны этап, які хочаце разгледзець.','Пераключайце «Суседнія дзяржавы» і «Беларускія землі», каб змяніць паказаны кантэкст.','Выберыце горад і прачытайце нататкі пра перыяд і крыніцы. Сучасны контур Беларусі — арыенцір, а не мяжа кожнай гістарычнай дзяржавы.']]},
 passport:{path:'tools/unmute-the-archive/',guide:'help/#passport',en:['Document a recording',['Choose a recording you are authorized to work with, then enter its title and source.','Record what is known about context and rights. Choose Unknown where evidence is missing.','Create and export the passport JSON. Its file fingerprint checks identical bytes; it does not prove authorship or grant reuse rights.']],be:['Як задакументаваць запіс',['Выберыце запіс, з якім маеце права працаваць, і ўкажыце яго назву і крыніцу.','Запішыце вядомыя звесткі пра кантэкст і правы. Калі сведчанняў няма, пазначце «Невядома».','Стварыце і экспартуйце JSON-пашпарт. Адбітак правярае ідэнтычнасць байтаў файла, але не даказвае аўтарства і не дае правоў на выкарыстанне.']]},
 audio:{path:'tools/unmute-the-archive/restoration/',guide:'help/#audio',en:['Try a documented audio intervention',['Select the source passport and the matching original audio file.','Choose conservative processing settings, then compare the source and the separate listening copy.','Keep the master unchanged. Export the derivative and its intervention record, describing the method and any uncertainty.']],be:['Як задакументаваць апрацоўку гуку',['Выберыце пашпарт крыніцы і адпаведны арыгінальны аўдыяфайл.','Задайце ашчадныя налады апрацоўкі і параўнайце арыгінал з асобнай копіяй для праслухоўвання.','Не змяняйце майстар. Экспартуйце вытворную копію і журнал апрацоўкі з апісаннем метаду і нявызначанасці.']]},
 music:{path:'tools/unmute-the-archive/atlas/',guide:'help/#music',en:['Use the earlier metadata workspace',['This Music Atlas works with its own pilot records and browser passports; it is separate from GUCHNA.','Filter the records and open their source links. Check why a result matches instead of treating every label as verified.','Export selected metadata or inspect the collection analytics. These actions do not upload audio or synchronize the listening pilot.']],be:['Як карыстацца ранейшай базай метаданых',['Гэты Music Atlas працуе са сваімі пілотнымі запісамі і пашпартамі браўзера; ён асобны ад «Гучна».','Адфільтруйце запісы і адкрыйце крыніцы. Праверце прычыну супадзення: не кожная пазнака азначае пацверджаны факт.','Экспартуйце метаданыя або паглядзіце аналітыку калекцыі. Гэта не загружае аўдыя і не сінхранізуе музычны пілот.']]},
 culture:{path:'atlas/',guide:'help/#culture',en:['Explore the culture directory',['Choose the type of cultural resource you want to explore.','Read the entry and follow its original source; the directory links to other projects, rather than replacing them.','Check availability and attribution on the source site. An entry or research lead is not a guarantee of complete or independently reviewed information.']],be:['Як даследаваць каталог культуры',['Выберыце тып культурнага рэсурсу, які вас цікавіць.','Прачытайце запіс і перайдзіце да арыгінальнай крыніцы: каталог спасылаецца на іншыя праекты, а не замяняе іх.','Праверце даступнасць і аўтарства на сайце крыніцы. Запіс або даследчы след не гарантуе паўнаты і незалежнай праверкі ўсіх звестак.']]},
 protocol:{path:'protocol/',guide:'protocol/#design',en:['Read the research boundaries',['Start with the current status: distinguish a planned protocol from completed observations.','Inspect the questions, source requirements and review procedure before interpreting any result.','The AI-system audit and the listening-product usability study are different activities. A working interface is not evidence that human testing has been completed.']],be:['Як чытаць межы даследавання',['Пачніце з актуальнага статусу: адрознівайце запланаваны пратакол ад праведзеных назіранняў.','Перад высновамі паглядзіце пытанні, патрабаванні да крыніц і працэдуру праверкі.','Аўдыт сістэм ШІ і карыстальніцкае тэставанне музычнага прадукту — розныя працы. Гатовы інтэрфейс не сведчыць пра завершанае тэставанне з людзьмі.']]},
 dranik:{path:'playground/dranik-meter/',guide:'playground/dranik-meter/#main',en:['A little potato arithmetic',['Enter a number and choose kilograms or pounds; nothing is guessed about you.','Keep the playful 50 g assumption for one dranik, or choose your own assumption, then press Count.','The result is just arithmetic, not health advice. Clear the fields when finished; this help does not read your inputs.']],be:['Крыху бульбяной арыфметыкі',['Увядзіце лік і выберыце кілаграмы або фунты; пра вас нічога не адгадваецца.','Пакіньце жартоўнае дапушчэнне 50 г на адзін дранік або выберыце сваё і націсніце «Палічыць».','Вынік — толькі арыфметыка, не парада наконт здароўя. Калі скончыце, ачысціце палі; гэтая даведка не чытае ўведзеныя даныя.']]}
};
// The standalone Dranik calculator additionally offers Russian; the Research site remains EN/BE.
content.dranik.ru=['Немного картофельной арифметики',[
 'Введите число и выберите килограммы или фунты; никаких догадок о вас.',
 'Оставьте шуточное допущение 50 г на один драник или выберите своё, затем нажмите «Посчитать».',
 'Результат — только арифметика, не совет о здоровье. Закончив, очистите поля; эта справка не читает введённые данные.'
]];
const words={en:{button:'? Help',close:'Close',guide:'Open the guide ↗',local:'Short, hand-written guidance for this page. Not an AI chat.'},be:{button:'? Дапамога',close:'Закрыць',guide:'Адкрыць інструкцыю ↗',local:'Кароткая даведка для гэтай старонкі, напісаная загадзя. Гэта не чат з ШІ.'},ru:{button:'? Помощь',close:'Закрыть',guide:'Открыть инструкцию ↗',local:'Краткая справка для этой страницы, написанная заранее. Это не чат с ИИ.'}};
content.dranik.en=['A little potato arithmetic',['Enter a number and choose kilograms or pounds; it stays in this tab.','One dranik is fixed at an assumed 50 g. Press Count, then choose Post or Story to preview your card.','This is playful arithmetic, not health advice. Share only if comfortable: the count reveals approximate body mass. Add the calculator URL with an Instagram Story Link sticker; nothing is posted automatically.']];
content.dranik.be=['Крыху бульбяной арыфметыкі',['Увядзіце лік і выберыце кілаграмы або фунты; лік застаецца ў гэтай укладцы.','Адзін дранік — заўсёды ўмоўныя 50 г. Націсніце «Палічыць», потым выберыце допіс або сторыс.','Гэта жартоўная арыфметыка, не парада наконт здароўя. Колькасць паказвае прыблізную масу цела: дзяліцеся, толькі калі вам камфортна. Спасылку дадайце стыкерам у Story; аўтаматычнай публікацыі няма.']];
content.dranik.ru=['Немного картофельной арифметики',['Введите число и выберите килограммы или фунты; число остаётся только в этой вкладке.','Один драник — всегда условные 50 г. Нажмите «Посчитать», затем выберите пост или сторис для превью.','Это шуточная арифметика, не совет о здоровье. По количеству можно понять примерную массу тела: делитесь, только если комфортно. Добавьте ссылку стикером в Story; автоматической публикации нет.']];

export function helpFor(pathname,language='en'){
 const normalized=String(pathname).replace(/index\.html$/,'').replace(/\/?$/,'/');
 const found=Object.entries(content).find(([,entry])=>ROOT+entry.path===normalized)||['home',content.home];
 const [id,entry]=found,lang=language==='be'?'be':language==='ru'&&id==='dranik'?'ru':'en';
 const [title,steps]=entry[lang];
 const [route,hash]=entry.guide.split('#');
 return {id,lang,title,steps:[...steps],href:ROOT+route+'?lang='+lang+(hash?'#'+hash:''),...words[lang]};
}

export function mountResearchHelp({document:doc=globalThis.document,window:win=globalThis.window}={}){
 if(!doc||!win||doc.getElementById('research-context-help'))return null;
 const el=(tag,attributes={},text)=>{const node=doc.createElement(tag);for(const [key,value]of Object.entries(attributes))node.setAttribute(key,value);if(text!==undefined)node.textContent=text;return node;};
 const wrapper=el('aside',{id:'research-context-help','data-research-owned':''});
 const button=el('button',{type:'button',class:'research-help-button','aria-expanded':'false','aria-controls':'research-help-dialog','aria-haspopup':'dialog'});
 const dialog=el('dialog',{id:'research-help-dialog',class:'research-help-dialog','aria-labelledby':'research-context-help-title'});
 const closeButton=el('button',{type:'button',class:'research-help-close'});
 const title=el('h2',{id:'research-context-help-title'}),list=el('ol'),guide=el('a',{class:'research-help-guide'}),notice=el('p',{class:'research-help-notice'});
 dialog.append(closeButton,title,list,guide,notice);wrapper.append(button,dialog);doc.body.append(wrapper);
 if(!doc.getElementById('research-context-help-css'))doc.head.append(el('link',{id:'research-context-help-css',rel:'stylesheet',href:ROOT+'context-help.css'}));
 function render(){const current=helpFor(win.location.pathname,doc.documentElement.lang);button.textContent=current.button;button.append(el('img',{src:ROOT+'assets/paca-vaca-helper.webp',width:'72',height:'72',alt:'','aria-hidden':'true',class:'research-help-mascot'}));button.setAttribute('title',current.lang==='en'?'Paca-Vaca · page help':'Паца-Ваца · '+current.button.replace('? ',''));closeButton.textContent=current.close+' ×';title.textContent=current.title;list.replaceChildren(...current.steps.map(text=>el('li',{},text)));guide.href=current.href;guide.textContent=current.guide;notice.textContent=current.local;const credit=el('a',{href:'https://nashaniva.com/ru/291797',target:'_blank',rel:'noopener noreferrer'},current.lang==='en'?' Character: Paca-Vaca, an illustrated homage—not official affiliation or a claim of ownership.':current.lang==='be'?' Персанаж: Паца-Ваца, ілюстраваная прысвята. Не афіцыйнае партнёрства і не заява пра ўласныя правы.':' Персонаж: Паца-Ваца, иллюстрированное посвящение. Не официальное партнёрство и не заявление о владении правами.');notice.append(credit);}
 function close(){if(dialog.open)dialog.close();}
 button.addEventListener('click',()=>{if(dialog.open){close();return;}render();dialog.show();button.setAttribute('aria-expanded','true');closeButton.focus();});
 closeButton.addEventListener('click',close);
 dialog.addEventListener('cancel',event=>{event.preventDefault();close();});
 dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();}});
 dialog.addEventListener('close',()=>{button.setAttribute('aria-expanded','false');button.focus();});
 if(win.MutationObserver)new win.MutationObserver(render).observe(doc.documentElement,{attributes:true,attributeFilter:['lang']});
 render();return {button,dialog,closeButton};
}
