/* Independently written historical context. No original MAPA database or artwork. */
(() => {
  'use strict';
  const sources={
    atlas:{label:'Belarus in Maps · Kocsis / Zhoomar et al. (2017), pp. 22–25',url:'https://hungarian-geography.hu/inmaps/pdf/Belarus-in-Maps_17.pdf'},
    partitions:{label:'German History in Documents and Images · partitions, 1772–1795',url:'https://germanhistorydocs.org/en/the-holy-roman-empire-1648-1815/the-partitions-of-poland-1772-1795'},
    west:{label:'University of Białystok Library · Kułak / Ryżewski / Wilczewski, p. 82',url:'https://bg.uwb.edu.pl/pcr/BKWP/files/BKWP_2008_14_009.pdf'},
    tilsit:{label:'State Archive in Białystok · Treaty of Tilsit, 1807',url:'https://www.bialystok.ap.gov.pl/arch/kalendarium/13_04.htm'},
    war:{label:'1914–1918 Online · Belarus',url:'https://encyclopedia.1914-1918-online.net/article/belarus/'},
    bnr:{label:'Rada BNR · Third Constituent Charter, 25 March 1918',url:'https://www.radabnr.org/en/the-third-constituent-charter-of-the-council-rada-of-the-belarusian-democratic-republic/'},
    state:{label:'U.S. Department of State · Office of the Historian: Belarus',url:'https://history.state.gov/countries/belarus'},
    un:{label:'United Nations · Belarus: membership and change of name',url:'https://www.un.org/en/node/122103'}
  };
  sources.homiel={label:'Viktor Temushev · Homiel Land, Institute of History, NAS Belarus (2009), pp. 5–6',url:'https://gulevich.net/statiy.files/temushev_gomel.files/Temushev-Gomel.pdf'};
  sources.sapockin={label:'Spadčyna heritage directory · Sapoćkin',url:'https://spadchyna.info/ru/belarus/horadnia-region/horadnia-disrtict/sapockin/'};
  sources.warsaw={label:'State Archives · Dąbrowa district records and administrative history',url:'https://www.szukajwarchiwach.gov.pl/de/zespol/-/zespol/110253'};
  sources.congress={label:'Central Archives of Historical Records · transition in 1815',url:'https://www.agad.gov.pl/inwentarze/rntkw181.xml'};
  sources.census={label:'Henryk Grossman · urban censuses, 1808 / 1810 (1925), table XXXIX, p. 102',url:'https://sbc.org.pl/Content/79470/iii5038-1925-01.pdf'};
  sources.postwar={label:'Treaty boundary map, 16 August 1945 · University of Wisconsin–Milwaukee',url:'https://collections.lib.uwm.edu/digital/collection/agdm/id/32932/'};
  sources.atlas.label='Belarus in Maps · state formation, historical maps and chronology (2017)';
  sources.west.url='http://bg.uwb.edu.pl/pcr/BKWP/files/BKWP_2008_14_009.pdf';sources.west.label+=' · public PDF over HTTP';
  const records=[
    {id:'principalities',date:['10th–13th centuries','X–XIII стагоддзі'],kind:'formation',title:['Several principalities, not one Belarusian state','Некалькі княстваў, а не адна беларуская дзяржава'],body:['Polotsk, Turov–Pinsk and other principalities formed distinct political centers. Their territories cannot be equated with the modern reference outline.','Полацкае, Турава-Пінскае і іншыя княствы былі асобнымі палітычнымі цэнтрамі. Іх тэрыторыі не тоесныя сучаснаму беларускаму контуру.'],areas:[[['Political contexts','Палітычныя кантэксты'],['Polotsk · Turov–Pinsk · other Rus’ principalities','Полацкае · Турава-Пінскае · іншыя княствы Русі']]],sources:['atlas']},
    {id:'gdl-formation',date:['13th–14th centuries','XIII–XIV стагоддзі'],kind:'formation',title:['Gradual incorporation into the Grand Duchy','Паступовае ўваходжанне ў ВКЛ'],body:['Belarusian lands entered the Grand Duchy of Lithuania at different times. A single “all Belarus joined in 1240” border would be misleading.','Беларускія землі ўваходзілі ў Вялікае Княства Літоўскае ў розны час. Адзіная мяжа «ўся Беларусь у ВКЛ з 1240 года» была б памылковай.'],areas:[[['Developing state','Дзяржава ў станаўленні'],['Grand Duchy of Lithuania','Вялікае Княства Літоўскае']]],sources:['atlas']},
    {id:'union-1385',year:1385,date:['1385–1386','1385–1386'],kind:'union',title:['A dynastic union, not yet the Commonwealth','Дынастычная унія, яшчэ не Рэч Паспалітая'],body:['The Kreva agreement and Jogaila’s Polish kingship linked the rulers. The Grand Duchy remained a distinct polity; the Commonwealth dates to 1569.','Крэўскае пагадненне і каранацыя Ягайлы ў Польшчы звязалі ўладароў. ВКЛ заставалася асобнай дзяржавай; Рэч Паспалітая ўзнікла ў 1569 годзе.'],areas:[[['Belarusian lands','Беларускія землі'],['Grand Duchy of Lithuania','Вялікае Княства Літоўскае']]],sources:['atlas']},
    {id:'gdl-1500',year:1500,map:1500,date:['1500','1500'],kind:'state',title:['Grand Duchy of Lithuania','Вялікае Княства Літоўскае'],body:['The focused map labels these lands as the Grand Duchy. Its source combines the outer Polish–Lithuanian area, so it cannot establish the duchy’s own full boundary.','Мапа фокусу называе гэтыя землі ВКЛ. Крыніца аб’ядноўвае знешнюю польска-літоўскую тэрыторыю і таму не вызначае асобнай поўнай мяжы княства.'],areas:[[['Local affiliation','Мясцовая прыналежнасць'],['Grand Duchy of Lithuania','Вялікае Княства Літоўскае']]],sources:['atlas']},
    {id:'lublin-1569',year:1569,date:['1569','1569'],kind:'union',title:['Grand Duchy within the Commonwealth','ВКЛ у складзе Рэчы Паспалітай'],body:['The Union of Lublin created a shared Commonwealth. The Grand Duchy retained separate institutions: “Belarus became Poland” is not an adequate description.','Люблінская унія стварыла агульную Рэч Паспалітую. ВКЛ захавала асобныя ўстановы: тлумачэнне «Беларусь стала Польшчай» недакладнае.'],areas:[[['State framework','Дзяржаўная сістэма'],['Polish–Lithuanian Commonwealth','Рэч Паспалітая']],[['Constituent polity','Складовая дзяржава'],['Grand Duchy of Lithuania','Вялікае Княства Літоўскае']]],sources:['atlas']},
    {id:'commonwealth-1700',year:1700,map:1700,date:['1700','1700'],kind:'state',title:['The Commonwealth-era affiliation','Прыналежнасць у эпоху Рэчы Паспалітай'],body:['The map supplies a dated territorial comparison. It is not a reconstruction of moving battlefronts during the Great Northern War.','Мапа дае датаванае тэрытарыяльнае параўнанне, а не рэканструкцыю рухомых франтоў Паўночнай вайны.'],areas:[[['Belarusian lands','Беларускія землі'],['Grand Duchy of Lithuania within the Commonwealth','ВКЛ у складзе Рэчы Паспалітай']]],sources:['atlas']},
    {id:'partition-1772',year:1772,date:['1772 · first partition','1772 · першы падзел'],kind:'partition',title:['Eastern lands transferred to Russia','Усходнія землі пераходзяць да Расіі'],body:['The first partition split the lands: eastern and northeastern areas passed to the Russian Empire, while the remainder stayed in the Commonwealth.','Першы падзел падзяліў землі: усходнія і паўночна-ўсходнія тэрыторыі перайшлі да Расійскай імперыі, астатнія засталіся ў Рэчы Паспалітай.'],areas:[[['East / northeast','Усход / паўночны ўсход'],['Russian Empire','Расійская імперыя']],[['Remaining lands','Астатнія землі'],['Grand Duchy within the Commonwealth','ВКЛ у Рэчы Паспалітай']]],sources:['partitions']},
    {id:'partition-1793',year:1793,date:['1793 · second partition','1793 · другі падзел'],kind:'partition',title:['The division moves westward','Лінія падзелу зрушваецца на захад'],body:['Russia acquired central Belarusian lands, including Minsk. Western lands remained in the reduced Commonwealth until the next partition.','Расія атрымала цэнтральныя беларускія землі, у тым ліку Мінск. Заходнія землі заставаліся ў зменшанай Рэчы Паспалітай да наступнага падзелу.'],areas:[[['Central and eastern lands','Цэнтральныя і ўсходнія землі'],['Russian Empire','Расійская імперыя']],[['Western remainder','Заходняя рэшта'],['Commonwealth','Рэч Паспалітая']]],sources:['partitions']},
    {id:'partition-1795',year:1795,aliases:[1800],date:['1795–1807','1795–1807'],kind:'partition',title:['Mostly Russia — with a Prussian western exception','Пераважна Расія — з прускім выключэннем на захадзе'],body:['After the final partition, most of the reference area was Russian. A small western area, including Adelsk and Sapoćkin, was Prussian until 1807.','Пасля апошняга падзелу большая частка контуру была расійскай. Невялікі заходні ўчастак, у тым ліку Адэльск і Сапоцкін, быў прускім да 1807 года.'],areas:[[['Most of the reference area','Большая частка контуру'],['Russian Empire','Расійская імперыя']],[['Small western area','Невялікая заходняя частка'],['Kingdom of Prussia','Каралеўства Прусія']]],sources:['partitions','west'],geometryNote:['The candidate 1800 dataset puts the known Prussian area near Sapoćkin in Russia. That map is excluded, rather than publishing a misleading fill.','Набор за 1800 год памылкова адносіць вядомы прускі ўчастак каля Сапоцкіна да Расіі. Мапа выключаная, каб не публікаваць памылковую залівку.']},
    {id:'tilsit-1807',year:1807,date:['1807','1807'],kind:'transfer',title:['The western exception passes to Russia','Заходняе выключэнне пераходзіць да Расіі'],body:['The Treaty of Tilsit transferred the Białystok region from Prussia to Russia. This includes the previously Prussian area inside the modern Belarus reference.','Паводле Тыльзіцкага міру Беластоцкая вобласць перайшла ад Прусіі да Расіі, уключаючы раней прускі ўчастак у сучасным беларускім контуры.'],areas:[[['Political affiliation','Палітычная прыналежнасць'],['Russian Empire','Расійская імперыя']]],sources:['tilsit','west']},
    {id:'empire-1914',year:1914,map:1914,date:['1914 · before the war','1914 · перад вайной'],kind:'state',title:['Within the Russian Empire','У складзе Расійскай імперыі'],body:['This prewar snapshot precedes the German occupation and the new state projects that emerged during the war and revolution.','Гэты перадваенны зрэз папярэднічае германскай акупацыі і новым дзяржаўным праектам часоў вайны і рэвалюцыі.'],areas:[[['Reference area','Тэрыторыя контуру'],['Russian Empire','Расійская імперыя']]],sources:['war']},
    {id:'occupation-1915',year:1915,date:['1915–1918','1915–1918'],kind:'occupation',title:['A front divides the lands','Фронт падзяляе землі'],body:['German forces occupied western areas; the front cut through Belarusian lands. The extent changed over time and requires precisely dated occupation maps.','Германскія войскі занялі заходнія тэрыторыі; фронт прайшоў праз беларускія землі. Яго становішча змянялася і патрабуе дакладна датаваных мапаў акупацыі.'],areas:[[['Control, not a permanent state border','Кантроль, а не сталая дзяржаўная мяжа'],['German occupation / Russian-controlled areas','Германская акупацыя / тэрыторыі пад расійскім кантролем']]],sources:['war']},
    {id:'bnr-1918',year:1918,date:['25 March 1918','25 сакавіка 1918'],kind:'declaration',title:['Belarusian Democratic Republic declared','Абвешчана Беларуская Народная Рэспубліка'],body:['The BNR proclaimed independence during German occupation. Its charter expressed a state project and territorial claims; declaration must not be colored as complete territorial control.','БНР абвясціла незалежнасць падчас германскай акупацыі. Грамата выказвала дзяржаўны праект і тэрытарыяльныя прэтэнзіі; абвяшчэнне не азначае поўнага кантролю тэрыторыі.'],areas:[[['Declared state','Абвешчаная дзяржава'],['Belarusian Democratic Republic','Беларуская Народная Рэспубліка']],[['Military context','Ваенны кантэкст'],['German occupation','Германская акупацыя']]],sources:['bnr','war']},
    {id:'contested-1919',year:1919,date:['1919–1920','1919–1920'],kind:'conflict',title:['Competing governments and shifting control','Канкуруючыя ўрады і зменлівы кантроль'],body:['Soviet Belarus, Litbel, Polish control and renewed Soviet power followed in rapid succession. No single polygon can truthfully represent the entire two-year period.','Савецкая Беларусь, Літбел, польскі кантроль і адноўленая савецкая ўлада хутка змянялі адно аднаго. Адзін палігон не можа праўдзіва адлюстраваць увесь двухгадовы перыяд.'],areas:[[['Sequence of authorities','Паслядоўнасць уладаў'],['Soviet Belarus · Litbel · Polish and Soviet control','Савецкая Беларусь · Літбел · польскі і савецкі кантроль']]],sources:['war','atlas']},
    {id:'riga-1921',year:1921,date:['18 March 1921','18 сакавіка 1921'],kind:'partition',title:['Riga: a divided Belarusian space','Рыга: падзеленая беларуская прастора'],body:['The peace divided the lands between Poland and Soviet republics. The easternmost areas had not yet been transferred from the Russian SFSR to the Belarusian SSR.','Мір падзяліў землі паміж Польшчай і савецкімі рэспублікамі. Найбольш усходнія тэрыторыі яшчэ не былі перададзеныя з РСФСР у БССР.'],areas:[[['West','Захад'],['Polish Republic','Польская Рэспубліка']],[['Center','Цэнтр'],['Belarusian SSR','Беларуская ССР']],[['East','Усход'],['Russian SFSR','Расійская СФСР']]],sources:['atlas']},
    {id:'ussr-1922',year:1922,date:['30 December 1922','30 снежня 1922'],kind:'union',title:['The Belarusian SSR joins the Soviet Union','Беларуская ССР уваходзіць у СССР'],body:['Union membership adds a new political level. Poland remains to the west; the Belarusian and Russian Soviet republics are now within the USSR.','Саюзная прыналежнасць дадае новы палітычны ўзровень. На захадзе застаецца Польшча; Беларуская і Расійская савецкія рэспублікі цяпер уваходзяць у СССР.'],areas:[[['West','Захад'],['Polish Republic','Польская Рэспубліка']],[['Center and east','Цэнтр і ўсход'],['Belarusian SSR / Russian SFSR within the USSR','Беларуская ССР / РСФСР у складзе СССР']]],sources:['atlas']},
    {id:'bssr-1924',year:1924,date:['1924','1924'],kind:'internal',title:['The Belarusian SSR expands eastward','Беларуская ССР пашыраецца на ўсход'],body:['Territories transferred from the Russian SFSR enlarged the Belarusian SSR. This changed an internal Soviet boundary, not the USSR’s international border.','Перадача тэрыторый з РСФСР павялічыла Беларускую ССР. Змянілася ўнутраная савецкая мяжа, а не міждзяржаўная мяжа СССР.'],areas:[[['Sovereign framework','Саюзная дзяржава'],['USSR','СССР']],[['Internal transfer','Унутраная перадача'],['Russian SFSR → Belarusian SSR','РСФСР → Беларуская ССР']]],sources:['atlas']},
    {id:'bssr-1926',year:1926,date:['1926','1926'],kind:'internal',title:['Homiel and Rečyca transferred to the Belarusian SSR','Гомель і Рэчыца перададзеныя Беларускай ССР'],body:['A further transfer from the Russian SFSR changed the republic boundary. It must not be represented as a new international state border.','Наступная перадача з РСФСР змяніла мяжу рэспублікі. Яе нельга падаваць як новую міждзяржаўную мяжу.'],areas:[[['Sovereign framework','Саюзная дзяржава'],['USSR','СССР']],[['Internal transfer','Унутраная перадача'],['Russian SFSR → Belarusian SSR','РСФСР → Беларуская ССР']]],sources:['atlas']},
    {id:'division-1938',year:1938,map:1938,date:['1938','1938'],kind:'state',title:['Poland in the west; Soviet Belarus in the east','Польшча на захадзе; савецкая Беларусь на ўсходзе'],body:['This mapped snapshot makes the interwar division visible. Brest and Hrodna lie on the Polish side; Minsk, Viciebsk and Homiel on the Soviet side.','Гэты геаметрычны зрэз паказвае міжваенны падзел. Брэст і Гродна знаходзяцца з польскага боку; Мінск, Віцебск і Гомель — з савецкага.'],areas:[[['West','Захад'],['Polish Republic','Польская Рэспубліка']],[['East','Усход'],['Belarusian SSR within the USSR','Беларуская ССР у складзе СССР']]],sources:['atlas']},
    {id:'invasion-1939',year:1939,date:['September–November 1939','Верасень–лістапад 1939'],kind:'occupation',title:['Soviet invasion and incorporation of western lands','Савецкае ўварванне і ўключэнне заходніх зямель'],body:['The USSR invaded eastern Poland on 17 September. Western Belarusian lands were subsequently incorporated into the Belarusian SSR; the whole year cannot share one boundary.','17 верасня СССР уварваўся ва ўсходнюю Польшчу. Заходнебеларускія землі затым уключылі ў БССР; увесь год нельга паказваць адной мяжой.'],areas:[[['Before / after transition','Да / пасля пераходу'],['Polish Republic → Belarusian SSR within USSR','Польская Рэспубліка → Беларуская ССР у СССР']]],sources:['atlas']},
    {id:'occupation-1941',year:1941,date:['1941–1944','1941–1944'],kind:'occupation',title:['Nazi German occupation','Нацысцкая германская акупацыя'],body:['Military occupation and occupation administrations are not equivalent to Belarus legally becoming Germany. Fronts and administrative zones require separate, date-specific layers.','Ваенная акупацыя і акупацыйныя адміністрацыі не азначаюць, што Беларусь юрыдычна стала Германіяй. Франты і адміністрацыйныя зоны патрабуюць асобных датаваных пластоў.'],areas:[[['De facto military context','Фактычны ваенны кантэкст'],['Nazi German occupation; Soviet control returns in 1944','Нацысцкая германская акупацыя; вяртанне савецкага кантролю ў 1944 годзе']]],sources:['state','atlas']},
    {id:'postwar-1945',year:1945,map:1945,date:['1945','1945'],kind:'transfer',title:['The postwar Polish–Soviet settlement','Пасляваеннае польска-савецкае ўрэгуляванне'],body:['The August border agreement placed Białystok on the Polish side. The mapped source is a generalized postwar snapshot, not every local adjustment or Soviet republic boundary.','Жнівеньская дамова аб мяжы пакінула Беласток з польскага боку. Крыніца мапы — абагульнены пасляваенны зрэз, а не ўсе мясцовыя карэкціроўкі або межы саюзных рэспублік.'],areas:[[['Modern Belarus reference','Сучасны беларускі контур'],['Belarusian SSR within the USSR','Беларуская ССР у складзе СССР']]],sources:['atlas']},
    {id:'sovereignty-1990',year:1990,date:['27 July 1990','27 ліпеня 1990'],kind:'declaration',title:['Declaration of sovereignty','Дэкларацыя аб суверэнітэце'],body:['The sovereignty declaration preceded independence. These are distinct constitutional steps, not two interchangeable dates for a new country boundary.','Дэкларацыя аб суверэнітэце папярэднічала незалежнасці. Гэта розныя канстытуцыйныя крокі, а не ўзаемазаменныя даты новай дзяржаўнай мяжы.'],areas:[[['Status at this stage','Статус на гэтым этапе'],['Belarusian SSR; sovereignty declared','Беларуская ССР; абвешчаны суверэнітэт']]],sources:['state']},
    {id:'independence-1991',year:1991,date:['1991','1991'],kind:'independence',title:['Independent Belarus','Незалежная Беларусь'],body:['Independence: 25 August. The name Republic of Belarus: 19 September. The separate 1994 map below is a later geometry snapshot, not the independence date.','Незалежнасць — 25 жніўня. Назва Рэспубліка Беларусь — 19 верасня. Асобная мапа за 1994 год — пазнейшы геаметрычны зрэз, а не дата незалежнасці.'],areas:[[['State affiliation','Дзяржаўная прыналежнасць'],['Independent Belarus → Republic of Belarus','Незалежная Беларусь → Рэспубліка Беларусь']]],sources:['state','un']},
    {id:'republic-1994',year:1994,map:1994,date:['1994 · available map year','1994 · даступны год мапы'],kind:'state',title:['The independent republic on the map','Незалежная рэспубліка на мапе'],body:['This source provides a separate Belarus polygon. The sovereign change occurred in 1991; the map’s date describes the dataset, not the start of statehood.','Крыніца дае асобны палігон Беларусі. Суверэнны пераход адбыўся ў 1991 годзе; дата мапы апісвае набор даных, а не пачатак дзяржаўнасці.'],areas:[[['State affiliation','Дзяржаўная прыналежнасць'],['Republic of Belarus','Рэспубліка Беларусь']]],sources:['state','un']}
  ];
  const homiel=records.find(r=>r.id==='gdl-1500');delete homiel.map;homiel.kind='transfer';homiel.title=['A transition year: Homiel changes allegiance','Пераходны год: Гомель змяняе прыналежнасць'];homiel.body=['Homiel passed from the Grand Duchy to Moscow in 1500; it returned in 1535. The available annual polygon has no precise date and cannot reliably show this transition, so it is not displayed.','У 1500 годзе Гомель перайшоў ад ВКЛ да Масквы; у 1535 годзе вярнуўся. Даступны гадавы палігон не мае дакладнай даты і не паказвае гэты пераход надзейна, таму не публікуецца.'];homiel.areas=[[['Broad political context','Агульны палітычны кантэкст'],['Grand Duchy of Lithuania','Вялікае Княства Літоўскае']],[['Homiel’s change during 1500','Пераход Гомеля на працягу 1500 года'],['Grand Duchy of Lithuania → Muscovy','Вялікае Княства Літоўскае → Маскоўская дзяржава']]];homiel.sources=['homiel','atlas'];
  const tilsit=records.find(r=>r.id==='tilsit-1807');tilsit.title=['Different political paths in the west','Розныя палітычныя шляхі на захадзе'];tilsit.body=['Tilsit transferred the Białystok region to Russia, but not every former Prussian area followed that path. Sapoćkin became part of the Duchy of Warsaw.','Паводле Тыльзіцкага міру Беластоцкая вобласць перайшла да Расіі, але не ўсе былыя прускія землі пайшлі тым жа шляхам. Сапоцкін увайшоў у Варшаўскае герцагства.'];tilsit.areas=[[['Białystok region, including Adelsk','Беластоцкая вобласць, уключаючы Адэльск'],['Russian Empire','Расійская імперыя']],[['Sapoćkin area','Сапоцкінскі ўчастак'],['Duchy of Warsaw','Варшаўскае герцагства']]];tilsit.sources=['tilsit','warsaw','sapockin'];
  records.splice(records.indexOf(tilsit)+1,0,{id:'congress-1815',year:1815,date:['1815','1815'],kind:'union',title:['A kingdom under the Russian emperor','Каралеўства пад уладай расійскага імператара'],body:['The Sapoćkin area entered Congress Poland, whose monarch was the Russian emperor. This local constitutional history differs from direct incorporation into an imperial province in 1807.','Сапоцкінскі ўчастак увайшоў у Царства Польскае, манархам якога быў расійскі імператар. Гэтая мясцовая канстытуцыйная гісторыя адрозніваецца ад прамога ўключэння ў імперскую вобласць у 1807 годзе.'],areas:[[['Most Belarusian lands','Большасць беларускіх зямель'],['Russian Empire','Расійская імперыя']],[['Sapoćkin area','Сапоцкінскі ўчастак'],['Congress Poland under the Russian emperor','Царства Польскае пад уладай расійскага імператара']]],sources:['sapockin','congress']});
  tilsit.sources=['tilsit','census','warsaw'];
  records.find(r=>r.id==='postwar-1945').sources=['postwar','atlas'];
  const count=records.filter(r=>r.map).length;
  const words={en:{mapTab:`Territory map · ${count} source years`,timelineTab:`Political chronology · ${records.length} stages`,eyebrow:'02 · Political chronology',title:'One place. More than one political story.',intro:'Follow the changes that a handful of map snapshots cannot explain. State membership, a republic’s internal boundary, a declaration, and military occupation are different things.',choose:'Choose a transition',previous:'Previous',next:'Next',sources:'Sources for this transition',openMap:'Open this dated map',scope:'Scope: lands inside the modern Belarus outline, not an unchanging ethnic or national territory. This is a selected chronology, not the original MAPA’s complete 63-state sequence.',unmapped:'Context only — no verified geometry for this exact stage. No other year’s borders are substituted.',mapped:'A dated source geometry is available. Open it to inspect the political division and its accuracy notes.',kinds:{formation:'Gradual political formation',union:'Union / constitutional framework',state:'Dated affiliation snapshot',partition:'Partition / territorial division',transfer:'Territorial transfer',occupation:'Military occupation / control',declaration:'Declaration — not proof of full control',conflict:'Contested rule / changing front',internal:'Internal republic boundary',independence:'Independent statehood'}},be:{mapTab:`Тэрытарыяльная мапа · ${count} гадоў`,timelineTab:`Палітычная храналогія · ${records.length} этапаў`,eyebrow:'02 · Палітычная храналогія',title:'Адно месца. Некалькі палітычных гісторый.',intro:'Прасачыце змены, якія некалькі мапаў не могуць растлумачыць. Дзяржаўная прыналежнасць, унутраная мяжа рэспублікі, дэкларацыя і ваенная акупацыя — розныя рэчы.',choose:'Абярыце пераход',previous:'Назад',next:'Далей',sources:'Крыніцы гэтага пераходу',openMap:'Адкрыць гэтую датаваную мапу',scope:'Фокус: землі ў сучасным беларускім контуры, а не нязменная этнічная або нацыянальная тэрыторыя. Гэта выбраная храналогія, а не ўсе 63 станы арыгінальнай MAPA.',unmapped:'Толькі кантэкст — праверанай геаметрыі гэтага дакладнага этапу няма. Межы іншага года не падстаўляюцца.',mapped:'Даступная датаваная геаметрыя крыніцы. Адкрыйце яе, каб убачыць падзел і заўвагі аб дакладнасці.',kinds:{formation:'Паступовае палітычнае станаўленне',union:'Унія / канстытуцыйная сістэма',state:'Датаваны зрэз прыналежнасці',partition:'Падзел тэрыторыі',transfer:'Тэрытарыяльная перадача',occupation:'Ваенная акупацыя / кантроль',declaration:'Абвяшчэнне — не доказ поўнага кантролю',conflict:'Спрэчная ўлада / зменлівы фронт',internal:'Унутраная мяжа рэспублікі',independence:'Незалежная дзяржаўнасць'}}};
  const $=id=>document.getElementById(id),local=x=>x[document.documentElement.lang==='be'?1:0],t=key=>words[document.documentElement.lang==='be'?'be':'en'][key];
  let current=records.findIndex(r=>r.id==='division-1938'),panel='borders';
  function setPanel(next,canonical=false){panel=next;$('borders').hidden=panel!=='borders';$('chronology').hidden=panel!=='chronology';document.querySelectorAll('[data-history-panel]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.historyPanel===panel)));if(panel==='chronology')window.dispatchEvent(new Event('mapa-pause-history'));else if(canonical)window.dispatchEvent(new Event('mapa-canonical-map'))}
  function render(){
    document.querySelectorAll('[data-chrono]').forEach(el=>el.textContent=t(el.dataset.chrono));
    const record=records[current],select=$('chronology-stage');select.replaceChildren();
    for(const r of records){const o=document.createElement('option');o.value=r.id;o.textContent=`${local(r.date)} · ${local(r.title)}`;select.append(o)}select.value=record.id;
    $('chronology-range').max=records.length-1;$('chronology-range').value=current;$('chronology-range').setAttribute('aria-valuetext',local(record.date));$('chronology-position').textContent=`${current+1} / ${records.length}`;
    $('chronology-prev').disabled=current===0;$('chronology-next').disabled=current===records.length-1;
    $('chronology-kind').textContent=`${local(record.date)} · ${t('kinds')[record.kind]}`;$('chronology-stage-title').textContent=local(record.title);$('chronology-body').textContent=local(record.body);
    $('chronology-affiliation').replaceChildren();for(const [area,polity] of record.areas){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=local(area);dd.textContent=local(polity);div.append(dt,dd);$('chronology-affiliation').append(div)}
    $('chronology-geometry').textContent=record.geometryNote?`${t('unmapped')} ${local(record.geometryNote)}`:t(record.map?'mapped':'unmapped');$('chronology-geometry').dataset.geometry=record.map?'mapped':'context-only';$('chronology-open-map').hidden=!record.map;
    $('chronology-sources').replaceChildren();for(const id of record.sources){const source=sources[id],a=document.createElement('a');a.href=source.url;a.textContent=source.label+' ↗';a.target='_blank';a.rel='noopener noreferrer';$('chronology-sources').append(a)}
  }
  function choose(i){current=Math.max(0,Math.min(records.length-1,i));setPanel('chronology');const url=new URL(location.href);url.searchParams.set('stage',records[current].id);url.hash='chronology';history.replaceState({},'',url);render()}
  document.querySelectorAll('[data-history-panel]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.historyPanel==='chronology'&&panel==='borders'){const year=+new URLSearchParams(location.search).get('year')||1938,found=records.findIndex(r=>r.map===year);if(found>=0)current=found}setPanel(button.dataset.historyPanel,true);const url=new URL(location.href);if(panel==='chronology')url.searchParams.set('stage',records[current].id);else url.searchParams.delete('stage');url.hash=panel;history.replaceState({},'',url);render()}));
  $('chronology-stage').addEventListener('change',e=>choose(records.findIndex(r=>r.id===e.target.value)));$('chronology-range').addEventListener('input',e=>choose(+e.target.value));$('chronology-prev').addEventListener('click',()=>choose(current-1));$('chronology-next').addEventListener('click',()=>choose(current+1));
  $('chronology-open-map').addEventListener('click',()=>{const record=records[current];if(!record.map)return;setPanel('borders');const url=new URL(location.href);url.searchParams.delete('stage');history.replaceState({},'',url);window.dispatchEvent(new CustomEvent('mapa-select-year',{detail:record.map}))});
  document.querySelectorAll('a[href="#borders"]').forEach(a=>a.addEventListener('click',()=>setPanel('borders',true)));
  const routeNotice=document.createElement('p');routeNotice.id='history-route-notice';routeNotice.role='status';routeNotice.hidden=true;document.querySelector('.mapa-history-tabs').before(routeNotice);
  function readURL(){const p=new URLSearchParams(location.search),stage=p.get('stage'),year=+p.get('year');const found=records.findIndex(r=>r.id===stage||(!stage&&!records.some(item=>item.map===year)&&(r.year===year||r.aliases?.includes(year))));if(found>=0){current=found;setPanel('chronology')}else if(location.hash==='#chronology')setPanel('chronology');else{setPanel('borders');if((year&&!records.some(r=>r.map===year))||(stage&&!records.some(r=>r.id===stage))){routeNotice.hidden=false;routeNotice.textContent=local([`The requested stage (${stage||year}) is not available. Showing the explicitly dated 1938 map, not an inferred border for that stage.`,`Запытаны этап (${stage||year}) недаступны. Паказана датаваная мапа 1938 года, а не выдуманая мяжа запытанага этапу.`]);setPanel('borders',true)}}}
  window.addEventListener('mapa-read-context',event=>{const found=records.findIndex(r=>r.map===event.detail);if(found>=0){choose(found);$('chronology').scrollIntoView({behavior:'smooth'})}});
  window.addEventListener('popstate',()=>{readURL();render()});new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  window.MAPA_CHRONOLOGY=Object.freeze(records.map(r=>Object.freeze({...r})));
  readURL();render();
})();
