(() => {
  'use strict';
  const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
  const eras=[
    {year:1500,match:['Poland-Lithuania'],title:['Poland and the Grand Duchy of Lithuania','Польшча і Вялікае Княства Літоўскае'],body:['The source groups the two realms under their shared dynasty. Belarusian lands belonged to the Grand Duchy of Lithuania; this combined polygon is not a separate map of the duchy.','Крыніца аб’ядноўвае дзве дзяржавы пад агульнай дынастыяй. Беларускія землі ўваходзілі ў Вялікае Княства Літоўскае; гэты агульны палігон не з’яўляецца асобнай мапай княства.'],warning:['Before the 1569 Union of Lublin: do not read this combined outline as the later Commonwealth or as modern Belarus.','Да Люблінскай уніі 1569 года: не блытайце агульны контур з пазнейшай Рэччу Паспалітай або сучаснай Беларуссю.'],change:['Starting snapshot. The highlighted territory extends well beyond today’s Belarus. Turn on the dashed modern reference to compare.','Пачатковы зрэз. Вылучаная тэрыторыя значна шырэйшая за сучасную Беларусь. Уключыце пункцірны сучасны контур для параўнання.']},
    {year:1700,match:['Polish–Lithuanian Commonwealth'],title:['The Polish–Lithuanian Commonwealth','Рэч Паспалітая'],body:['The map now shows the Commonwealth’s regional outline. Compare its eastern edge with the earlier source snapshot; the highlighted polygon itself changes.','Мапа паказвае рэгіянальны контур Рэчы Паспалітай. Параўнайце ўсходнюю мяжу з папярэднім зрэзам: змяняецца сам вылучаны палігон.'],warning:['A regional snapshot, not a map of front lines during the Great Northern War.','Рэгіянальны зрэз, а не мапа франтоў падчас Паўночнай вайны.'],change:['The composite dynastic-region layer is replaced by the later Commonwealth geometry. The 1569 and seventeenth-century transitions between them are not animated as invented intermediate borders.','Пласт дынастычнага аб’яднання замяняецца пазнейшай геаметрыяй Рэчы Паспалітай. Пераходы 1569 года і XVII стагоддзя не падмяняюцца выдуманымі прамежкавымі межамі.']},
    {year:1800,match:['Russian Empire'],title:['After the partitions','Пасля падзелаў'],body:['Following the partitions of 1772, 1793 and 1795, the lands of present-day Belarus were within the Russian Empire. The visible extent is the empire clipped to this regional window.','Пасля падзелаў 1772, 1793 і 1795 гадоў землі сучаснай Беларусі ўваходзілі ў Расійскую імперыю. Бачная частка імперыі абмежаваная акном гэтай рэгіянальнай мапы.'],warning:['The full Russian Empire extends beyond the frame. Its shape must not be described as the territory of Belarus.','Расійская імперыя выходзіць за межы кадра. Яе контур нельга называць тэрыторыяй Беларусі.'],change:['The Commonwealth disappears from this source snapshot and the Russian imperial polygon replaces it across Belarusian lands.','Рэч Паспалітая знікае з гэтага зрэзу; на беларускіх землях яе замяняе палігон Расійскай імперыі.']},
    {year:1914,match:['Russian Empire'],title:['The region before the First World War','Рэгіён перад Першай сусветнай вайной'],body:['The imperial context remains, but the western territorial configuration differs from 1800. Use the previous-territory overlay to inspect that difference rather than relying on a change of name.','Імперскі кантэкст захоўваецца, але канфігурацыя заходніх тэрыторый адрозніваецца ад 1800 года. Уключыце папярэдні контур, каб пабачыць розніцу, а не толькі назву.'],warning:['A dated political map, not a day-by-day wartime occupation map.','Палітычная мапа на абраны год, а не штодзённая мапа ваеннай акупацыі.'],change:['The western extent changes, including the imperial boundary in the Polish lands. Belarusian lands remain inside the larger empire.','Змяняецца заходняя частка, у тым ліку імперская мяжа на польскіх землях. Беларускія землі застаюцца ўнутры большай імперыі.']},
    {year:1938,match:['USSR','Poland'],title:['Belarusian lands divided between states','Беларускія землі падзеленыя паміж дзяржавамі'],body:['The interwar map shows Poland to the west and the USSR to the east. Western Belarus was in Poland; the Belarusian SSR was part of the USSR.','Міжваенная мапа паказвае Польшчу на захадзе і СССР на ўсходзе. Заходняя Беларусь была ў складзе Польшчы, Беларуская ССР — у складзе СССР.'],warning:['Only the USSR’s external boundary is available in this layer. No internal Belarusian SSR border is drawn.','У гэтым пласце ёсць толькі знешняя мяжа СССР. Унутраная мяжа Беларускай ССР не намаляваная.'],change:['One imperial space is replaced by distinct interwar state polygons. Two colors make the division visible on the map.','Адну імперскую прастору замяняюць асобныя палігоны міжваенных дзяржаў. Два колеры паказваюць падзел на мапе.']},
    {year:1945,match:['USSR','Poland'],title:['The postwar territorial arrangement','Пасляваенны тэрытарыяльны падзел'],body:['The source’s 1945 snapshot shows the Soviet boundary farther west and Poland’s shifted outline. Compare it directly with 1938 to see the territorial change.','Зрэз крыніцы за 1945 год паказвае савецкую мяжу далей на захад і зменены контур Польшчы. Параўнайце з 1938 годам, каб пабачыць тэрытарыяльныя змены.'],warning:['A generalized postwar snapshot; not every 1945 treaty date or later local adjustment is represented. Internal SSR boundaries are absent.','Абагульнены пасляваенны зрэз: не ўсе даты дамоваў 1945 года і пазнейшыя мясцовыя карэкціроўкі адлюстраваныя. Унутраных межаў ССР няма.'],change:['The Poland–USSR boundary moves west relative to 1938. The map changes the actual state polygons; the optional coral contour preserves the previous view for comparison.','Мяжа Польшчы і СССР зрушваецца на захад адносна 1938 года. Мапа змяняе самі палігоны; каралавы контур захоўвае папярэдні выгляд для параўнання.']},
    {year:1994,match:['Byelarus'],title:['Belarus as an independent state','Беларусь як незалежная дзяржава'],body:['Belarus is now represented as its own state polygon, alongside Lithuania, Poland, Russia and Ukraine. This is the dataset’s 1994 map, not a claim that independence began in 1994.','Беларусь паказаная асобным дзяржаўным палігонам побач з Літвой, Польшчай, Расіяй і Украінай. Гэта мапа набору даных за 1994 год, а не сцвярджэнне, што незалежнасць пачалася ў 1994 годзе.'],warning:['Independence dates to 1991. The selected geometry is the available 1994 snapshot.','Незалежнасць адносіцца да 1991 года. Абраная геаметрыя — даступны зрэз за 1994 год.'],change:['The USSR polygon is replaced by the separate outlines of the successor states. Belarus’s own outline is highlighted.','Палігон СССР замяняецца асобнымі контурамі дзяржаў. Вылучаны ўласны контур Беларусі.']}
  ];
  const focusNotes={
    1500:{title:['The Grand Duchy of Lithuania','Вялікае Княства Літоўскае'],body:['The lands shown here were predominantly part of the Grand Duchy of Lithuania. The source combines its outer polygon with Poland; inside the fixed Belarus reference, the label describes the duchy rather than calling these lands Poland.','Паказаныя землі пераважна ўваходзілі ў Вялікае Княства Літоўскае. Крыніца аб’ядноўвае яго знешні палігон з Польшчай; у межах сталага беларускага контуру подпіс называе княства, а не падмяняе яго Польшчай.'],change:['The same Belarusian reference area stays on screen. Colors identify political affiliation within it; the full extent of neighboring states is optional.','Той самы беларускі контур застаецца на экране. Колеры паказваюць палітычную прыналежнасць унутры яго; поўныя контуры суседніх дзяржаў можна ўключыць асобна.']},
    1700:{title:['Grand Duchy of Lithuania within the Commonwealth','ВКЛ у складзе Рэчы Паспалітай'],body:['After the Union of Lublin in 1569, the Grand Duchy of Lithuania was a constituent part of the Polish–Lithuanian Commonwealth. These are not simply Polish lands: the duchy retained its own institutions.','Пасля Люблінскай уніі 1569 года Вялікае Княства Літоўскае было складовай часткай Рэчы Паспалітай. Гэта не проста польскія землі: княства захоўвала ўласныя ўстановы.'],change:['The state framework changes from the earlier dynastic relationship to the Commonwealth, while the Belarusian lands remain the focus. This map is the available 1700 snapshot, not an invented exact 1569 boundary.','Змяняецца дзяржаўная сістэма: замест ранейшай дынастычнай сувязі — Рэч Паспалітая. Фокус застаецца на беларускіх землях. Гэта даступны зрэз за 1700 год, а не выдуманая дакладная мяжа 1569 года.']},
    1800:{title:['Russian Empire','Расійская імперыя'],body:['After the three partitions of the Commonwealth, the lands of present-day Belarus were incorporated into the Russian Empire. Only the intersection with the fixed Belarus reference is colored here.','Пасля трох падзелаў Рэчы Паспалітай землі сучаснай Беларусі былі ўключаныя ў Расійскую імперыю. Тут афарбаванае толькі перасячэнне са сталым беларускім контурам.'],warning:['The partitions happened in 1772, 1793 and 1795. This source supplies a post-partition 1800 map, not verified polygons for each intermediate division.','Падзелы адбыліся ў 1772, 1793 і 1795 гадах. Крыніца дае мапу пасля іх за 1800 год, а не правераныя палігоны кожнага прамежкавага падзелу.'],change:['The affiliation of these lands changes from the Commonwealth to the Russian Empire. The view no longer substitutes the empire’s enormous overall outline for Belarus.','Прыналежнасць гэтых зямель змяняецца з Рэчы Паспалітай на Расійскую імперыю. Выгляд больш не падмяняе Беларусь велізарным агульным контурам імперыі.']},
    1914:{title:['Still within the Russian Empire','Па-ранейшаму ў Расійскай імперыі'],body:['Before the First World War, the lands in this reference area were still part of the Russian Empire. The affiliation remains the same as in the previous mapped snapshot; no territorial change is invented to make the animation busier.','Перад Першай сусветнай вайной землі гэтага контуру ўсё яшчэ ўваходзілі ў Расійскую імперыю. Прыналежнасць тая ж, што ў папярэднім зрэзе; змены не выдумляюцца дзеля анімацыі.'],change:['Continuity in political affiliation. The wider-region mode can show external imperial changes, but those are a different question from who governed these Belarusian lands.','Захаванне палітычнай прыналежнасці. Рэжым рэгіёна паказвае змены знешніх межаў імперыі, але гэта іншае пытанне, чым тое, хто кіраваў гэтымі беларускімі землямі.']},
    1938:{title:['Two political jurisdictions','Дзве палітычныя прыналежнасці'],body:['Western Belarus was within the Polish Republic. Eastern Belarusian lands were in the Soviet Union, primarily in the Belarusian SSR. The dividing line is the intersection of the source’s actual Polish and Soviet polygons with the constant Belarus reference.','Заходняя Беларусь была ў складзе Польскай Рэспублікі. Усходнія беларускія землі знаходзіліся ў СССР, пераважна ў Беларускай ССР. Лінія падзелу атрымана перасячэннем польскага і савецкага палігонаў крыніцы са сталым беларускім контурам.'],warning:['The source resolves the international Polish–Soviet division, not the internal USSR republic boundaries. “Belarusian SSR” is political context, not a separately digitized polygon here.','Крыніца адлюстроўвае міждзяржаўны польска-савецкі падзел, а не ўнутраныя межы рэспублік СССР. «Беларуская ССР» тут — палітычны кантэкст, а не асобна алічбаваны палігон.'],change:['One area, two colors and two jurisdictions. Select Brest and Minsk below the map to see the difference directly.','Адзін контур, два колеры і дзве палітычныя прыналежнасці. Абярыце Брэст і Мінск пад мапай, каб непасрэдна пабачыць розніцу.']},
    1945:{match:['USSR'],title:['Within the Soviet Union','У складзе Савецкага Саюза'],body:['After the wartime changes and postwar settlement, the reference area lies within the Soviet Union. The Belarusian SSR was the relevant constituent republic; its separate internal boundary is not reconstructed by this country-level source.','Пасля ваенных зменаў і пасляваеннага ўрэгулявання гэты контур знаходзіцца ў Савецкім Саюзе. Адпаведнай саюзнай рэспублікай была Беларуская ССР; яе асобную ўнутраную мяжу крыніца дзяржаўнага ўзроўню не рэканструюе.'],change:['The interwar Polish–Soviet division across Belarusian lands disappears from the postwar view. Compare with 1938: the western and eastern parts now share the Soviet-level affiliation.','Міжваенны польска-савецкі падзел беларускіх зямель знікае з пасляваеннага выгляду. Параўнайце з 1938 годам: заходняя і ўсходняя часткі цяпер маюць агульную прыналежнасць на ўзроўні СССР.']},
    1994:{title:['Independent Republic of Belarus','Незалежная Рэспубліка Беларусь'],body:['Following independence in 1991, the Republic of Belarus is itself the state of affiliation. The modern reference stays fixed so the change from an imperial or union framework to a sovereign Belarus is easy to follow.','Пасля здабыцця незалежнасці ў 1991 годзе дзяржавай прыналежнасці з’яўляецца сама Рэспубліка Беларусь. Сучасны контур застаецца сталым, каб было лёгка прасачыць пераход ад імперскай або саюзнай сістэмы да суверэннай Беларусі.'],change:['The Soviet-level affiliation is replaced by the Republic of Belarus. The map uses the available 1994 geometry; 1994 is not presented as the date of independence.','Прыналежнасць на ўзроўні СССР замяняецца Рэспублікай Беларусь. Мапа выкарыстоўвае даступную геаметрыю за 1994 год; гэты год не падаецца як дата незалежнасці.']}
  };
  eras.forEach(era=>Object.assign(era,focusNotes[era.year]));
  // 1800 is deliberately context-only: the coarse source misassigns the
  // historically Prussian area near Sapoćkin to Russia. Do not publish that fill.
  eras.splice(eras.findIndex(era=>era.year===1800),1);
  // Homiel changed allegiance within 1500; the undated yearly source cannot
  // establish which side of that transition its near-total GDL fill describes.
  eras.splice(eras.findIndex(era=>era.year===1500),1);
  eras.find(era=>era.year===1938).title=['Poland and the Soviet Union','Польшча і Савецкі Саюз'];
  eras.find(era=>era.year===1914).body=['Before the First World War, these lands were within the Russian imperial framework. This is a prewar source snapshot, not a map of the occupation or front lines that followed.','Перад Першай сусветнай вайной гэтыя землі знаходзіліся ў расійскай імперскай сістэме. Гэта перадваенны зрэз крыніцы, а не мапа пазнейшай акупацыі або франтоў.'];
  eras.find(era=>era.year===1914).change=['The Commonwealth-era affiliation is replaced by the Russian imperial framework after the partitions and nineteenth-century changes. See the chronology for the intermediate stages and western exceptions.','Прыналежнасць эпохі Рэчы Паспалітай замяняецца расійскай імперскай сістэмай пасля падзелаў і зменаў XIX стагоддзя. Прамежкавыя этапы і заходнія выключэнні глядзіце ў храналогіі.'];
  window.MAPA_MAPPED_YEARS=Object.freeze(eras.map(era=>era.year));
  const words={
    en:{eyebrow:'01 · Changing territories',title:'Move through time. Watch the borders change.',intro:'These are seven dated regional maps, not a modern outline with changing pins. Choose a year, drag the timeline, or play the sequence.',jumpEvents:'Explore places and documents ↓',snapshot:'dated snapshot',loading:'Loading source geometry…',play:'Play timeline',pause:'Pause',replay:'Replay timeline',previous:'Previous',next:'Next',slider:'Map year',modernOverlay:'Show present-day Belarus · dashed white',previousOverlay:'Compare previous territory · dashed coral',accuracy:'Approximate regional reconstructions, not survey boundaries. Only these seven years have map data; no intermediate borders are invented.',whatChanged:'What changes in this view',download:'Open this map’s GeoJSON',datasetSource:'Original geometry and revision ↗',methodLink:'Sources, accuracy and missing periods ↓',methodTitle:'How these historical maps were made — and what is missing',method1:'Geometry: André Ourednik and contributors’ Historical Basemaps, an openly licensed, work-in-progress dataset designed for continental and regional views. We clipped seven source files to this region; we did not draw new borders by eye. The original MAPA’s 63 drawings are not used.',method2:'The maps represent political regions, not the borders of a timeless Belarusian nation. The 1500 layer combines Poland and the Grand Duchy of Lithuania; the Soviet layers show the USSR’s external extent, not the Belarusian SSR’s internal boundary. Modern Belarus appears only as an optional, explicitly labeled reference.',method3:'Missing: the medieval principalities, the full sequence of partitions, BNR territorial claims, and internal BSSR boundary changes. Several candidate source years failed our basic place checks and were excluded. The remaining regional outlines still require specialist cartographic review; do not use them as legal or detailed academic boundary evidence.',rebuild:'Reproducible clipping script',review:'Review notes and provenance',originalBehavior:'How the original MAPA changed borders',license:'Modified geometry is distributed under GPL-3.0, with its editable GeoJSON, source revision and license. Data is provided without warranty. The separate present-day reference comes from Natural Earth, public domain.',eventEyebrow:'02 · Places and documents',eventHeading:'Follow the evidence behind an event.',backBorders:'Back to changing borders ↑',failed:'This historical layer could not load. Choose another year or reload the page; no substitute map is shown.',neighbor:'Other mapped territories',mapDescription:'Approximate political territories in the selected source snapshot. See the explanation and source alongside the map.',notBefore:'No earlier snapshot in this edition.',sourceName:'Source label'},
    be:{eyebrow:'01 · Змена тэрыторый',title:'Рухайцеся ў часе. Глядзіце, як мяняюцца межы.',intro:'Гэта сем рэгіянальных мапаў на канкрэтныя гады, а не сучасны контур з маркерамі. Абярыце год, перасуньце паўзунок або запусціце паслядоўнасць.',jumpEvents:'Да месцаў і дакументаў ↓',snapshot:'зрэз на абраны год',loading:'Загрузка геаметрыі крыніцы…',play:'Запусціць храналогію',pause:'Паўза',replay:'Паўтарыць храналогію',previous:'Назад',next:'Далей',slider:'Год мапы',modernOverlay:'Паказаць сучасную Беларусь · белы пункцір',previousOverlay:'Параўнаць з папярэднім контурам · каралавы пункцір',accuracy:'Прыблізныя рэгіянальныя рэканструкцыі, а не геадэзічныя межы. Геаметрыя ёсць толькі на гэтыя сем гадоў; прамежкавыя межы не выдумляюцца.',whatChanged:'Што змяняецца на гэтым зрэзе',download:'Адкрыць GeoJSON гэтай мапы',datasetSource:'Зыходная геаметрыя і версія ↗',methodLink:'Крыніцы, дакладнасць і адсутныя перыяды ↓',methodTitle:'Як зробленыя гэтыя гістарычныя мапы — і чаго пакуль няма',method1:'Геаметрыя: Historical Basemaps Андрэ Ўрэдніка і супольнасці — адкрыты набор даных для кантынентальных і рэгіянальных мапаў, які працягвае развівацца. Мы абрэзалі сем зыходных файлаў да гэтага рэгіёна, а не малявалі новыя межы на вока. 63 выявы арыгінальнай MAPA не выкарыстоўваюцца.',method2:'Мапы паказваюць палітычныя рэгіёны, а не межы вечнай беларускай нацыі. Пласт 1500 года аб’ядноўвае Польшчу і ВКЛ; савецкія пласты паказваюць знешні контур СССР, а не ўнутраную мяжу БССР. Сучасная Беларусь дадаецца толькі як асобна пазначаны неабавязковы арыенцір.',method3:'Пакуль адсутнічаюць: сярэднявечныя княствы, поўная паслядоўнасць падзелаў, тэрытарыяльныя прэтэнзіі БНР і ўнутраныя змены межаў БССР. Некалькі магчымых зрэзаў не прайшлі базавую праверку месцаў і былі выключаныя. Астатнія контуры ўсё яшчэ патрабуюць спецыялізаванай картаграфічнай праверкі; яны не з’яўляюцца юрыдычным або дэталёвым навуковым доказам межаў.',rebuild:'Скрыпт для паўторнага стварэння',review:'Праверка і паходжанне даных',originalBehavior:'Як арыгінальная MAPA змяняла межы',license:'Змененая геаметрыя распаўсюджваецца паводле GPL-3.0 разам з рэдагуемымі GeoJSON, версіяй крыніцы і ліцэнзіяй, без гарантый. Асобны сучасны контур узяты з Natural Earth — грамадскага набытку.',eventEyebrow:'02 · Месцы і дакументы',eventHeading:'Прасачыце сведчанні за падзеяй.',backBorders:'Назад да змены межаў ↑',failed:'Гэты гістарычны пласт не загрузіўся. Абярыце іншы год або абнавіце старонку; іншая мапа замест яго не падстаўляецца.',neighbor:'Іншыя тэрыторыі крыніцы',mapDescription:'Прыблізныя палітычныя тэрыторыі на абраны год паводле крыніцы. Тлумачэнне і крыніца — побач з мапай.',notBefore:'У гэтай версіі няма ранейшага зрэзу.',sourceName:'Назва ў крыніцы'}
  };
  Object.assign(words.en,{eyebrow:'01 · Belarusian lands through time',title:'Which states were these lands part of?',intro:'Keep the same Belarusian lands in view and follow their political affiliation. Different colors show simultaneous jurisdictions, not the full size of an empire. The default example is the interwar division in 1938.',focusMode:'Belarusian lands',regionMode:'Wider states',fixedScope:'White outline: present-day Belarus, held constant as a comparison window — not a historical state border or an ethnic homeland.',cityPrompt:'Check a city in this year',unresolved:'Unresolved source alignment',cityUnresolved:'The source geometry does not reliably classify this location.',comparison:'Compare previous division · dashed coral',previousOverlay:'Compare previous division · dashed coral',accuracy:'The dividing lines come from actual polygon intersections. Hatched edge areas remain unresolved where historical and modern datasets do not align; they are not assigned to invented countries.',download:'Open the Belarus-focused GeoJSON',mapDescription:'Political affiliation within the constant present-day Belarus reference. See the jurisdiction legend and historical explanation beside the map.',method1:'We intersected the historical state polygons with one fixed present-day Belarus outline using polygon-clipping. We did not redraw historical dividing lines. The resulting focused GeoJSON and reproducible script are public. The wider-state view is optional.',method2:'This is a history of political affiliation of lands within a modern comparison area, not a claim that today’s Belarus existed throughout history. The Grand Duchy of Lithuania, Commonwealth, imperial state, union and constituent republic are distinguished in the captions.',method3:'The original had 63 states; this edition still has seven mapped snapshots. The medieval period, exact partition stages, BNR claims and internal BSSR changes are not fully mapped. Small mismatches at the modern outline remain visibly unresolved, rather than turning into false historical enclaves. This is not a complete restoration or survey-quality boundary evidence.'});
  Object.assign(words.be,{eyebrow:'01 · Беларускія землі ў часе',title:'У склад якіх дзяржаў уваходзілі гэтыя землі?',intro:'Трымайце ў полі зроку тыя самыя беларускія землі і сачыце за іх палітычнай прыналежнасцю. Розныя колеры паказваюць адначасовыя прыналежнасці, а не памер цэлай імперыі. Пачатковы прыклад — міжваенны падзел 1938 года.',focusMode:'Беларускія землі',regionMode:'Дзяржавы рэгіёна',fixedScope:'Белы контур: сучасная Беларусь як сталае акно параўнання, а не мяжа гістарычнай дзяржавы або этнічнага арэала.',cityPrompt:'Праверце горад у гэтым годзе',unresolved:'Неўзгодненасць крыніц',cityUnresolved:'Геаметрыя крыніцы не дазваляе надзейна вызначыць прыналежнасць гэтага месца.',comparison:'Папярэдні падзел · каралавы пункцір',previousOverlay:'Папярэдні падзел · каралавы пункцір',accuracy:'Лініі падзелу атрыманыя перасячэннем сапраўдных палігонаў. Заштрыхаваныя краявыя ўчасткі застаюцца неўзгодненымі паміж гістарычным і сучасным наборамі; ім не прыпісваюцца выдуманыя дзяржавы.',download:'Адкрыць GeoJSON беларускіх зямель',mapDescription:'Палітычная прыналежнасць у сталым сучасным контуры Беларусі. Легенда і гістарычнае тлумачэнне — побач з мапай.',method1:'Мы перасеклі гістарычныя дзяржаўныя палігоны з адным сталым сучасным контурам Беларусі праз polygon-clipping. Новыя лініі гістарычнага падзелу не маляваліся. Выніковыя GeoJSON і скрыпт адкрытыя. Поўныя дзяржавы рэгіёна можна ўключыць асобна.',method2:'Гэта гісторыя палітычнай прыналежнасці зямель у сучасным акне параўнання, а не сцвярджэнне, што сённяшняя Беларусь існавала ва ўсе эпохі. У подпісах адрозніваюцца ВКЛ, Рэч Паспалітая, імперыя, саюз і саюзная рэспубліка.',method3:'У арыгінале было 63 станы; гэтая версія ўсё яшчэ мае сем геаметрычных зрэзаў. Сярэднявечча, дакладныя этапы падзелаў, прэтэнзіі БНР і ўнутраныя змены БССР не адлюстраваныя цалкам. Дробныя неўзгодненасці сучаснага контуру застаюцца бачнымі, а не ператвараюцца ў ілжывыя анклавы. Гэта не поўнае аднаўленне і не геадэзічнае сведчанне межаў.'});
  const labels={'Poland-Lithuania':['Grand Duchy of Lithuania','Вялікае Княства Літоўскае'],'Polish–Lithuanian Commonwealth':['GDL within the Commonwealth','ВКЛ у Рэчы Паспалітай'],'Russian Empire':['Russian Empire','Расійская імперыя'],USSR:['Soviet Union · Belarusian SSR context','Савецкі Саюз · кантэкст БССР'],Poland:['Polish Republic','Польская Рэспубліка'],Byelarus:['Republic of Belarus','Рэспубліка Беларусь']};
  focusNotes[1800].body=['Most lands in the modern Belarus reference were incorporated into the Russian Empire after the partitions. A small western area was held by Prussia until 1807. Its precise local boundary is not certified by this coarse source and remains unresolved on the map.','Большасць зямель сучаснага беларускага контуру пасля падзелаў увайшла ў Расійскую імперыю. Невялікая заходняя частка знаходзілася ў Прусіі да 1807 года. Гэтая грубая крыніца не пацвярджае дакладную мясцовую мяжу; яна застаецца неўзгодненай на мапе.'];
  Object.assign(words.en,{method3:'Six approximate mapped snapshots are available, alongside a separate political chronology. The original had 63 boundary states; this is not a complete restoration. The 1800 polygon was excluded because it misassigns the Prussian western exception. Medieval, partition, wartime and internal BSSR boundaries still need reliable geometry. Unaligned edges remain hatched.',snapshot:'source map year'});
  Object.assign(words.be,{method3:'Даступныя шэсць прыблізных геаметрычных зрэзаў і асобная палітычная храналогія. У арыгінале было 63 станы межаў; гэта не поўнае аднаўленне. Палігон 1800 года выключаны: ён памылкова адносіць прускі заходні ўчастак да Расіі. Сярэднявечныя, ваенныя, унутраныя межы БССР і этапы падзелаў яшчэ патрабуюць надзейнай геаметрыі. Неўзгодненыя краі заштрыхаваныя.',snapshot:'год мапы крыніцы'});
  const cities=[{id:'minsk',name:['Minsk / Mensk','Мінск / Менск'],point:[27.5615,53.9023]},{id:'brest',name:['Brest','Брэст'],point:[23.6877,52.0976]},{id:'hrodna',name:['Hrodna','Гродна'],point:[23.8258,53.6694]},{id:'baranavichy',name:['Baranavičy','Баранавічы'],point:[26.0139,53.1327]},{id:'viciebsk',name:['Viciebsk','Віцебск'],point:[30.2049,55.1904]},{id:'homiel',name:['Homiel','Гомель'],point:[30.9878,52.4345]}];
  const colors={'Poland-Lithuania':['#466732','#b8ff35'],'Polish–Lithuanian Commonwealth':['#286b63','#64d6bb'],'Russian Empire':['#695332','#e5bc74'],USSR:['#58416f','#c9a4f4'],Poland:['#315d87','#8bbff2'],Byelarus:['#4b662c','#b8ff35']};
  Object.assign(words.en,{method3:'Five approximate mapped snapshots are available, alongside a separate political chronology. This is not the original’s complete 63-state sequence. The 1500 source cannot resolve Homiel’s within-year transfer to Moscow; the 1800 source misassigns a Prussian western area. Both maps are excluded. Exact partition, wartime and internal BSSR boundaries still need reliable geometry. Unaligned edges remain hatched.'});
  Object.assign(words.be,{method3:'Даступныя пяць прыблізных геаметрычных зрэзаў і асобная палітычная храналогія. Гэта не ўсе 63 станы арыгінала. Крыніца 1500 года не вызначае пераходу Гомеля да Масквы ўнутры года; крыніца 1800 года памылкова адносіць прускі заходні ўчастак да Расіі. Абедзве мапы выключаныя. Дакладныя этапы падзелаў, ваенныя і ўнутраныя межы БССР яшчэ патрабуюць надзейнай геаметрыі. Неўзгодненыя краі заштрыхаваныя.'});
  words.en.cityPrompt='Check a present-day location in this year';words.be.cityPrompt='Праверце месца сучаснага горада ў гэтым годзе';
  words.en.eventEyebrow='03 · Places and documents';words.be.eventEyebrow='03 · Месцы і дакументы';
  let index=2,timer=null,renderToken=0,lang='en',mode='focus',cityId='minsk',currentFeatures=[];const cache=new Map();
  const local=value=>value[lang==='be'?1:0],t=key=>words[lang][key];
  const node=(tag,attrs={})=>{const el=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,value);return el};
  const projection=([lon,lat])=>[(lon-12)/28*960,(61-lat)/15*700];
  const path=geometry=>(geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates).map(poly=>poly.map(ring=>ring.map((point,i)=>(i?'L':'M')+projection(point).map(n=>n.toFixed(2)).join(',')).join('')+'Z').join('')).join('');
  async function load(year,kind='focus'){const key=`${kind}_${year}`;if(!cache.has(key))cache.set(key,fetch(new URL(`./history/${key}.geojson`,new URL('./history.js',location.href))).then(response=>{if(!response.ok)throw Error(response.status);return response.json()}).catch(error=>{cache.delete(key);throw error}));return cache.get(key)}
  const referencePromise=fetch('./history/belarus-reference.geojson').then(response=>{if(!response.ok)throw Error(response.status);return response.json()});
  function sync(){const url=new URL(location.href);url.searchParams.set('year',eras[index].year);url.searchParams.delete('stage');if(mode==='region')url.searchParams.set('mapScope','region');else url.searchParams.delete('mapScope');url.hash='borders';history.replaceState({},'',url)}
  function stop(){if(timer)clearInterval(timer);timer=null;$('history-play').setAttribute('aria-pressed','false');$('history-play').textContent=t(index===eras.length-1?'replay':'play')}
  function select(next,manual=true){if(manual)stop();index=Math.max(0,Math.min(eras.length-1,next));sync();render()}
  function textUI(){lang=document.documentElement.lang==='be'?'be':'en';document.querySelectorAll('[data-history]').forEach(el=>el.textContent=t(el.dataset.history));$('history-years').setAttribute('aria-label',t('slider'));$('history-play').textContent=t(timer?'pause':index===eras.length-1?'replay':'play');document.querySelectorAll('[data-history-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.historyMode===mode)))}
  function drawGroup(group,features,className){group.replaceChildren();for(const f of features){const shape=node('path',{d:path(f.geometry),class:className,'fill-rule':'evenodd'});group.append(shape)}}
  async function render(){
    const token=++renderToken,era=eras[index];textUI();$('history-era-year').textContent=`${era.year} · ${index+1} / ${eras.length}`;$('history-map-year').textContent=era.year;
    $('history-era-title').textContent=local(era.title);$('history-era-text').textContent=local(era.body);$('history-era-warning').textContent=local(era.warning);$('history-change').textContent=local(era.change);
    $('history-range').max=eras.length-1;$('history-range').value=index;$('history-range').setAttribute('aria-valuetext',String(era.year));$('history-prev').disabled=index===0;$('history-next').disabled=index===eras.length-1;
    $('history-show-prior').disabled=index===0;$('history-show-prior').title=index===0?t('notBefore'):'';
    document.querySelectorAll('[data-era]').forEach(button=>button.setAttribute('aria-pressed',String(+button.dataset.era===index)));
    $('history-data-link').href=`./history/focus_${era.year}.geojson`;$('history-source-link').href=`https://github.com/aourednik/historical-basemaps/blob/62d8f1a03a71f2d3ff17f2d166f7553f256bce68/geojson/world_${era.year}.geojson`;
    $('history-map-title').textContent=`${era.year} · ${local(era.title)}`;$('history-map-desc').textContent=t('mapDescription');
    $('history-load-status').hidden=false;$('history-load-status').textContent=t('loading');$('history-shapes').replaceChildren();$('history-surrounding').replaceChildren();$('history-prior').replaceChildren();$('history-labels').replaceChildren();$('history-legend').replaceChildren();currentFeatures=[];$('history-city-result').textContent=t('loading');
    try{
      const [data,reference]=await Promise.all([load(era.year),referencePromise]);if(token!==renderToken)return;
      const ref=reference.features[0].geometry;drawGroup($('history-reference-fill'),reference.features,'history-reference-ground');drawGroup($('history-reference'),reference.features,'history-fixed-outline');
      const points=ref.coordinates.flat(2).map(projection),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y;
      $('history-map').setAttribute('viewBox',mode==='region'?'0 0 960 700':`${x-w*.13} ${y-h*.17} ${w*1.26} ${h*1.34}`);
      $('history-map').classList.toggle('is-region',mode==='region');
      const features=data.features.filter(f=>era.match.includes(f.properties.NAME));currentFeatures=features;
      for(const feature of features){const name=feature.properties.NAME;const shape=node('path',{d:path(feature.geometry),'fill-rule':'evenodd',class:'history-focus','data-polity':name,fill:colors[name][0],stroke:colors[name][1]});const title=node('title');title.textContent=local(labels[name]);shape.append(title);$('history-shapes').append(shape)}
      for(const name of era.match){const item=document.createElement('p');item.className='history-legend-item';item.style.setProperty('--polity-fill',colors[name][0]);item.style.setProperty('--polity-stroke',colors[name][1]);item.textContent=local(labels[name]);$('history-legend').append(item)}
      const uncertainty=document.createElement('p');uncertainty.className='history-uncertainty-legend';uncertainty.textContent=t('unresolved');$('history-legend').append(uncertainty);
      $('history-surrounding').toggleAttribute('hidden',mode!=='region');
      if(mode==='region'){const surrounding=await load(era.year,'world');if(token!==renderToken)return;for(const feature of surrounding.features){const name=feature.properties.NAME,shape=node('path',{d:path(feature.geometry),'fill-rule':'evenodd',class:'history-context-country',fill:colors[name]?.[0]||'#162c23',stroke:'#61766a'});$('history-surrounding').append(shape)}}
      drawCities();$('history-load-status').hidden=true;await overlays(token);
    }catch{if(token!==renderToken)return;stop();$('history-load-status').textContent=t('failed');$('history-map-desc').textContent=t('failed')}
  }
  function inRing(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
  function affiliation(point){return currentFeatures.find(feature=>feature.geometry.coordinates.some(poly=>inRing(point,poly[0])&&!poly.slice(1).some(hole=>inRing(point,hole))))?.properties.NAME}
  function drawCities(){
    $('history-labels').replaceChildren();$('history-cities').replaceChildren();
    for(const city of cities){const active=city.id===cityId,[x,y]=projection(city.point);const mark=node('g',{class:active?'history-city-mark active':'history-city-mark'});mark.append(node('circle',{cx:x,cy:y,r:active?3:2}));const label=node('text',{x:x+5,y:y+2,class:'history-city-label'});label.textContent=local(city.name);mark.append(label);$('history-labels').append(mark);
      const button=document.createElement('button');button.type='button';button.dataset.city=city.id;button.textContent=local(city.name);button.setAttribute('aria-pressed',String(active));button.addEventListener('click',()=>{cityId=city.id;drawCities()});$('history-cities').append(button);
    }
    const city=cities.find(c=>c.id===cityId),owner=affiliation(city.point);$('history-city-result').textContent=`${eras[index].year} · ${local(city.name)} → ${owner?local(labels[owner]):t('cityUnresolved')}`;
  }
  async function overlays(token=renderToken){
    $('history-prior').toggleAttribute('hidden',!$('history-show-prior').checked||index===0);
    if($('history-show-prior').checked&&index>0){try{const previous=eras[index-1],data=await load(previous.year);if(token!==renderToken)return;drawGroup($('history-prior'),data.features.filter(f=>previous.match.includes(f.properties.NAME)),'history-prior-outline')}catch{$('history-show-prior').checked=false;$('history-prior').setAttribute('hidden','')}}
  }
  eras.forEach((era,i)=>{const button=document.createElement('button');button.type='button';button.dataset.era=i;button.textContent=era.year;button.setAttribute('aria-pressed',String(i===index));button.addEventListener('click',()=>select(i));$('history-years').append(button)});
  $('history-range').addEventListener('input',event=>select(+event.target.value));$('history-prev').addEventListener('click',()=>select(index-1));$('history-next').addEventListener('click',()=>select(index+1));
  $('history-play').addEventListener('click',()=>{if(timer){stop();return}if(index===eras.length-1)select(0,false);timer=setInterval(()=>{if(index===eras.length-1){stop();return}select(index+1,false);if(index===eras.length-1)stop()},3500);$('history-play').setAttribute('aria-pressed','true');$('history-play').textContent=t('pause')});
  $('history-show-prior').addEventListener('change',()=>overlays());
  document.querySelectorAll('[data-history-mode]').forEach(button=>button.addEventListener('click',()=>{stop();mode=button.dataset.historyMode;sync();render()}));
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
  new MutationObserver(()=>{stop();render()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  function readURL(){const params=new URLSearchParams(location.search),found=eras.findIndex(era=>era.year===+params.get('year'));index=found>=0?found:2;mode=params.get('mapScope')==='region'?'region':'focus'}
  window.addEventListener('mapa-select-year',event=>{const found=eras.findIndex(era=>era.year===+event.detail);if(found>=0){select(found);$('borders').scrollIntoView({behavior:'smooth'})}});
  window.addEventListener('mapa-canonical-map',()=>sync());
  window.addEventListener('mapa-pause-history',()=>stop());
  const contextButton=document.createElement('button');contextButton.type='button';contextButton.className='mapa-button quiet';contextButton.id='history-read-context';contextButton.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('mapa-read-context',{detail:eras[index].year})));$('history-data-link').before(contextButton);
  function contextLabel(){contextButton.textContent=document.documentElement.lang==='be'?'Гістарычны кантэкст і крыніцы →':'Historical context and sources →'}
  new MutationObserver(contextLabel).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});contextLabel();
  window.addEventListener('popstate',()=>{stop();readURL();render()});
  readURL();render();
  eras.forEach(era=>load(era.year).catch(()=>{}));
})();
