(() => {
  'use strict';
  const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
  const eras=[
    {year:1500,match:['Poland-Lithuania'],title:['Poland and the Grand Duchy of Lithuania','Польшча і Вялікае Княства Літоўскае'],body:['The source groups the two realms under their shared dynasty. Belarusian lands belonged to the Grand Duchy of Lithuania; this combined polygon is not a separate map of the duchy.','Крыніца аб’ядноўвае дзве дзяржавы пад агульнай дынастыяй. Беларускія землі ўваходзілі ў Вялікае Княства Літоўскае; гэты агульны палігон не з’яўляецца асобнай мапай княства.'],warning:['Before the 1569 Union of Lublin: do not read this combined outline as the later Commonwealth or as modern Belarus.','Да Люблінскай уніі 1569 года: не блытайце агульны контур з пазнейшай Рэччу Паспалітай або сучаснай Беларуссю.'],change:['Starting snapshot. The highlighted territory extends well beyond today’s Belarus. Turn on the dashed modern reference to compare.','Пачатковы зрэз. Вылучаная тэрыторыя значна шырэйшая за сучасную Беларусь. Уключыце пункцірны сучасны контур для параўнання.']},
    {year:1700,match:['Polish–Lithuanian Commonwealth'],title:['The Polish–Lithuanian Commonwealth','Рэч Паспалітая'],body:['The map now shows the Commonwealth’s regional outline. Compare its eastern edge with the earlier source snapshot; the highlighted polygon itself changes.','Мапа паказвае рэгіянальны контур Рэчы Паспалітай. Параўнайце ўсходнюю мяжу з папярэднім зрэзам: змяняецца сам вылучаны палігон.'],warning:['A regional snapshot, not a map of front lines during the Great Northern War.','Рэгіянальны зрэз, а не мапа франтоў падчас Паўночнай вайны.'],change:['The composite dynastic-region layer is replaced by the later Commonwealth geometry. The 1569 and seventeenth-century transitions between them are not animated as invented intermediate borders.','Пласт дынастычнага аб’яднання замяняецца пазнейшай геаметрыяй Рэчы Паспалітай. Пераходы 1569 года і XVII стагоддзя не падмяняюцца выдуманымі прамежкавымі межамі.']},
    {year:1800,match:['Russian Empire'],title:['After the partitions','Пасля падзелаў'],body:['Following the partitions of 1772, 1793 and 1795, the lands of present-day Belarus were within the Russian Empire. The visible extent is the empire clipped to this regional window.','Пасля падзелаў 1772, 1793 і 1795 гадоў землі сучаснай Беларусі ўваходзілі ў Расійскую імперыю. Бачная частка імперыі абмежаваная акном гэтай рэгіянальнай мапы.'],warning:['The full Russian Empire extends beyond the frame. Its shape must not be described as the territory of Belarus.','Расійская імперыя выходзіць за межы кадра. Яе контур нельга называць тэрыторыяй Беларусі.'],change:['The Commonwealth disappears from this source snapshot and the Russian imperial polygon replaces it across Belarusian lands.','Рэч Паспалітая знікае з гэтага зрэзу; на беларускіх землях яе замяняе палігон Расійскай імперыі.']},
    {year:1914,match:['Russian Empire'],title:['The region before the First World War','Рэгіён перад Першай сусветнай вайной'],body:['The imperial context remains, but the western territorial configuration differs from 1800. Use the previous-territory overlay to inspect that difference rather than relying on a change of name.','Імперскі кантэкст захоўваецца, але канфігурацыя заходніх тэрыторый адрозніваецца ад 1800 года. Уключыце папярэдні контур, каб пабачыць розніцу, а не толькі назву.'],warning:['A dated political map, not a day-by-day wartime occupation map.','Палітычная мапа на абраны год, а не штодзённая мапа ваеннай акупацыі.'],change:['The western extent changes, including the imperial boundary in the Polish lands. Belarusian lands remain inside the larger empire.','Змяняецца заходняя частка, у тым ліку імперская мяжа на польскіх землях. Беларускія землі застаюцца ўнутры большай імперыі.']},
    {year:1938,match:['USSR','Poland'],title:['Belarusian lands divided between states','Беларускія землі падзеленыя паміж дзяржавамі'],body:['The interwar map shows Poland to the west and the USSR to the east. Western Belarus was in Poland; the Belarusian SSR was part of the USSR.','Міжваенная мапа паказвае Польшчу на захадзе і СССР на ўсходзе. Заходняя Беларусь была ў складзе Польшчы, Беларуская ССР — у складзе СССР.'],warning:['Only the USSR’s external boundary is available in this layer. No internal Belarusian SSR border is drawn.','У гэтым пласце ёсць толькі знешняя мяжа СССР. Унутраная мяжа Беларускай ССР не намаляваная.'],change:['One imperial space is replaced by distinct interwar state polygons. Two colors make the division visible on the map.','Адну імперскую прастору замяняюць асобныя палігоны міжваенных дзяржаў. Два колеры паказваюць падзел на мапе.']},
    {year:1945,match:['USSR','Poland'],title:['The postwar territorial arrangement','Пасляваенны тэрытарыяльны падзел'],body:['The source’s 1945 snapshot shows the Soviet boundary farther west and Poland’s shifted outline. Compare it directly with 1938 to see the territorial change.','Зрэз крыніцы за 1945 год паказвае савецкую мяжу далей на захад і зменены контур Польшчы. Параўнайце з 1938 годам, каб пабачыць тэрытарыяльныя змены.'],warning:['A generalized postwar snapshot; not every 1945 treaty date or later local adjustment is represented. Internal SSR boundaries are absent.','Абагульнены пасляваенны зрэз: не ўсе даты дамоваў 1945 года і пазнейшыя мясцовыя карэкціроўкі адлюстраваныя. Унутраных межаў ССР няма.'],change:['The Poland–USSR boundary moves west relative to 1938. The map changes the actual state polygons; the optional coral contour preserves the previous view for comparison.','Мяжа Польшчы і СССР зрушваецца на захад адносна 1938 года. Мапа змяняе самі палігоны; каралавы контур захоўвае папярэдні выгляд для параўнання.']},
    {year:1994,match:['Byelarus'],title:['Belarus as an independent state','Беларусь як незалежная дзяржава'],body:['Belarus is now represented as its own state polygon, alongside Lithuania, Poland, Russia and Ukraine. This is the dataset’s 1994 map, not a claim that independence began in 1994.','Беларусь паказаная асобным дзяржаўным палігонам побач з Літвой, Польшчай, Расіяй і Украінай. Гэта мапа набору даных за 1994 год, а не сцвярджэнне, што незалежнасць пачалася ў 1994 годзе.'],warning:['Independence dates to 1991. The selected geometry is the available 1994 snapshot.','Незалежнасць адносіцца да 1991 года. Абраная геаметрыя — даступны зрэз за 1994 год.'],change:['The USSR polygon is replaced by the separate outlines of the successor states. Belarus’s own outline is highlighted.','Палігон СССР замяняецца асобнымі контурамі дзяржаў. Вылучаны ўласны контур Беларусі.']}
  ];
  const words={
    en:{eyebrow:'01 · Changing territories',title:'Move through time. Watch the borders change.',intro:'These are seven dated regional maps, not a modern outline with changing pins. Choose a year, drag the timeline, or play the sequence.',jumpEvents:'Explore places and documents ↓',snapshot:'dated snapshot',loading:'Loading source geometry…',play:'Play timeline',pause:'Pause',replay:'Replay timeline',previous:'Previous',next:'Next',slider:'Map year',modernOverlay:'Show present-day Belarus · dashed white',previousOverlay:'Compare previous territory · dashed coral',accuracy:'Approximate regional reconstructions, not survey boundaries. Only these seven years have map data; no intermediate borders are invented.',whatChanged:'What changes in this view',download:'Open this map’s GeoJSON',datasetSource:'Original geometry and revision ↗',methodLink:'Sources, accuracy and missing periods ↓',methodTitle:'How these historical maps were made — and what is missing',method1:'Geometry: André Ourednik and contributors’ Historical Basemaps, an openly licensed, work-in-progress dataset designed for continental and regional views. We clipped seven source files to this region; we did not draw new borders by eye. The original MAPA’s 63 drawings are not used.',method2:'The maps represent political regions, not the borders of a timeless Belarusian nation. The 1500 layer combines Poland and the Grand Duchy of Lithuania; the Soviet layers show the USSR’s external extent, not the Belarusian SSR’s internal boundary. Modern Belarus appears only as an optional, explicitly labeled reference.',method3:'Missing: the medieval principalities, the full sequence of partitions, BNR territorial claims, and internal BSSR boundary changes. Several candidate source years failed our basic place checks and were excluded. The remaining regional outlines still require specialist cartographic review; do not use them as legal or detailed academic boundary evidence.',rebuild:'Reproducible clipping script',review:'Review notes and provenance',originalBehavior:'How the original MAPA changed borders',license:'Modified geometry is distributed under GPL-3.0, with its editable GeoJSON, source revision and license. Data is provided without warranty. The separate present-day reference comes from Natural Earth, public domain.',eventEyebrow:'02 · Places and documents',eventHeading:'Follow the evidence behind an event.',backBorders:'Back to changing borders ↑',failed:'This historical layer could not load. Choose another year or reload the page; no substitute map is shown.',neighbor:'Other mapped territories',mapDescription:'Approximate political territories in the selected source snapshot. See the explanation and source alongside the map.',notBefore:'No earlier snapshot in this edition.',sourceName:'Source label'},
    be:{eyebrow:'01 · Змена тэрыторый',title:'Рухайцеся ў часе. Глядзіце, як мяняюцца межы.',intro:'Гэта сем рэгіянальных мапаў на канкрэтныя гады, а не сучасны контур з маркерамі. Абярыце год, перасуньце паўзунок або запусціце паслядоўнасць.',jumpEvents:'Да месцаў і дакументаў ↓',snapshot:'зрэз на абраны год',loading:'Загрузка геаметрыі крыніцы…',play:'Запусціць храналогію',pause:'Паўза',replay:'Паўтарыць храналогію',previous:'Назад',next:'Далей',slider:'Год мапы',modernOverlay:'Паказаць сучасную Беларусь · белы пункцір',previousOverlay:'Параўнаць з папярэднім контурам · каралавы пункцір',accuracy:'Прыблізныя рэгіянальныя рэканструкцыі, а не геадэзічныя межы. Геаметрыя ёсць толькі на гэтыя сем гадоў; прамежкавыя межы не выдумляюцца.',whatChanged:'Што змяняецца на гэтым зрэзе',download:'Адкрыць GeoJSON гэтай мапы',datasetSource:'Зыходная геаметрыя і версія ↗',methodLink:'Крыніцы, дакладнасць і адсутныя перыяды ↓',methodTitle:'Як зробленыя гэтыя гістарычныя мапы — і чаго пакуль няма',method1:'Геаметрыя: Historical Basemaps Андрэ Ўрэдніка і супольнасці — адкрыты набор даных для кантынентальных і рэгіянальных мапаў, які працягвае развівацца. Мы абрэзалі сем зыходных файлаў да гэтага рэгіёна, а не малявалі новыя межы на вока. 63 выявы арыгінальнай MAPA не выкарыстоўваюцца.',method2:'Мапы паказваюць палітычныя рэгіёны, а не межы вечнай беларускай нацыі. Пласт 1500 года аб’ядноўвае Польшчу і ВКЛ; савецкія пласты паказваюць знешні контур СССР, а не ўнутраную мяжу БССР. Сучасная Беларусь дадаецца толькі як асобна пазначаны неабавязковы арыенцір.',method3:'Пакуль адсутнічаюць: сярэднявечныя княствы, поўная паслядоўнасць падзелаў, тэрытарыяльныя прэтэнзіі БНР і ўнутраныя змены межаў БССР. Некалькі магчымых зрэзаў не прайшлі базавую праверку месцаў і былі выключаныя. Астатнія контуры ўсё яшчэ патрабуюць спецыялізаванай картаграфічнай праверкі; яны не з’яўляюцца юрыдычным або дэталёвым навуковым доказам межаў.',rebuild:'Скрыпт для паўторнага стварэння',review:'Праверка і паходжанне даных',originalBehavior:'Як арыгінальная MAPA змяняла межы',license:'Змененая геаметрыя распаўсюджваецца паводле GPL-3.0 разам з рэдагуемымі GeoJSON, версіяй крыніцы і ліцэнзіяй, без гарантый. Асобны сучасны контур узяты з Natural Earth — грамадскага набытку.',eventEyebrow:'02 · Месцы і дакументы',eventHeading:'Прасачыце сведчанні за падзеяй.',backBorders:'Назад да змены межаў ↑',failed:'Гэты гістарычны пласт не загрузіўся. Абярыце іншы год або абнавіце старонку; іншая мапа замест яго не падстаўляецца.',neighbor:'Іншыя тэрыторыі крыніцы',mapDescription:'Прыблізныя палітычныя тэрыторыі на абраны год паводле крыніцы. Тлумачэнне і крыніца — побач з мапай.',notBefore:'У гэтай версіі няма ранейшага зрэзу.',sourceName:'Назва ў крыніцы'}
  };
  const labels={'Poland-Lithuania':['Poland + Grand Duchy of Lithuania','Польшча + ВКЛ'],'Polish–Lithuanian Commonwealth':['Polish–Lithuanian Commonwealth','Рэч Паспалітая'],'Russian Empire':['Russian Empire','Расійская імперыя'],USSR:['USSR · external territory','СССР · знешняя тэрыторыя'],Poland:['Poland','Польшча'],Byelarus:['Belarus','Беларусь']};
  let index=0,timer=null,renderToken=0,lang='en';const cache=new Map();
  const local=value=>value[lang==='be'?1:0],t=key=>words[lang][key];
  const node=(tag,attrs={})=>{const el=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,value);return el};
  const projection=([lon,lat])=>[(lon-12)/28*960,(61-lat)/15*700];
  const path=geometry=>(geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates).map(poly=>poly.map(ring=>ring.map((point,i)=>(i?'L':'M')+projection(point).map(n=>n.toFixed(2)).join(',')).join('')+'Z').join('')).join('');
  async function load(year){if(!cache.has(year))cache.set(year,fetch(new URL(`./history/world_${year}.geojson`,document.currentScript?.src||new URL('./history.js',location.href))).then(response=>{if(!response.ok)throw Error(response.status);return response.json()}).catch(error=>{cache.delete(year);throw error}));return cache.get(year)}
  function sync(){const url=new URL(location.href);url.searchParams.set('year',eras[index].year);url.hash='borders';history.replaceState({},'',url)}
  function stop(){if(timer)clearInterval(timer);timer=null;$('history-play').setAttribute('aria-pressed','false');$('history-play').textContent=t(index===eras.length-1?'replay':'play')}
  function select(next,manual=true){if(manual)stop();index=Math.max(0,Math.min(eras.length-1,next));sync();render()}
  function textUI(){lang=document.documentElement.lang==='be'?'be':'en';document.querySelectorAll('[data-history]').forEach(el=>el.textContent=t(el.dataset.history));$('history-years').setAttribute('aria-label',t('slider'));$('history-play').textContent=t(timer?'pause':index===eras.length-1?'replay':'play')}
  function drawGroup(group,features,className){group.replaceChildren();for(const f of features){const shape=node('path',{d:path(f.geometry),class:className,'fill-rule':'evenodd'});group.append(shape)}}
  async function render(){
    const token=++renderToken,era=eras[index];textUI();$('history-era-year').textContent=`${era.year} · ${index+1} / ${eras.length}`;$('history-map-year').textContent=era.year;
    $('history-era-title').textContent=local(era.title);$('history-era-text').textContent=local(era.body);$('history-era-warning').textContent=local(era.warning);$('history-change').textContent=local(era.change);
    $('history-range').value=index;$('history-range').setAttribute('aria-valuetext',String(era.year));$('history-prev').disabled=index===0;$('history-next').disabled=index===eras.length-1;
    $('history-show-prior').disabled=index===0;$('history-show-prior').title=index===0?t('notBefore'):'';
    document.querySelectorAll('[data-era]').forEach(button=>button.setAttribute('aria-pressed',String(+button.dataset.era===index)));
    $('history-data-link').href=`./history/world_${era.year}.geojson`;$('history-source-link').href=`https://github.com/aourednik/historical-basemaps/blob/62d8f1a03a71f2d3ff17f2d166f7553f256bce68/geojson/world_${era.year}.geojson`;
    $('history-map-title').textContent=`${era.year} · ${local(era.title)}`;$('history-map-desc').textContent=t('mapDescription');
    $('history-load-status').hidden=false;$('history-load-status').textContent=t('loading');$('history-shapes').replaceChildren();$('history-prior').replaceChildren();$('history-labels').replaceChildren();$('history-legend').replaceChildren();
    try{
      const data=await load(era.year);if(token!==renderToken)return;
      const features=data.features.slice().sort((a,b)=>Number(era.match.includes(a.properties.NAME))-Number(era.match.includes(b.properties.NAME)));
      for(const feature of features){const ordinal=era.match.indexOf(feature.properties.NAME);const shape=node('path',{d:path(feature.geometry),'fill-rule':'evenodd',class:ordinal<0?'history-country':`history-country history-focus history-focus-${ordinal}`});const title=node('title');title.textContent=labels[feature.properties.NAME]?local(labels[feature.properties.NAME]):`${t('sourceName')}: ${feature.properties.NAME}`;shape.append(title);$('history-shapes').append(shape)}
      era.match.forEach((name,i)=>{const item=document.createElement('p');item.className=`history-legend-item history-legend-${i}`;item.textContent=local(labels[name]);$('history-legend').append(item)});
      const place=node('g');const [x,y]=projection([27.5615,53.9023]);place.append(node('circle',{cx:x,cy:y,r:4,fill:'#fff'}));const label=node('text',{x:x+10,y:y+5,class:'history-place-label'});label.textContent=lang==='be'?'Мінск / Менск':'Minsk / Mensk';place.append(label);$('history-labels').append(place);
      $('history-load-status').hidden=true;await overlays(token);
    }catch{if(token!==renderToken)return;stop();$('history-load-status').textContent=t('failed');$('history-map-desc').textContent=t('failed')}
  }
  async function overlays(token=renderToken){
    $('history-reference').toggleAttribute('hidden',!$('history-show-reference').checked);
    $('history-prior').toggleAttribute('hidden',!$('history-show-prior').checked||index===0);
    if($('history-show-prior').checked&&index>0){try{const previous=eras[index-1],data=await load(previous.year);if(token!==renderToken)return;drawGroup($('history-prior'),data.features.filter(f=>previous.match.includes(f.properties.NAME)),'history-prior-outline')}catch{$('history-show-prior').checked=false;$('history-prior').setAttribute('hidden','')}}
  }
  eras.forEach((era,i)=>{const button=document.createElement('button');button.type='button';button.dataset.era=i;button.textContent=era.year;button.setAttribute('aria-pressed',String(i===index));button.addEventListener('click',()=>select(i));$('history-years').append(button)});
  $('history-range').addEventListener('input',event=>select(+event.target.value));$('history-prev').addEventListener('click',()=>select(index-1));$('history-next').addEventListener('click',()=>select(index+1));
  $('history-play').addEventListener('click',()=>{if(timer){stop();return}if(index===eras.length-1)select(0,false);timer=setInterval(()=>{if(index===eras.length-1){stop();return}select(index+1,false);if(index===eras.length-1)stop()},3500);$('history-play').setAttribute('aria-pressed','true');$('history-play').textContent=t('pause')});
  $('history-show-reference').addEventListener('change',()=>overlays());$('history-show-prior').addEventListener('change',()=>overlays());
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
  new MutationObserver(()=>{stop();render()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  window.addEventListener('popstate',()=>{stop();index=Math.max(0,eras.findIndex(era=>era.year===+new URLSearchParams(location.search).get('year')));render()});
  index=Math.max(0,eras.findIndex(era=>era.year===+new URLSearchParams(location.search).get('year')));render();
  fetch('./history/belarus-reference.geojson').then(response=>{if(!response.ok)throw Error(response.status);return response.json()}).then(data=>drawGroup($('history-reference'),data.features,'history-modern-outline')).catch(()=>{$('history-show-reference').disabled=true;$('history-show-reference').checked=false});
  eras.forEach(era=>load(era.year).catch(()=>{}));
})();
