(() => {
  const copy = {
    en: {
      'review-label':'Unlisted review build','review-note':'available only by direct URL; excluded from navigation and search indexing','eyebrow':'INDEPENDENT RECONSTRUCTION STUDY · v0.1','title-em':'made findable again.','deck':'A rights-safe prototype for exploring how a lost historical interface might be researched and rebuilt without copying its protected code, illustrations, or full dataset.','boundary-title':'This is not the original MAPA.','boundary-text':'It is a newly designed demonstration using a small set of public historical facts. The original project remains fully credited, and no public mirror will be released without permission.','map-note':'DIRECT-LINK RESEARCH PREVIEW','timeline-label':'INTERACTION PROOF','timeline-title':'Choose a year. See the evidence layer change.','sample-note':'Demonstration record · not recovered original data','source-link':'Open public source ↗','method-label':'RECONSTRUCTION RULES','method-title':'Preserve the idea without impersonating the original.','method-one-title':'Document','method-one-text':'Record archived captures, creators, known functionality, dates, language editions, and remaining uncertainty.','method-two-title':'Rebuild independently','method-two-text':'Use new code, new interaction design, and independently verified public facts. Do not extract or republish protected assets.','method-three-title':'Ask before release','method-three-text':'Keep the demonstration unlisted while seeking permission and expert correction. Publish only a clearly attributed, agreed scope.','credits-label':'ORIGINAL PROJECT ATTRIBUTION','credits-text':'The original Interactive Map of Belarusian History was created by Alexey Cherenkevich (idea and design), Yauhen Shpileuski (front-end), Hanna Shyrayeva (texts and translations), Viktar Yakunin (management), and Pavel Kedzich (advice). This independent study is not affiliated with them. Documentation: <a href="https://blog.cherenkevich.com/blog/mapa-process/" target="_blank" rel="noopener noreferrer">process article</a>, <a href="https://blog.cherenkevich.com/blog/mapa-results/" target="_blank" rel="noopener noreferrer">results article</a>, and <a href="https://arquivo.pt/wayback/20190923020214/http://map.letapis.by/by/" target="_blank" rel="noopener noreferrer">public archived capture</a>.'
    },
    be: {
      'review-label':'Непублічны аглядны білд','review-note':'даступны толькі па прамой спасылцы; выключаны з навігацыі і пошукавай індэксацыі','eyebrow':'НЕЗАЛЕЖНАЯ РЭКАНСТРУКЦЫЯ · v0.1','title-em':'зноў даступная для пошуку.','deck':'Прататып для вывучэння таго, як можна даследаваць і аднавіць страчаны гістарычны інтэрфейс без капіявання абароненага кода, ілюстрацый або поўнага набору даных.','boundary-title':'Гэта не арыгінальная MAPA.','boundary-text':'Гэта новы дызайн-дэманстратар з невялікай колькасцю публічных гістарычных фактаў. Арыгінальны праект цалкам атрыбутаваны; публічнае люстэрка не будзе выпушчана без дазволу.','map-note':'ДАСЛЕДЧЫ PREVIEW ПА ПРАМОЙ СПАСЫЛЦЫ','timeline-label':'ПРАВЕРКА ЎЗАЕМАДЗЕЯННЯ','timeline-title':'Абярыце год — і паглядзіце, як змяняецца пласт сведчанняў.','sample-note':'Дэманстрацыйны запіс · не даныя арыгінала','source-link':'Адкрыць публічную крыніцу ↗','method-label':'ПРАВІЛЫ РЭКАНСТРУКЦЫІ','method-title':'Захаваць ідэю, не выдаючы сябе за арыгінал.','method-one-title':'Задакументаваць','method-one-text':'Зафіксаваць архіўныя копіі, аўтараў, вядомыя функцыі, даты, моўныя версіі і нявызначанасць.','method-two-title':'Аднавіць незалежна','method-two-text':'Выкарыстоўваць новы код, новы дызайн і незалежна правераныя публічныя факты. Не капіяваць абароненыя матэрыялы.','method-three-title':'Спытаць перад публікацыяй','method-three-text':'Пакінуць дэманстрацыю непублічнай, пакуль запытваюцца дазвол і экспертныя выпраўленні. Публікаваць толькі выразна атрыбутаваны і ўзгоднены аб’ём.','credits-label':'АТРЫБУЦЫЯ АРЫГІНАЛЬНАГА ПРАЕКТА','credits-text':'Арыгінальную Інтэрактыўную мапу беларускай гісторыі стварылі Аляксей Чаранкевіч (ідэя і дызайн), Яўген Шпілеўскі (front-end), Ганна Шыраева (тэксты і пераклады), Віктар Якунін (менеджмент) і Павел Кедзіч (кансультацыі). Гэтае незалежнае даследаванне не звязана з імі. Дакументацыя: <a href="https://blog.cherenkevich.com/blog/mapa-process/" target="_blank" rel="noopener noreferrer">артыкул пра працэс</a>, <a href="https://blog.cherenkevich.com/blog/mapa-results/" target="_blank" rel="noopener noreferrer">артыкул пра вынікі</a> і <a href="https://arquivo.pt/wayback/20190923020214/http://map.letapis.by/by/" target="_blank" rel="noopener noreferrer">публічная архіўная копія</a>.'
    }
  };
  const events = [
    {year:'1067',label:{en:'First mention of Minsk',be:'Першая згадка Менска'},title:{en:'Minsk enters the written record.',be:'Менск уваходзіць у пісьмовыя крыніцы.'},text:{en:'The year commonly associated with the first chronicle mention of Minsk and the Battle on the Nemiga River. This sample demonstrates how a date, place, annotation, and source could be layered without reusing the original MAPA dataset.',be:'Год, з якім звычайна звязваюць першую летапісную згадку Менска і бітву на Нямізе. Запіс паказвае, як можна злучыць дату, месца, анатацыю і крыніцу без паўторнага выкарыстання арыгінальнага набору MAPA.'},url:'https://www.britannica.com/place/Minsk'},
    {year:'1569',label:{en:'Union of Lublin',be:'Люблінская ўнія'},title:{en:'A new Commonwealth changes the political map.',be:'Новая Рэч Паспалітая змяняе палітычную мапу.'},text:{en:'The Union of Lublin created the Polish–Lithuanian Commonwealth. A full research build would distinguish political borders, legal structures, languages, and later interpretations rather than compressing them into one visual claim.',be:'Люблінская ўнія стварыла Рэч Паспалітую. Поўная даследчая версія павінна аддзяляць палітычныя межы, прававыя структуры, мовы і пазнейшыя інтэрпрэтацыі.'},url:'https://www.britannica.com/event/Union-of-Lublin'},
    {year:'1918',label:{en:'Belarusian Democratic Republic',be:'Беларуская Народная Рэспубліка'},title:{en:'The Third Constituent Charter declares independence.',be:'Трэцяя Ўстаўная грамата абвяшчае незалежнасць.'},text:{en:'This example shows why a historical interface needs visible source status: a primary document, the political circumstances of its adoption, and the later symbolic meaning are related but not interchangeable claims.',be:'Прыклад паказвае, чаму гістарычны інтэрфейс патрабуе бачнага статусу крыніц: першасны дакумент, палітычныя абставіны і пазнейшае сімвалічнае значэнне звязаныя, але не тоесныя.'},url:'https://www.radabnr.org/en/charters/'},
    {year:'1991',label:{en:'Restored independence',be:'Аднаўленне незалежнасці'},title:{en:'Belarus becomes an independent state.',be:'Беларусь становіцца незалежнай дзяржавай.'},text:{en:'The independence milestone demonstrates the proposed temporal interface at a familiar scale. Future layers could connect documents, borders, oral histories, cultural works, and competing interpretations while preserving provenance.',be:'Вяха незалежнасці паказвае прапанаваны часавы інтэрфейс на знаёмым прыкладзе. Будучыя пласты могуць злучыць дакументы, межы, вусныя гісторыі, культурныя творы і розныя інтэрпрэтацыі.'},url:'https://www.britannica.com/place/Belarus/Belarus-since-independence'}
  ];
  let lang='en'; let active=0;
  const years=document.querySelector('#years');
  const draw=()=>{years.replaceChildren(...events.map((event,index)=>{const button=document.createElement('button');button.type='button';button.setAttribute('aria-pressed',String(index===active));button.innerHTML=`<b>${event.year}</b><span>${event.label[lang]}</span>`;button.addEventListener('click',()=>{active=index;draw()});return button}));const event=events[active];document.querySelector('#event-year').textContent=event.year;document.querySelector('#event-title').textContent=event.title[lang];document.querySelector('#event-text').textContent=event.text[lang];document.querySelector('#event-source').href=event.url};
  const setLanguage=(next)=>{lang=next;document.documentElement.lang=next;document.querySelectorAll('[data-copy]').forEach(node=>{const value=copy[next][node.dataset.copy];if(value!==undefined)node.innerHTML=value});document.querySelectorAll('[data-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lang===next)));draw();const url=new URL(location.href);url.searchParams.set('lang',next);history.replaceState({},'',url)};
  document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));
  const initial=new URLSearchParams(location.search).get('lang');setLanguage(initial==='be'?'be':'en');
})();
