import {catalog,listeningPaths} from './catalog.js';
import {copy} from './i18n.js';
import {missionCopy} from './mission-copy.js';
import {experienceCopy,enhanceExperience} from './experience.js';
import {productCopy} from './product-copy.js';
import {dynamicProductCopy} from './release.js';
import {routeState,routeURL} from './routing.js';
import {pilotCopy,enhancePilot} from './pilot.js';
import {RELEASE} from './release.js';
import {countArtistIdentities} from './artist-identity.js';
import {renderArtwork,renderArtworkCredit,artworkControlHTML,mountArtworkControls} from './artwork.js';
import {deploymentCopy} from './deployment-copy.js';
import {taxonomyLabels} from './taxonomy-r3.js';
import {studyTaskLabels} from './study-copy-r3.js';
import {createResultPager,resultPageHTML,revealMoreResults} from './pagination.js';
import {readLibrary,saveLibrary} from './library.js';
import {decisions} from './roadmap.js';
import {readStudy,saveStudy,studyExport,taskIds} from './study.js';
for(const key of Object.keys(copy))Object.assign(copy[key],missionCopy[key],experienceCopy[key],productCopy[key],dynamicProductCopy(catalog,key),deploymentCopy(key),{private:pilotCopy[key].private,taskNote:pilotCopy[key].taskNote});
import {STORAGE_KEY,languages,escapeHTML as e,safeUrl,readState,saveState,search,cleanPersonal,selectionText,selectionHTML,metadataPassport,normalize,matchRecord} from './core.js';
let storage; try { storage=window.localStorage; } catch { storage={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}; }
let state=readState(storage,catalog.map(r=>r.id));
const library=readLibrary(storage,state);
const artworkController=mountArtworkControls({storage,onChange:(_enabled,{saved})=>{const scroll=window.scrollY;render();window.scrollTo({top:scroll,behavior:'instant'});if(!saved)toast(t.artworkSessionOnly);}});
const activeCollection=library.collections.find(c=>c.id===library.active);
if(activeCollection){state.title=activeCollection.title;state.ids=activeCollection.ids.filter(id=>catalog.some(r=>r.id===id)||state.personal.some(r=>r.id===id));}
state.storageOK=state.storageOK&&library.ok;
const app=document.querySelector('#app');
let lang='en',t=copy.en,view={},lastFocused;
const resultPager=createResultPager();let discoveryMatches=[];
let study=readStudy(storage);
const records=()=>[...catalog,...state.personal];
const byId=id=>records().find(r=>r.id===id);
const selected=()=>state.ids.map(byId).filter(Boolean);
const icon=(name)=>({arrow:'↗',save:'＋',saved:'✓',search:'⌕',close:'×',back:'←',next:'→',up:'↑',down:'↓'}[name]||'');
for(const key of Object.keys(copy)){copy[key].tasks=studyTaskLabels(key,copy[key].tasks);for(const [tag,labels] of Object.entries(taxonomyLabels))copy[key][tag]=labels[{en:0,be:1,ru:2}[key]];}
const APP_BASE=new URL('./',import.meta.url).pathname;
function readURL(){const {params:p,route}=routeState(location);lang=languages.includes(p.get('lang'))?p.get('lang'):'en';t=copy[lang];view={route,q:(p.get('q')||'').slice(0,180),scope:['listen','leads','personal'].includes(p.get('scope'))?p.get('scope'):'listen',path:p.get('path'),language:p.get('language')||(p.get('scope')==='personal'?'all':'be'),topic:p.get('topic')||'',genre:p.get('genre')||'',type:p.get('type')||'',decade:p.get('decade')||'',sort:p.get('sort')||''};}
function url(route,changes={}){return routeURL(location,route,changes,APP_BASE);}
history.replaceState({},'',url(routeState(location).route));
function go(route,changes={},focus=true,keepScroll=false){history.pushState({},'',url(route,changes));render();if(focus)document.querySelector('main h1,main h2')?.focus({preventScroll:true});if(!keepScroll)window.scrollTo({top:0,behavior:'instant'});}
const link=(url,label,className='')=>`<a class="${className}" href="${e(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${e(label)} <span aria-hidden="true">↗</span></a>`;
const button=(action,label,extra='',className='button')=>`<button type="button" class="${className}" data-action="${action}" ${extra}>${label}</button>`;
function persist(){
 // A recovery view is not authorization to replace unreadable stored data.
 // Keep both storage keys untouched; the existing warning remains visible.
 if(library.ok===false){state.storageOK=false;return false;}
 const libraryOK=saveLibrary(storage,library,state);
 if(!libraryOK){state.storageOK=false;return false;}
 state.storageOK=saveState(storage,state);return state.storageOK;
}
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),5000);}
const countArt=countArtistIdentities;
function researchLink(){return `<a class="research-return" href="https://research.sergey-ulyanov.pro/?lang=${lang==='be'?'be':'en'}" rel="noopener noreferrer" referrerpolicy="no-referrer">← ${e(t.researchReturn)}</a>`;}
function header(){return `<a class="skip" href="#main">${t.skip}</a><div class="private"><span class="status-dot"></span>${t.private}</div><header class="header"><div class="shell research-return-row">${researchLink()}</div><div class="shell header-inner"><a class="brand" data-route="discover" href="${url('discover')}"><span class="brand-icon" aria-hidden="true">u<span>↗</span></span><span>unmute<span class="brand-sub">music · memory · connection</span></span></a><nav aria-label="${t.mainNavigation}"><a data-route="discover" href="${url('discover')}" ${view.route==='discover'||view.route.startsWith('track/')?'aria-current="page"':''}>${t.navDiscover}</a><a data-route="collection" href="${url('collection')}" ${view.route==='collection'?'aria-current="page"':''}>${t.navCollection}<span class="nav-count">${state.ids.length}</span></a><a data-route="guide" href="${url('guide')}" ${view.route==='guide'?'aria-current="page"':''}>${t.navGuide}</a></nav><label class="language"><span class="sr-only">${t.language}</span><select id="language">${languages.map(l=>`<option value="${l}" ${lang===l?'selected':''}>${l.toUpperCase()}</option>`).join('')}</select></label></div></header>`;}
function art(r,small=false){const initials=r.artist==='Ana Zhdanova'?'z*':r.artist==='Šuma'?'š':r.artist==='Nürnberg'?'n':r.artist==='NAVIBAND'?'n↗':r.artist==='TROLLWALD'?'tw':r.artist.slice(0,2).toLowerCase();const fallbackHTML=`<div class="art art-${e(r.art||'personal')} ${small?'art-small':''}" aria-hidden="true"><div class="art-orbit"></div><div class="art-mark">${e(initials)}</div><div class="art-foot"><span>${e(r.artist)}</span><span>${r.year||'—'}</span></div></div>`;return renderArtwork(r,{fallbackHTML,lang,small,enabled:artworkController.enabled});}
function saveButton(r,wide=false){const saved=state.ids.includes(r.id);return button('save',`<span aria-hidden="true">${icon(saved?'saved':'save')}</span> ${saved?t.saved:t.save}`,`data-id="${e(r.id)}" aria-pressed="${saved}" aria-label="${e((saved?t.remove:t.save)+' · '+r.artist+' — '+r.title)}"`,wide?'button save wide '+(saved?'is-saved':''):'button save '+(saved?'is-saved':''));}
function card(r){const summary=r.summary?.[lang]||r.summary?.en||'';return `<article class="music-card"><a class="art-link" data-route="track/${e(r.id)}" href="${url('track/'+r.id)}" aria-label="${e(t.story+' · '+r.artist+' — '+r.title)}">${art(r)}</a><div class="card-body"><div class="meta"><span>${e(r.artist)}</span><span>${r.year||'—'}</span></div><h3><a data-route="track/${e(r.id)}" href="${url('track/'+r.id)}">${e(r.title)}</a></h3><div class="badges"><span>${e(t[r.language]||t.unknown)}</span>${r.kind==='remix'?`<span>${t.remix}</span>`:''}${r.personal?`<span>${t.personalBadge}</span>`:''}${!r.listenUrl?`<span class="caution">${t.lead}</span>`:''}</div><p class="card-summary">${e(summary)}</p><a class="story-link" data-route="track/${e(r.id)}" href="${url('track/'+r.id)}">${t.story} <span aria-hidden="true">→</span></a><div class="card-actions">${r.listenUrl?link(r.listenUrl,t.listen+' '+r.listenLabel,'button primary'):link(r.sourceUrl,t.source,'button secondary')}${saveButton(r)}</div></div></article>`;}
const select=(id,label,values,selectedValue)=>`<label class="filter"><span>${label}</span><select id="${id}" name="${id}">${values.map(([v,l])=>`<option value="${v}" ${selectedValue===v?'selected':''}>${e(l)}</option>`).join('')}</select></label>`;
function searchForm(){return `<form id="search-form" class="search-form"><label for="query">${t.searchLabel}</label><div class="search-bar"><span class="search-symbol" aria-hidden="true">⌕</span><input name="q" id="query" type="search" autocomplete="off" maxlength="180" value="${e(view.q)}" placeholder="${e(t.placeholder)}"><button class="button primary" type="submit">${t.search}<span aria-hidden="true">→</span></button></div><div class="examples"><span>${t.examplesLabel}</span>${t.examples.map(q=>button('example',e(q),`data-query="${e(q)}"`,'query-chip')).join('')}</div><p class="scope-note">${t.searchHelp}</p></form>`;}
function filters(){
 const values=(field,currentValue)=>{const tags=[...new Set(records().flatMap(r=>field==='topic'?[...(r.themes||[]),...(r.culturalFunctions||[])]:field==='genre'?r.tags||[]:[r.kind]).concat(currentValue||[]))];return [['',t.all],...tags.sort((a,b)=>(t[a]||a).localeCompare(t[b]||b,lang)).map(k=>[k,t[k]||k])];};
 return `<div class="filters">${select('filter-language',t.languageFilter,[['be',t.be],['all',t.all+' · review'],['mixed',t.mixed],['unknown',t.unknown],['instrumental',t.instrumental]],view.language)}${select('filter-topic',t.topicFilter,values('topic',view.topic),view.topic)}${select('filter-genre',t.genreFilter,values('genre',view.genre),view.genre)}${select('filter-type',t.typeFilter,values('type',view.type),view.type)}${select('filter-decade',t.decadeFilter,[['',t.all],['1990','1990–1999'],['2000','2000–2009'],['2010','2010–2019'],['2020','2020–2029']],view.decade)}${select('filter-sort',t.sort,[['',t.editorial],['newest',t.newest],['artist',t.artist]],view.sort)}</div>`;
}
function discover(){let base=records().filter(r=>view.scope==='personal'?r.personal:view.scope==='leads'?!r.personal&&!r.listenUrl:!r.personal&&r.listenUrl);
 const pathId=Number(view.path);if(view.path!==null&&listeningPaths[pathId])base=listeningPaths[pathId].ids.map(byId).filter(Boolean);
 const {intent,matches}=search(base,view.q,view);discoveryMatches=matches;const page=resultPager.snapshot(view,matches);const applied=[...(intent.topics||[]).map(g=>t[g]||g),...(intent.sound||[]).map(g=>t[g]||g),...intent.genres.map(g=>t[g]||g),intent.language?t[intent.language]:'',intent.years?.join('–')].filter(Boolean);const filtered=view.q||view.language||view.genre||view.type||view.decade||view.path!==null;
 return `<section class="hero shell"><div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><h1 tabindex="-1">${t.headline.split('\n').map((s,i)=>i?`<em>${s}</em>`:s).join('<br>')}</h1><p class="intro">${t.intro}</p></div><div class="hero-record" aria-hidden="true"><div class="record-disc"><div class="record-center">u↗</div></div><div class="record-sleeve"><span>U / 01</span><strong>слухай.<br>адчувай.<br>адкрывай.</strong><small>LISTEN & CONNECT</small></div></div>${searchForm()}</section>
 <section class="shell paths"><div class="section-label"><span>${t.collectionTitle}</span><span>01 — 03</span></div><div class="path-grid">${listeningPaths.map((p,i)=>button('path',`<span class="path-number">0${i+1}</span><span><strong>${t.paths[i]}</strong><small>${t.pathNotes[i]}</small></span><span aria-hidden="true">↗</span>`,`data-path="${i}" aria-pressed="${view.path===String(i)}"`,'path-card path-'+i)).join('')}</div></section>
 <section class="workspace shell" id="music"><div class="workspace-head"><div><p class="eyebrow">${t.catalog} · ${catalog.length} ${t.countNote}</p><h2 tabindex="-1">${view.path!==null&&t.paths[pathId]?t.paths[pathId]:t.browse}</h2></div>${filtered?button('reset',t.reset,'','button subtle'):''}</div><div class="scope-tabs" role="group" aria-label="${t.searchScope}">${['listen','leads','personal'].map(s=>{const n=records().filter(r=>s==='personal'?r.personal:s==='leads'?!r.personal&&!r.listenUrl:!r.personal&&r.listenUrl).length;return button('scope',`${t['scope'+s[0].toUpperCase()+s.slice(1)]} <span>${n}</span>`,`data-scope="${s}" aria-pressed="${view.scope===s&&view.path===null}"`,'scope-tab');}).join('')}</div><p class="scope-note">${view.scope==='leads'?t.leadsHelp:view.scope==='personal'?t.personalHelp:t.scopeHelp}</p>${view.language!=='be'&&view.scope!=='personal'?`<p class="query-readout">${t.reviewMode}</p>`:''}${filters()}
 ${view.q?`<div class="query-readout">${intent.unsupportedOperators.length?`<strong>${t.operatorWarning}</strong>`:''}${view.language&&view.language!=='all'&&intent.language&&view.language!==intent.language?`<strong>${t.conflictingLanguage}</strong>`:''}<span>${intent.mode==='exact-title'?t.exactTitle:applied.length?t.understood+' '+e(applied.join(' · ')):t.noIntent}</span>${intent.text.length?`<span>${t.unmatched} <strong>${e(intent.text.join(' · '))}</strong></span>`:''}</div>`:''}<div class="results-meta" role="status"><strong>${matches.length} ${t.results}</strong><span>${countArt(matches)} ${t.artists}</span>${view.scope==='personal'?button('add-link',t.addLink,'','text-button'):''}</div>
 ${matches.length?resultPageHTML(page,card,lang):`<div class="empty"><span class="empty-mark" aria-hidden="true">↗</span><h3>${t.empty}</h3><p>${t.emptyHelp}</p>${button('reset',t.reset,'','button primary')}${view.scope==='personal'?button('add-link',t.addLink,'','button secondary'):''}</div>`}${matches.length===0&&!intent.unsupportedOperators.length&&(intent.topics.includes('lullaby')||intent.sound.includes('soft')||view.topic==='lullaby')?relatedCandidates(base,intent):''}<p class="art-note">${t.artNote}</p></section>`;
}
function relatedCandidates(base,intent){if(intent.alternatives?.length||intent.excluded?.length||intent.diagnostics?.length||!['be','all'].includes(view.language)||(intent.language&&intent.language!=='be'))return '';const relaxed={...intent,topics:intent.topics.filter(x=>x!=='lullaby'),sound:intent.sound.filter(x=>x!=='soft')};const rs=base.filter(r=>r.language==='be'&&(r.themes?.includes('sleep')||/калыханка|lullaby/i.test(r.title))&&matchRecord(r,relaxed,{...view,topic:view.topic==='lullaby'?'':view.topic}));return rs.length?`<section class="related-candidates"><h3>${t.candidateTitle}</h3><p class="scope-note">${t.candidateNote}</p><div class="music-grid">${rs.map(card).join('')}</div></section>`:'';}
function collection(){const rs=selected();return `<section class="shell collection-page"><p class="eyebrow">${t.navCollection} · ${rs.length}</p><h1 tabindex="-1">${t.libraryHeading}</h1><p class="intro">${t.libraryIntro}</p><div class="collection-layout"><div class="collection-content">${rs.length?`<label class="collection-title-label" for="collection-title">${t.collectionName}</label><input id="collection-title" maxlength="120" placeholder="${e(t.collectionPlaceholder)}" value="${e(state.title)}"><ol class="collection-list">${rs.map((r,i)=>`<li>${art(r,true)}<div><span class="collection-artist">${e(r.artist)}</span><h2><a data-route="track/${e(r.id)}" href="${url('track/'+r.id)}">${e(r.title)}</a></h2><p>${e((r.summary?.[lang]||r.summary?.en||''))}</p>${r.listenUrl?link(r.listenUrl,t.listen+' '+r.listenLabel,'text-link'):link(r.sourceUrl,t.source,'text-link')}</div><div class="reorder">${button('up',icon('up'),`data-id="${e(r.id)}" ${i===0?'disabled':''} aria-label="${e(t.moveUp+' · '+r.title)}"`,'icon-button')}${button('down',icon('down'),`data-id="${e(r.id)}" ${i===rs.length-1?'disabled':''} aria-label="${e(t.moveDown+' · '+r.title)}"`,'icon-button')}${button('remove',icon('close'),`data-id="${e(r.id)}" aria-label="${e(t.remove+' · '+r.title)}"`,'icon-button')}</div></li>`).join('')}</ol>`:`<div class="empty"><span class="empty-mark" aria-hidden="true">＋</span><h2 tabindex="-1">${t.collectionEmpty}</h2><p>${t.collectionEmptyNote}</p><a class="button primary" data-route="discover" href="${url('discover')}">${t.goDiscover} →</a></div>`}</div><aside class="share-panel"><span class="eyebrow">${t.selection}</span><h2>${rs.length} <span>${t.results}</span></h2><p>${t.storageNote}</p>${button('copy',t.copy,rs.length?'':'disabled','button primary wide')}${button('download',t.download,rs.length?'':'disabled','button secondary wide')}${button('download-text',t.downloadText,rs.length?'':'disabled','button subtle wide')}<hr>${button('add-link',`＋ ${t.addLink}`,'','button secondary wide')}<div id="copy-fallback"></div></aside></div></section>`;}
function details(id){const r=byId(id);if(!r)return `<section class="shell empty"><h1 tabindex="-1">${t.empty}</h1><a data-route="discover" href="${url('discover')}" class="button primary">${t.goDiscover}</a></section>`;const siblings=r.workId?records().filter(s=>s.workId===r.workId&&s.id!==r.id):[];return `<section class="shell detail"><a class="breadcrumb" data-route="discover" href="${url('discover')}">← ${t.navDiscover}</a><div class="detail-layout"><div>${art(r)}${renderArtworkCredit(r,lang,{enabled:artworkController.enabled})}<p class="art-note">${t.artNote}</p></div><div><p class="eyebrow">${e(r.artist)} · ${r.year||t.noYear}</p><h1 tabindex="-1">${e(r.title)}</h1><div class="badges"><span>${t[r.language]||t.unknown}</span><span>${t[r.kind]||r.kind}</span>${r.tags.map(tag=>`<span>${e(t[tag]||tag)}</span>`).join('')}</div><p class="detail-summary">${e(r.summary[lang]||r.summary.en)}</p><p class="muted">${r.personal?t.personalBadge:t.summaryNote}</p><div class="detail-actions">${r.listenUrl?link(r.listenUrl,t.listen+' '+r.listenLabel,'button primary'):link(r.sourceUrl,t.source,'button primary')}${saveButton(r)}</div><p class="scope-note">${r.personal?t.personalBadge:r.listenUrl?t.checked:t.leadsHelp}</p>${r.linkNote?`<p class="notice">${t.linkCaution}</p>`:''}<div class="evidence"><h2>${r.personal?t.personalBadge:t.sourceFacts}</h2><dl><div><dt>${t.languageFilter}</dt><dd>${t[r.language]||t.unknown}</dd></div><div><dt>${t.typeFilter}</dt><dd>${t[r.kind]||r.kind}</dd></div><div><dt>${t.decadeFilter}</dt><dd>${r.year||t.noYear}</dd></div></dl>${r.languageEvidence?`<details class="classification"><summary>${t.whyLabel}</summary><p><strong>${t.languageFilter}.</strong> ${e(r.languageEvidence[lang]||r.languageEvidence.en)}</p>${r.tagScope?`<p><strong>${t.genreEvidence}.</strong> ${e(r.tagScope[lang]||r.tagScope.en)}</p>`:''}</details>`:''}${r.sourceUrl?link(r.sourceUrl,r.sourceName,'text-link'):''}<p>${t.rights}</p>${button('passport',t.passport,`data-id="${e(r.id)}"`,'button secondary')}<p>${t.passportNote}</p>${r.claims?.length?`<details class="classification"><summary>${t.claims}</summary><p>${t.claimNote}</p>${r.claims.map(c=>`<p><strong>${e(c.value)}</strong> · ${e(c.method)}<br>${e(c.basis)}${c.scope?' · '+e(c.scope):''}</p>`).join('')}</details>`:''}${r.unknowns?.length?`<details class="classification"><summary>${t.unknowns}</summary>${r.unknowns.map(s=>`<p>${e(s)}</p>`).join('')}</details>`:''}</div>${siblings.length?`<div class="versions"><h2>${t.paths[1]}</h2>${siblings.map(s=>`<a data-route="track/${s.id}" href="${url('track/'+s.id)}">${e(s.title)} →</a>`).join('')}</div>`:''}</div></div></section>`;}
function guide(){return `<section class="shell guide"><p class="eyebrow">${t.navGuide}</p><h1 tabindex="-1">${t.guideTitle.replace('\n','<br>')}</h1><p class="intro">${t.guideIntro}</p><div class="detail-actions"><a data-route="study" href="${url('study')}" class="button primary">${t.studyNav} →</a><a data-route="roadmap" href="${url('roadmap')}" class="button secondary">${t.roadmapNav}</a></div><div class="steps">${t.steps.map(([title,desc],i)=>`<article><span>0${i+1}</span><h2>${title}</h2><p>${desc}</p></article>`).join('')}</div><div class="guide-two"><section><h2>${t.boundaries}</h2><ul>${t.bounds.map(s=>`<li>${s}</li>`).join('')}</ul></section><section class="try-panel"><p class="eyebrow">03:00</p><h2>${t.tryTitle}</h2><p>${t.tryText}</p><a class="button primary" href="${url('discover')}" data-route="discover">${t.goDiscover} →</a><p class="muted">${t.feedback}</p></section></div><section class="advanced"><h2>${t.advanced}</h2><p>${t.advancedText}</p>${link('https://research.sergey-ulyanov.pro/tools/unmute-the-archive/',t.advancedLink,'text-link')}</section></section>`;}

function roadmap(){return `<section class="shell guide"><p class="eyebrow">${t.roadmapNav}</p><h1 tabindex="-1">${t.roadmapTitle}</h1><p class="intro">${t.roadmapIntro}</p><div class="steps roadmap-steps">${decisions.directions.map((d,i)=>`<article><span>${String(d.id).padStart(2,'0')}</span><h2>${t.directions[i]}</h2><p class="eyebrow">${d.phase.includes('now')?t.phaseNow:d.phase==='next'?t.phaseNext:d.phase==='later'?t.phaseLater:t.phaseLab}</p><p>${t.directionNotes[i]}</p></article>`).join('')}</div><section class="advanced"><h2>${t.corpusHeading}</h2><p>${t.corpusText}</p><p>${t.roadmapBoundary}</p>${button('roadmap-export',t.downloadRoadmap,'','button secondary')} <a data-route="study" href="${url('study')}" class="button primary">${t.studyNav} →</a></section></section>`;}
function studyPage(){const p=routeState(location).params,requested=String(p.get('participant')||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40),s=study&&(!requested||requested===study.code)?study:{},code=requested||s.code||'';return `<section class="shell collection-page"><p class="eyebrow">${t.studyNav}</p><h1 tabindex="-1">${t.studyTitle}</h1><p class="intro">${t.studyIntro}</p><div class="collection-layout study-layout"><section><div class="query-readout">${t.studyPrivacy}</div><p class="intro">${t.taskNote}</p><p class="scope-note">${t.localOnly}</p><div class="detail-actions"><a class="button primary" data-route="discover" href="${url('discover')}">${t.startTest} →</a><a class="button secondary" data-route="roadmap" href="${url('roadmap')}">${t.roadmapNav}</a></div></section><form id="study-form" class="add-dialog study-form"><h2>${t.studyWelcome}${s.nickname?' · '+e(s.nickname):''}</h2><label>${t.code}<input name="code" required pattern="[A-Za-z0-9_-]+" maxlength="40" value="${e(code)}" placeholder="P01"></label><label>${t.nickname}<input name="nickname" maxlength="60" value="${e(s.nickname||'')}"></label>${select('role',t.role,['listener','musician','researcher','learner','other'].map(k=>[k,t[k]]),s.role||'listener')}${select('comfort',t.comfort,['fluent','some','learning','none'].map(k=>[k,t[k]]),s.comfort||'some')}${select('task',t.task,taskIds.map((k,i)=>[k,t.tasks[i]]),s.task||'own-need')}<p id="study-task" class="scope-note">${t.tasks[Math.max(0,taskIds.indexOf(s.task||'own-need'))]}</p><label>${t.yourQuery}<input name="query" maxlength="180" value="${e(s.query||'')}"></label>${select('outcome',t.outcome,[['not-tried',t.notTried],['done',t.done],['partly',t.partly],['not-done',t.notDone]],s.outcome||'not-tried')}${select('ease',t.ease,[['',t.noRating],...['1','2','3','4','5'].map(n=>[n,n==='1'?n+' · '+t.easeLow:n==='5'?n+' · '+t.easeHigh:n])],s.ease?String(s.ease):'')}<label>${t.comment}<textarea name="comment" maxlength="1200" rows="5">${e(s.comment||'')}</textarea></label><label class="study-consent"><input type="checkbox" name="consent" required ><span>${t.consent}</span></label><p class="scope-note">${t.feedbackDraft}</p><p id="study-status" role="status"></p><button class="button primary wide" type="submit">${t.saveFeedback}</button>${button('study-export',t.exportFeedback,s.code?'':'disabled','button secondary wide')}</form></div></section>`;}

function render(){readURL();document.documentElement.lang=lang;document.title=`Unmute · ${view.route==='collection'?t.navCollection:view.route==='guide'?t.navGuide:t.navDiscover} — listening pilot`;app.innerHTML=header()+(!state.storageOK?`<div class="storage-warning" role="alert">${t.storageWarning}</div>`:'')+`<main id="main">${view.route==='study'?studyPage():view.route==='roadmap'?roadmap():view.route==='collection'?collection():view.route==='guide'?guide():view.route.startsWith('track/')?details(view.route.slice(6)):discover()}</main><footer class="shell footer"><span>${t.footer}</span><div class="footer-links">${researchLink()}<a data-route="study" href="${url('study')}">${t.studyNav} ↗</a><a data-route="roadmap" href="${url('roadmap')}">${t.roadmapNav} ↗</a><a data-route="guide" href="${url('guide')}">${t.navGuide} ↗</a></div></footer>`;}
function download(content,name,type){const blob=new Blob([content],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function openAdd(){lastFocused=document.activeElement;const dialog=document.createElement('dialog');dialog.className='add-dialog';dialog.innerHTML=`<button class="icon-button dialog-close" data-action="close-dialog" aria-label="${t.close}">×</button><h2 id="add-heading">${t.addTitle}</h2><p>${t.addIntro}</p><form id="add-form"><label>${t.titleLabel}<input name="title" required maxlength="160"></label><label>${t.artistLabel}<input name="artist" required maxlength="160"></label><label>${t.urlLabel}<input name="listenUrl" type="url" placeholder="https://…" required maxlength="2048"></label><label>${t.languageFilter}<select name="language">${['unknown','be','ru','en','instrumental'].map(l=>`<option value="${l}">${t[l]}</option>`).join('')}</select></label><p id="add-error" role="alert"></p><button class="button primary wide" type="submit">${t.submitLink} →</button></form>`;dialog.setAttribute('aria-labelledby','add-heading');document.body.append(dialog);dialog.addEventListener('close',()=>{dialog.remove();lastFocused?.focus();});dialog.showModal();}
document.addEventListener('click',async event=>{if(event.target.closest('.skip')){event.preventDefault();const main=document.querySelector('main');main.tabIndex=-1;main.focus();return;}const anchor=event.target.closest('[data-route]');if(anchor&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();go(anchor.dataset.route,anchor.hasAttribute('data-own-search')?{q:'',path:'',scope:'listen',language:'be',genre:'',topic:'',type:'',decade:'',sort:''}:{});return;}const b=event.target.closest('[data-action]');if(!b)return;const id=b.dataset.id,action=b.dataset.action;
 if(action==='load-more'){revealMoreResults({pager:resultPager,view,matches:discoveryMatches,render,document,window,lang,announce:toast});return;}
 if(action==='save'||action==='remove'){const wasSaved=state.ids.includes(id),previousIndex=state.ids.indexOf(id);if(!wasSaved&&state.ids.length>=100){toast(t.maxLinks);return;}if(wasSaved)state.ids=state.ids.filter(s=>s!==id);else if(byId(id))state.ids.push(id);persist();render();const focus=document.querySelector(`[data-action="save"][data-id="${CSS.escape(id)}"]`)||document.querySelectorAll('.collection-list [data-action="remove"]')[Math.min(previousIndex,state.ids.length-1)]||document.querySelector('main h1');focus?.focus({preventScroll:true});toast(state.storageOK?(wasSaved?t.removedToast:t.savedToast):t.storageWarning);}
 if(action==='passport'){const r=byId(id);if(r)download(JSON.stringify(metadataPassport(r,records()),null,2),'unmute-'+r.id+'-passport.json','application/json');}
 if(action==='roadmap-export')download(JSON.stringify(decisions,null,2),'unmute-product-decisions.json','application/json');
 if(action==='study-export'&&study)download(studyExport(study),'unmute-feedback-'+study.code+'.json','application/json');
 if(action==='reset')go('discover',{q:'',path:'',language:'',topic:'',genre:'',type:'',decade:'',sort:''},false);
 if(action==='example')go('discover',{q:b.dataset.query,scope:'listen',path:'',language:'',topic:'',genre:'',type:'',decade:''},false);
 if(action==='scope')go('discover',{scope:b.dataset.scope,path:'',language:b.dataset.scope==='personal'?'all':'be'},false);
 if(action==='path'){go('discover',{scope:'listen',path:b.dataset.path,q:'',language:'',topic:'',genre:'',type:'',decade:''},false);document.querySelector('#music').scrollIntoView({behavior:'smooth'});}
 if(action==='up'||action==='down'){const i=state.ids.indexOf(id),j=i+(action==='up'?-1:1);if(i>=0&&j>=0&&j<state.ids.length){[state.ids[i],state.ids[j]]=[state.ids[j],state.ids[i]];persist();render();(document.querySelector(`[data-action="${action}"][data-id="${CSS.escape(id)}"]:not(:disabled)`)||document.querySelector(`[data-action="remove"][data-id="${CSS.escape(id)}"]`))?.focus({preventScroll:true});}}
 if(action==='add-link')openAdd();if(action==='close-dialog')b.closest('dialog').close();
 if(action==='copy'){const text=selectionText(state.title,selected(),lang);try{await navigator.clipboard.writeText(text);toast(t.copyOK);}catch{const area=document.querySelector('#copy-fallback');area.innerHTML=`<label for="copy-text">${t.copyFailed}</label><textarea id="copy-text" readonly rows="8">${e(text)}</textarea>`;area.querySelector('textarea').focus();area.querySelector('textarea').select();}}
 if(action==='download')download(selectionHTML(state.title,selected(),lang),'unmute-selection.html','text/html;charset=utf-8');
 if(action==='download-text')download(selectionText(state.title,selected(),lang),'unmute-selection.txt','text/plain;charset=utf-8');
});
document.addEventListener('change',event=>{if(event.target.id==='task'){document.querySelector('#study-task').textContent=t.tasks[taskIds.indexOf(event.target.value)]||'';return;}if(event.target.id==='language'){go(view.route,{lang:event.target.value},false,true);document.querySelector('#language')?.focus({preventScroll:true});return;}if(event.target.id.startsWith('filter-')){const focusId=event.target.id;go('discover',{q:document.querySelector('#query').value,language:document.querySelector('#filter-language').value,topic:document.querySelector('#filter-topic').value,genre:document.querySelector('#filter-genre').value,type:document.querySelector('#filter-type').value,decade:document.querySelector('#filter-decade').value,sort:document.querySelector('#filter-sort').value},false,true);document.querySelector('#'+focusId)?.focus({preventScroll:true});}});
document.addEventListener('input',event=>{if(event.target.id==='collection-title'){state.title=event.target.value.slice(0,120);persist();if(!state.storageOK)toast(t.storageWarning);}});
document.addEventListener('submit',event=>{if(event.target.id==='study-form'){event.preventDefault();const result=saveStudy(storage,Object.fromEntries(new FormData(event.target)));study=result.value||study;document.querySelector('#study-status').textContent=result.ok?t.savedFeedback:t.studyError;if(study)document.querySelector('[data-action="study-export"]').disabled=false;return;}if(event.target.id==='search-form'){event.preventDefault();go('discover',{q:new FormData(event.target).get('q'),path:''},false);document.querySelector('#music')?.scrollIntoView({behavior:'smooth'});}if(event.target.id==='add-form'){event.preventDefault();if(state.personal.length>=100||state.ids.length>=100){document.querySelector('#add-error').textContent=t.maxLinks;return;}const r=cleanPersonal(Object.fromEntries(new FormData(event.target)));if(!r){document.querySelector('#add-error').textContent=t.invalidLink;return;}const existing=records().find(s=>s.listenUrl===r.listenUrl);if(existing){if(!state.ids.includes(existing.id))state.ids.push(existing.id);}else{state.personal.push(r);state.ids.push(r.id);}persist();event.target.closest('dialog').close();go('collection');toast(state.storageOK?t.savedToast:t.storageWarning);}});
window.addEventListener('popstate',()=>render());window.addEventListener('hashchange',()=>render());
const renderBase=render;
render=function(){renderBase();enhanceExperience({state,library,storage,catalog,records:records(),lang,t,view,go,render,persist,toast,download,selected:selected(),byId,card,pagination:{incremental:true},prototypeVersion:RELEASE});enhancePilot({lang,t,view,catalog,url});if(view.route==='discover'||view.route==='collection'||view.route.startsWith('track/')){const slot=document.querySelector('.workspace-head,.collection-page>.intro,.detail>.breadcrumb');slot?.insertAdjacentHTML('afterend',artworkControlHTML(lang,{enabled:artworkController.enabled}));}if(view.route==='guide'||view.route==='privacy'){document.querySelector('main>.shell')?.insertAdjacentHTML('beforeend',`<section class="artwork-guide"><h2>${e(t.artworkHeading)}</h2><p>${e(t.artworkGuide)}</p></section>`);}};
render();
