// Exact public release/recording artwork metadata, checked 12 September 2026.
// No image bytes, lyrics, or audio are stored here. Imported/personal records are excluded.
// Album covers remain album covers, including multi-performer compilations.
// Metadata availability is not a claim of ownership or independent rights clearance.
// Bandcamp: public og:image + JSON-LD recording membership (URL and track_id).
// Apple: square public twitter:image; not the 1200x630 social-card og:image.
export const artworkReleases = [
  {
    sourceUrl: "https://3miii.bandcamp.com/album/nekrut",
    url: "https://f4.bcbits.com/img/a4172465104_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "NEKRUT",
    publisher: "3MI",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3008879629","listenUrl":"https://3miii.bandcamp.com/track/chubaryki-forelocks","artist":"3MI"},
      {"id":"bc-3602998129","listenUrl":"https://3miii.bandcamp.com/track/saddling-the-horse","artist":"3MI"},
      {"id":"bc-578429968","listenUrl":"https://3miii.bandcamp.com/track/the-oak-on-the-hill","artist":"3MI"},
      {"id":"bc-4026610619","listenUrl":"https://3miii.bandcamp.com/track/rain-calling-song","artist":"3MI"},
      {"id":"bc-1460555545","listenUrl":"https://3miii.bandcamp.com/track/village-fair","artist":"3MI"},
      {"id":"bc-3108374745","listenUrl":"https://3miii.bandcamp.com/track/harvest","artist":"3MI"},
      {"id":"bc-2144813428","listenUrl":"https://3miii.bandcamp.com/track/a-lost-friend","artist":"3MI"},
      {"id":"bc-1489520720","listenUrl":"https://3miii.bandcamp.com/track/the-recruit-s-song-remix","artist":"3MI"},
      {"id":"bc-2604036953","listenUrl":"https://3miii.bandcamp.com/track/three-horses","artist":"3MI"},
      {"id":"bc-329876719","listenUrl":"https://3miii.bandcamp.com/track/dziady-ancestors","artist":"3MI"},
      {"id":"bc-1813380656","listenUrl":"https://3miii.bandcamp.com/track/a-green-oak-a-cappella","artist":"3MI"},
      {"id":"bc-1210794942","listenUrl":"https://3miii.bandcamp.com/track/oh-the-geese-flew-a-cappella","artist":"3MI"},
      {"id":"bc-255057540","listenUrl":"https://3miii.bandcamp.com/track/the-recruit-s-song-a-cappella","artist":"3MI"},
    ],
  },
  {
    sourceUrl: "https://adarvirog.bandcamp.com/album/kraj-padannia",
    url: "https://f4.bcbits.com/img/a2758108415_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Kraj Padanniaŭ",
    publisher: "Adarvirog",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-4131660173","listenUrl":"https://adarvirog.bandcamp.com/track/adarvirog","artist":"Adarvirog"},
      {"id":"bc-4268604465","listenUrl":"https://adarvirog.bandcamp.com/track/pieravaracie-werewolf","artist":"Adarvirog"},
      {"id":"bc-3456167371","listenUrl":"https://adarvirog.bandcamp.com/track/balada-pra-pa-stanca-va-kalaku-ballad-of-rebel-vaukalaka","artist":"Adarvirog"},
      {"id":"bc-355627873","listenUrl":"https://adarvirog.bandcamp.com/track/zabi-vyratava-nika-kill-the-savior","artist":"Adarvirog"},
      {"id":"bc-2320484358","listenUrl":"https://adarvirog.bandcamp.com/track/piesnia-bielaruskich-a-niera-song-of-belarusian-soldiers","artist":"Adarvirog"},
      {"id":"bc-807165950","listenUrl":"https://adarvirog.bandcamp.com/track/skro-piekla-through-hell","artist":"Adarvirog"},
      {"id":"bc-2678317615","listenUrl":"https://adarvirog.bandcamp.com/track/liso-yki","artist":"Adarvirog"},
      {"id":"bc-2736209685","listenUrl":"https://adarvirog.bandcamp.com/track/chareja-chorea","artist":"Adarvirog"},
      {"id":"bc-2812428491","listenUrl":"https://adarvirog.bandcamp.com/track/adarvirog-ii-from-hell-with-love","artist":"Adarvirog"},
      {"id":"bc-2694064202","listenUrl":"https://adarvirog.bandcamp.com/track/1863","artist":"Adarvirog"},
    ],
  },
  {
    sourceUrl: "https://adarvirog.bandcamp.com/album/ornaje-sonca",
    url: "https://f4.bcbits.com/img/a3010666852_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Čornaje Sonca",
    publisher: "Adarvirog",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3777375850","listenUrl":"https://adarvirog.bandcamp.com/track/ach","artist":"Adarvirog"},
      {"id":"bc-3344737348","listenUrl":"https://adarvirog.bandcamp.com/track/abadonna","artist":"Adarvirog"},
      {"id":"bc-323744568","listenUrl":"https://adarvirog.bandcamp.com/track/jurate","artist":"Adarvirog"},
      {"id":"bc-2453755603","listenUrl":"https://adarvirog.bandcamp.com/track/pieramie-a","artist":"Adarvirog"},
      {"id":"bc-3536839156","listenUrl":"https://adarvirog.bandcamp.com/track/kali-zdradzi-sviet","artist":"Adarvirog"},
      {"id":"bc-2829714022","listenUrl":"https://adarvirog.bandcamp.com/track/karol","artist":"Adarvirog"},
      {"id":"bc-3375971421","listenUrl":"https://adarvirog.bandcamp.com/track/ciomnyja-vody","artist":"Adarvirog"},
      {"id":"bc-3123717916","listenUrl":"https://adarvirog.bandcamp.com/track/abud-e-nie","artist":"Adarvirog"},
      {"id":"bc-1517273481","listenUrl":"https://adarvirog.bandcamp.com/track/pra-tych-chto-nie-viartajecca","artist":"Adarvirog"},
      {"id":"bc-435608018","listenUrl":"https://adarvirog.bandcamp.com/track/nia-varty","artist":"Adarvirog"},
    ],
  },
  {
    sourceUrl: "https://amaroka.bandcamp.com/album/pastka",
    url: "https://f4.bcbits.com/img/a4287705086_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "PASTKA",
    publisher: "AMAROKA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1743370286","listenUrl":"https://amaroka.bandcamp.com/track/tu-ny-viet","artist":"AMAROKA"},
      {"id":"bc-4209921681","listenUrl":"https://amaroka.bandcamp.com/track/pank-rok-naza-dy","artist":"AMAROKA"},
      {"id":"bc-648558747","listenUrl":"https://amaroka.bandcamp.com/track/hubliaju-kacha-nie","artist":"AMAROKA"},
      {"id":"bc-2738540625","listenUrl":"https://amaroka.bandcamp.com/track/pradajem","artist":"AMAROKA"},
      {"id":"bc-2756182932","listenUrl":"https://amaroka.bandcamp.com/track/zamiataje-zima","artist":"AMAROKA"},
      {"id":"bc-337211923","listenUrl":"https://amaroka.bandcamp.com/track/fliuhier","artist":"AMAROKA"},
      {"id":"bc-3676617314","listenUrl":"https://amaroka.bandcamp.com/track/razryvaje","artist":"AMAROKA"},
      {"id":"bc-1068797573","listenUrl":"https://amaroka.bandcamp.com/track/liudzi","artist":"AMAROKA"},
      {"id":"bc-1147792916","listenUrl":"https://amaroka.bandcamp.com/track/tvoj-a-tamat","artist":"AMAROKA"},
    ],
  },
  {
    sourceUrl: "https://astrouna.bandcamp.com/album/-",
    url: "https://f4.bcbits.com/img/a1857806678_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Вясна-красна, цёпла лецечка",
    publisher: "ASTROŪNA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3198421315","listenUrl":"https://astrouna.bandcamp.com/track/-","artist":"ASTROŪNA"},
      {"id":"bc-33663324","listenUrl":"https://astrouna.bandcamp.com/track/--2","artist":"ASTROŪNA"},
      {"id":"bc-2758031347","listenUrl":"https://astrouna.bandcamp.com/track/--3","artist":"ASTROŪNA"},
      {"id":"bc-2728520730","listenUrl":"https://astrouna.bandcamp.com/track/--4","artist":"ASTROŪNA"},
      {"id":"bc-216511723","listenUrl":"https://astrouna.bandcamp.com/track/--5","artist":"ASTROŪNA"},
      {"id":"bc-2270746025","listenUrl":"https://astrouna.bandcamp.com/track/--7","artist":"ASTROŪNA"},
      {"id":"bc-1266674917","listenUrl":"https://astrouna.bandcamp.com/track/--8","artist":"ASTROŪNA"},
      {"id":"bc-1168950206","listenUrl":"https://astrouna.bandcamp.com/track/--9","artist":"ASTROŪNA"},
      {"id":"bc-1631460825","listenUrl":"https://astrouna.bandcamp.com/track/--10","artist":"ASTROŪNA"},
      {"id":"bc-649168110","listenUrl":"https://astrouna.bandcamp.com/track/--11","artist":"ASTROŪNA"},
      {"id":"bc-573789204","listenUrl":"https://astrouna.bandcamp.com/track/--12","artist":"ASTROŪNA"},
      {"id":"bc-1153541506","listenUrl":"https://astrouna.bandcamp.com/track/--13","artist":"ASTROŪNA"},
      {"id":"bc-437283791","listenUrl":"https://astrouna.bandcamp.com/track/--15","artist":"ASTROŪNA"},
      {"id":"bc-2576492011","listenUrl":"https://astrouna.bandcamp.com/track/--16","artist":"ASTROŪNA"},
    ],
  },
  {
    sourceUrl: "https://dzieciuki.bandcamp.com/album/haradzenski-harmidar",
    url: "https://f4.bcbits.com/img/a2984626631_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Haradzenski Harmidar",
    publisher: "Dzieciuki",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2113086336","listenUrl":"https://dzieciuki.bandcamp.com/track/-","artist":"Dzieciuki"},
      {"id":"bc-117720768","listenUrl":"https://dzieciuki.bandcamp.com/track/--2","artist":"Dzieciuki"},
      {"id":"bc-1863502200","listenUrl":"https://dzieciuki.bandcamp.com/track/--3","artist":"Dzieciuki"},
      {"id":"bc-2995854866","listenUrl":"https://dzieciuki.bandcamp.com/track/--4","artist":"Dzieciuki"},
      {"id":"bc-3640245107","listenUrl":"https://dzieciuki.bandcamp.com/track/--5","artist":"Dzieciuki"},
      {"id":"bc-1544661766","listenUrl":"https://dzieciuki.bandcamp.com/track/--6","artist":"Dzieciuki"},
      {"id":"bc-2500333337","listenUrl":"https://dzieciuki.bandcamp.com/track/--7","artist":"Dzieciuki"},
      {"id":"bc-2824986194","listenUrl":"https://dzieciuki.bandcamp.com/track/i","artist":"Dzieciuki"},
      {"id":"bc-3739146155","listenUrl":"https://dzieciuki.bandcamp.com/track/--8","artist":"Dzieciuki"},
      {"id":"bc-2202646917","listenUrl":"https://dzieciuki.bandcamp.com/track/--9","artist":"Dzieciuki"},
    ],
  },
  {
    sourceUrl: "https://ezhevika.bandcamp.com/album/sonca",
    url: "https://f4.bcbits.com/img/a4182183996_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Sonca",
    publisher: "Shuma",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"shuma-rano","listenUrl":"https://ezhevika.bandcamp.com/track/rano-rano","artist":"Šuma"},
    ],
  },
  {
    sourceUrl: "https://ezhevika.bandcamp.com/album/znichka",
    url: "https://f4.bcbits.com/img/a4233211060_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Znichka",
    publisher: "Ana Zhdanova",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"ana-znichka","listenUrl":"https://ezhevika.bandcamp.com/track/znichka","artist":"Ana Zhdanova"},
      {"id":"ana-diamos","listenUrl":"https://ezhevika.bandcamp.com/track/znichka-diamos-roll-vision","artist":"Ana Zhdanova"},
      {"id":"ana-marmi","listenUrl":"https://ezhevika.bandcamp.com/track/znichka-marmi-remix","artist":"Ana Zhdanova"},
      {"id":"ana-kosmonavt","listenUrl":"https://ezhevika.bandcamp.com/track/znichka-kosmonavt-remix","artist":"Ana Zhdanova"},
    ],
  },
  {
    sourceUrl: "https://gruppasoyuz.bandcamp.com/album/krok",
    url: "https://f4.bcbits.com/img/a2393948265_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "KROK",
    publisher: "СОЮЗ / SOYUZ",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2529283070","listenUrl":"https://gruppasoyuz.bandcamp.com/track/krok","artist":"СОЮЗ / SOYUZ"},
    ],
  },
  {
    sourceUrl: "https://hetaleta.bandcamp.com/album/panoptykum",
    url: "https://f4.bcbits.com/img/a0017580595_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Panoptykum",
    publisher: "Leta",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2594948852","listenUrl":"https://hetaleta.bandcamp.com/track/praletarskaja","artist":"Leta"},
      {"id":"bc-1317282769","listenUrl":"https://hetaleta.bandcamp.com/track/lajk","artist":"Leta"},
      {"id":"bc-851427111","listenUrl":"https://hetaleta.bandcamp.com/track/naduryli","artist":"Leta"},
      {"id":"bc-2220619411","listenUrl":"https://hetaleta.bandcamp.com/track/tannaja-harelka","artist":"Leta"},
      {"id":"bc-3536443493","listenUrl":"https://hetaleta.bandcamp.com/track/hit","artist":"Leta"},
      {"id":"bc-3416457610","listenUrl":"https://hetaleta.bandcamp.com/track/ideolah","artist":"Leta"},
      {"id":"bc-2785124774","listenUrl":"https://hetaleta.bandcamp.com/track/sekstet-seiferta","artist":"Leta"},
      {"id":"bc-1346122203","listenUrl":"https://hetaleta.bandcamp.com/track/vam-pakiet","artist":"Leta"},
    ],
  },
  {
    sourceUrl: "https://jmors.bandcamp.com/album/--11",
    url: "https://f4.bcbits.com/img/a1993008278_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Зэкамерон. Песні да спектакля",
    publisher: "J:МОРС, Вольныя купалаўцы",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2925051591","listenUrl":"https://jmors.bandcamp.com/track/--117","artist":"J:МОРС, Volnyja Kupalaŭcy"},
      {"id":"bc-3905571451","listenUrl":"https://jmors.bandcamp.com/track/--118","artist":"J:МОРС, Volnyja Kupalaŭcy"},
      {"id":"bc-574063311","listenUrl":"https://jmors.bandcamp.com/track/--121","artist":"J:МОРС, Volnyja Kupalaŭcy"},
      {"id":"bc-2612295126","listenUrl":"https://jmors.bandcamp.com/track/--122","artist":"J:МОРС, Volnyja Kupalaŭcy"},
    ],
  },
  {
    sourceUrl: "https://jmors.bandcamp.com/album/ep-2",
    url: "https://f4.bcbits.com/img/a0183200844_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Блізка EP",
    publisher: "J:МОРС",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1719915277","listenUrl":"https://jmors.bandcamp.com/track/--115","artist":"J:МОРС"},
      {"id":"bc-3574457402","listenUrl":"https://jmors.bandcamp.com/track/feat-folkrada","artist":"J:МОРС feat. FolkRada"},
      {"id":"bc-487268639","listenUrl":"https://jmors.bandcamp.com/track/summer-version","artist":"J:МОРС"},
    ],
  },
  {
    sourceUrl: "https://koob.bandcamp.com/track/nie-chapai",
    url: "https://f4.bcbits.com/img/a1158116641_5.jpg",
    provider: "Bandcamp",
    scope: "track",
    releaseTitle: "Не чапай (Nie Chapai)",
    publisher: "KOOB",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"koob-nie-chapai-2021","listenUrl":"https://koob.bandcamp.com/track/nie-chapai","artist":"KOOB"},
    ],
  },
  {
    sourceUrl: "https://koob.bandcamp.com/track/zubraniatka",
    url: "https://f4.bcbits.com/img/a2845943579_5.jpg",
    provider: "Bandcamp",
    scope: "track",
    releaseTitle: "zubraniatka",
    publisher: "KOOB, SW@DA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"koob-swada-zubraniatka-2024","listenUrl":"https://koob.bandcamp.com/track/zubraniatka","artist":"KOOB, SW@DA"},
    ],
  },
  {
    sourceUrl: "https://leibonik.bandcamp.com/album/aki",
    url: "https://f4.bcbits.com/img/a3708440107_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Žaki",
    publisher: "Leibonik",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-69151418","listenUrl":"https://leibonik.bandcamp.com/track/o-d-a","artist":"Leibonik"},
      {"id":"bc-772941727","listenUrl":"https://leibonik.bandcamp.com/track/barada-horrar-beards-i","artist":"Leibonik"},
      {"id":"bc-3757243525","listenUrl":"https://leibonik.bandcamp.com/track/mars","artist":"Leibonik"},
      {"id":"bc-1082273466","listenUrl":"https://leibonik.bandcamp.com/track/zialonaja-vi-nia","artist":"Leibonik"},
      {"id":"bc-1102600238","listenUrl":"https://leibonik.bandcamp.com/track/sma-na-i-hutka","artist":"Leibonik"},
      {"id":"bc-2582045319","listenUrl":"https://leibonik.bandcamp.com/track/szbm-beards-ii","artist":"Leibonik"},
      {"id":"bc-1215653364","listenUrl":"https://leibonik.bandcamp.com/track/aki","artist":"Leibonik"},
      {"id":"bc-1878870790","listenUrl":"https://leibonik.bandcamp.com/track/cycy","artist":"Leibonik"},
    ],
  },
  {
    sourceUrl: "https://leibonik.bandcamp.com/album/tam",
    url: "https://f4.bcbits.com/img/a1883233795_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "TAM",
    publisher: "Leibonik",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2463927880","listenUrl":"https://leibonik.bandcamp.com/track/emigrant-song","artist":"Leibonik"},
      {"id":"bc-3372098592","listenUrl":"https://leibonik.bandcamp.com/track/hastroli","artist":"Leibonik"},
      {"id":"bc-90417827","listenUrl":"https://leibonik.bandcamp.com/track/slimak","artist":"Leibonik"},
      {"id":"bc-3482372188","listenUrl":"https://leibonik.bandcamp.com/track/hramadzianin","artist":"Leibonik"},
      {"id":"bc-2073519414","listenUrl":"https://leibonik.bandcamp.com/track/naviny","artist":"Leibonik"},
      {"id":"bc-2718421861","listenUrl":"https://leibonik.bandcamp.com/track/saty-graha-feat-recha","artist":"Leibonik feat. Recha"},
      {"id":"bc-2043985404","listenUrl":"https://leibonik.bandcamp.com/track/oj-zakuj","artist":"Leibonik"},
      {"id":"bc-3637937051","listenUrl":"https://leibonik.bandcamp.com/track/bie-arusami","artist":"Leibonik"},
    ],
  },
  {
    sourceUrl: "https://lutysakavik.bandcamp.com/album/bol-jon-moj",
    url: "https://f4.bcbits.com/img/a3371667141_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Bol Jon Moj",
    publisher: "luty sakavik",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3025087496","listenUrl":"https://lutysakavik.bandcamp.com/track/strach","artist":"luty sakavik"},
      {"id":"bc-3157405711","listenUrl":"https://lutysakavik.bandcamp.com/track/niuansy","artist":"luty sakavik"},
      {"id":"bc-3516134324","listenUrl":"https://lutysakavik.bandcamp.com/track/melancholija","artist":"luty sakavik"},
      {"id":"bc-473561943","listenUrl":"https://lutysakavik.bandcamp.com/track/nienavid-u-pary","artist":"luty sakavik"},
      {"id":"bc-2521337951","listenUrl":"https://lutysakavik.bandcamp.com/track/bie-ciabie-pavodle-krambambuli","artist":"luty sakavik"},
      {"id":"bc-1566677189","listenUrl":"https://lutysakavik.bandcamp.com/track/herbary","artist":"luty sakavik"},
      {"id":"bc-724277537","listenUrl":"https://lutysakavik.bandcamp.com/track/paasobku","artist":"luty sakavik"},
      {"id":"bc-1014551209","listenUrl":"https://lutysakavik.bandcamp.com/track/ho-y","artist":"luty sakavik"},
    ],
  },
  {
    sourceUrl: "https://misschambertale.bandcamp.com/album/yrvony-kraj",
    url: "https://f4.bcbits.com/img/a4124786760_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Čyrvony kraj",
    publisher: "Miss Chambertale",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2883711195","listenUrl":"https://misschambertale.bandcamp.com/track/yrvony-kraj","artist":"Miss Chambertale"},
    ],
  },
  {
    sourceUrl: "https://mnimayaos.bandcamp.com/album/--2",
    url: "https://f4.bcbits.com/img/a2985152973_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Тутака-Тамака",
    publisher: "Мнімая Ось",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-4224259127","listenUrl":"https://mnimayaos.bandcamp.com/track/--19","artist":"Мнімая Ось"},
      {"id":"bc-3176166484","listenUrl":"https://mnimayaos.bandcamp.com/track/--20","artist":"Мнімая Ось"},
      {"id":"bc-2154820749","listenUrl":"https://mnimayaos.bandcamp.com/track/--21","artist":"Мнімая Ось"},
      {"id":"bc-3205421724","listenUrl":"https://mnimayaos.bandcamp.com/track/--22","artist":"Мнімая Ось"},
      {"id":"bc-2625202357","listenUrl":"https://mnimayaos.bandcamp.com/track/--23","artist":"Мнімая Ось"},
      {"id":"bc-2257521560","listenUrl":"https://mnimayaos.bandcamp.com/track/--24","artist":"Мнімая Ось"},
      {"id":"bc-3973421665","listenUrl":"https://mnimayaos.bandcamp.com/track/--25","artist":"Мнімая Ось"},
      {"id":"bc-2310055373","listenUrl":"https://mnimayaos.bandcamp.com/track/--26","artist":"Мнімая Ось"},
      {"id":"bc-3414991576","listenUrl":"https://mnimayaos.bandcamp.com/track/--28","artist":"Мнімая Ось"},
    ],
  },
  {
    sourceUrl: "https://music.apple.com/us/album/%D0%B1%D0%B5%D0%BB%D0%B0%D1%80%D1%83%D1%81%D0%BA%D1%96%D1%8F-%D0%BA%D0%B0%D0%BB%D1%8B%D1%85%D0%B0%D0%BD%D0%BA%D1%96/1810683327",
    url: "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/0e/48/3f/0e483ffe-de60-0cf2-2cdc-3d226f2cb717/990591026360.png/600x600bf-60.jpg",
    provider: "Apple Music",
    scope: "album",
    releaseTitle: "Беларускія Калыханкі",
    publisher: "Apple Music catalogue",
    metadataField: "twitter:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact catalogue song/album identifiers and named public Apple release metadata.",
    bindings: [
      {"id":"apple-1810683328","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BF%D0%B0%D0%B9%D1%88%D0%BE%D1%9E%20%D0%BA%D0%BE%D1%86%D1%96%D0%BA%20%D1%83%20%D0%B3%D1%83%D0%BB%D1%96/1810683327?i=1810683328","artist":"Сяржук Доўгушаў · Tradycyja"},
      {"id":"apple-1810683329","listenUrl":"https://music.apple.com/us/album/%D0%90-%D0%B0%D0%B0%2C%20%D0%BA%D0%BE%D1%82%D0%BA%D1%96%20%D0%B4%D0%B2%D0%B0/1810683327?i=1810683329","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683330","listenUrl":"https://music.apple.com/us/album/%D0%90%D0%B9%2C%20%D0%BB%D1%8E%D0%BB%D1%96-%D0%BB%D1%8E%D0%BB%D1%96-%D0%BB%D1%8E%D0%BB%D1%96%2C%20%D0%B4%D0%B0%20%D1%9E%D1%81%D0%B5%20%D0%B4%D0%B7%D0%B5%D1%82%D0%BA%D1%96%20%D0%BC%D0%B0%D0%BB%D1%8B%D1%8F%20%D0%BF%D0%B0%D1%81%D0%BD%D1%83%D0%BB%D1%96/1810683327?i=1810683330","artist":"Яўгенія Чачура · Tradycyja"},
      {"id":"apple-1810683331","listenUrl":"https://music.apple.com/us/album/%D0%91%D0%B5%D0%B3%D0%BB%D0%B0%20%D0%BC%D1%83%D1%88%D0%BA%D0%B0%20%D0%BF%D0%B0%20%D0%BA%D0%B0%D0%BF%D1%83%D1%81%D1%86%D1%96/1810683327?i=1810683331","artist":"Таццяна Чорная · Tradycyja"},
      {"id":"apple-1810683332","listenUrl":"https://music.apple.com/us/album/%D0%94%D0%B0%20%D0%BB%D1%8E%D0%BB%D1%96-%D0%BB%D1%8E%D0%BB%D1%96%2C%20%D0%B4%D0%B0%20%D1%82%D1%8B%20%D0%B6%2C%20%D0%BC%D0%BE%D0%B5%20%D0%B4%D0%B7%D1%96%D1%86%D1%8F%D1%82%D0%BA%D0%BE/1810683327?i=1810683332","artist":"Таццяна Юнчыц · Tradycyja"},
      {"id":"apple-1810683333","listenUrl":"https://music.apple.com/us/album/%D0%90%20%D1%82%D1%8B%2C%20%D0%BA%D0%B0%D1%82%D0%BE%D0%BA%20%D1%88%D1%8D%D1%80%D1%8B/1810683327?i=1810683333","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683334","listenUrl":"https://music.apple.com/us/album/%D0%90%D1%85%2C%20%D0%B2%D1%8B%20%D0%BA%D0%BE%D1%86%D1%96%D0%BA%D1%96-%D0%BA%D0%B0%D1%82%D1%8B/1810683327?i=1810683334","artist":"Еўфрасіння Цішкова · Tradycyja"},
      {"id":"apple-1810683335","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%20%D1%81%D0%BF%D0%B0%D1%86%D1%8C%2C%20%D0%B0%20%D1%8F%20%D0%B1%D1%83%D0%B4%D1%83%20%D0%BA%D0%BE%D0%BB%D1%8B%D1%85%D0%B0%D1%86%D1%8C/1810683327?i=1810683335","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683336","listenUrl":"https://music.apple.com/us/album/%D0%9F%D0%B0%D0%B9%D1%88%D0%BE%D1%9E%20%D0%BA%D0%BE%D1%86%D1%96%D0%BA%20%D0%BF%D0%B0%20%D0%BF%D0%BB%D0%B0%D1%82%D1%83/1810683327?i=1810683336","artist":"Алена Герасімава · Tradycyja"},
      {"id":"apple-1810683337","listenUrl":"https://music.apple.com/us/album/%D0%A1%D0%BF%D1%96%2C%20%D0%BC%D0%BE%D0%B9%20%D1%81%D1%8B%D0%BD%D0%BA%D1%83%2C%20%D1%81%D0%BF%D1%96%2C%20%D1%81%D1%8B%D0%BD%D0%BE%D0%BA/1810683327?i=1810683337","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683338","listenUrl":"https://music.apple.com/us/album/%D0%91%D0%B0%D1%8E%2C%20%D0%B1%D0%B0%D1%8E%2C%20%D0%9D%D0%B5%D1%81%D1%86%D0%B5%D1%80%D0%BA%D0%B0/1810683327?i=1810683338","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683339","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BF%D1%80%D1%8B%D0%BB%D1%8F%D1%86%D0%B5%D0%BB%D1%96%20%D0%B3%D1%83%D0%BB%D1%96/1810683327?i=1810683339","artist":"Рыгор Барадулін · Tradycyja"},
      {"id":"apple-1810683340","listenUrl":"https://music.apple.com/us/album/%D0%90-%D0%B0-%D0%B0%D0%B9%2C%20%D0%BB%D1%8E%D0%BB%D1%96/1810683327?i=1810683340","artist":"Ганна Сакалоўская · Tradycyja"},
      {"id":"apple-1810683341","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BF%D1%80%D1%8B%D0%BB%D1%8D%D1%86%D1%96%D0%BB%D1%96%20%D0%B3%D1%83%D0%BB%D1%96/1810683327?i=1810683341","artist":"Ніна Міневіч і Надзея Супрун · Tradycyja"},
      {"id":"apple-1810683342","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BF%D1%80%D1%8B%D0%BB%D1%8F%D1%86%D0%B5%D0%BB%D1%96%20%D0%BA%D1%83%D1%80%D1%8B/1810683327?i=1810683342","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683343","listenUrl":"https://music.apple.com/us/album/%D0%9F%D0%B0%D0%B9%D1%88%D0%BE%D1%9E%20%D0%BA%D0%BE%D1%86%D1%96%D0%BA%20%D1%83%20%D0%BB%D1%8F%D1%81%D0%BE%D0%BA/1810683327?i=1810683343","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683344","listenUrl":"https://music.apple.com/us/album/%D0%90-%D0%B0%2C%20%D0%B4%D0%B7%D0%B5%D1%82%D0%BA%D0%B0%2C%20%D1%81%D0%BF%D0%B0%D1%86%D1%8C/1810683327?i=1810683344","artist":"Наталля Марковіч · Tradycyja"},
      {"id":"apple-1810683345","listenUrl":"https://music.apple.com/us/album/%D0%90%D0%B9%2C%20%D0%BB%D1%8E-%D0%BB%D1%8E%2C%20%D0%BC%D0%BE%D0%B9%20%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D1%96%20%D0%BA%D0%B0%D1%80%D0%B0%D0%BB%D1%8E/1810683327?i=1810683345","artist":"VOLYA · Tradycyja"},
      {"id":"apple-1810683346","listenUrl":"https://music.apple.com/us/album/%D0%9B%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%2C%20%D0%BB%D1%8E-%D0%BB%D1%96%20%D1%81%D0%BF%D0%B0%D1%86%D1%8C/1810683327?i=1810683346","artist":"Ядвіга Альфер · Tradycyja"},
    ],
  },
  {
    sourceUrl: "https://music.apple.com/us/song/1333929562",
    url: "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/07/85/a6/0785a621-a405-8f8c-f598-5be582f11f26/cover.jpg/600x600bf-60.jpg",
    provider: "Apple Music",
    scope: "track",
    releaseTitle: "Калыханка (feat. Alexander Muratovsky)",
    publisher: "Apple Music catalogue",
    metadataField: "twitter:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact catalogue song/album identifiers and named public Apple release metadata.",
    bindings: [
      {"id":"ulyanoow-kalykhanka-2016","listenUrl":"https://music.apple.com/us/song/1333929562","artist":"ULYANOOW"},
    ],
  },
  {
    sourceUrl: "https://naviband.bandcamp.com/album/-",
    url: "https://f4.bcbits.com/img/a4152307530_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Адной дарогай",
    publisher: "NAVIBAND",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-4170861870","listenUrl":"https://naviband.bandcamp.com/track/--9","artist":"NAVIBAND"},
      {"id":"bc-1280086167","listenUrl":"https://naviband.bandcamp.com/track/--10","artist":"NAVIBAND"},
      {"id":"bc-2233965950","listenUrl":"https://naviband.bandcamp.com/track/--11","artist":"NAVIBAND"},
      {"id":"bc-1686218633","listenUrl":"https://naviband.bandcamp.com/track/--12","artist":"NAVIBAND"},
      {"id":"bc-195379354","listenUrl":"https://naviband.bandcamp.com/track/--13","artist":"NAVIBAND"},
      {"id":"bc-3856409198","listenUrl":"https://naviband.bandcamp.com/track/--14","artist":"NAVIBAND"},
      {"id":"bc-776364687","listenUrl":"https://naviband.bandcamp.com/track/--15","artist":"NAVIBAND"},
      {"id":"bc-1475122249","listenUrl":"https://naviband.bandcamp.com/track/--16","artist":"NAVIBAND"},
      {"id":"bc-3051383185","listenUrl":"https://naviband.bandcamp.com/track/--17","artist":"NAVIBAND"},
    ],
  },
  {
    sourceUrl: "https://nizkiz.bandcamp.com/track/--32",
    url: "https://f4.bcbits.com/img/a2298769800_5.jpg",
    provider: "Bandcamp",
    scope: "track",
    releaseTitle: "Правілы",
    publisher: "NIZKIZ",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"nizkiz-pravily","listenUrl":"https://nizkiz.bandcamp.com/track/--32","artist":"NIZKIZ"},
    ],
  },
  {
    sourceUrl: "https://nurnbergminsk.bandcamp.com/album/adkaz",
    url: "https://f4.bcbits.com/img/a2065764041_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Adkaz",
    publisher: "Nürnberg",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1929267369","listenUrl":"https://nurnbergminsk.bandcamp.com/track/insomnia","artist":"Nürnberg"},
      {"id":"bc-2739398510","listenUrl":"https://nurnbergminsk.bandcamp.com/track/horad","artist":"Nürnberg"},
      {"id":"bc-2913337126","listenUrl":"https://nurnbergminsk.bandcamp.com/track/adkaz","artist":"Nürnberg"},
      {"id":"bc-2404778083","listenUrl":"https://nurnbergminsk.bandcamp.com/track/miesca","artist":"Nürnberg"},
      {"id":"bc-3956297895","listenUrl":"https://nurnbergminsk.bandcamp.com/track/adliha","artist":"Nürnberg"},
      {"id":"bc-3135913542","listenUrl":"https://nurnbergminsk.bandcamp.com/track/vada","artist":"Nürnberg"},
      {"id":"bc-514877096","listenUrl":"https://nurnbergminsk.bandcamp.com/track/strach","artist":"Nürnberg"},
      {"id":"bc-1597488723","listenUrl":"https://nurnbergminsk.bandcamp.com/track/pacalunak","artist":"Nürnberg"},
    ],
  },
  {
    sourceUrl: "https://nurnbergminsk.bandcamp.com/track/valasy",
    url: "https://f4.bcbits.com/img/a2846376412_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Skryvaj",
    publisher: "Nürnberg",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"nurnberg-valasy","listenUrl":"https://nurnbergminsk.bandcamp.com/track/valasy","artist":"Nürnberg"},
    ],
  },
  {
    sourceUrl: "https://parusproject.bandcamp.com/album/zara",
    url: "https://f4.bcbits.com/img/a3030174598_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Zara",
    publisher: "Parus",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1938562571","listenUrl":"https://parusproject.bandcamp.com/track/zara","artist":"Parus"},
      {"id":"bc-704582768","listenUrl":"https://parusproject.bandcamp.com/track/soniejka","artist":"Parus"},
      {"id":"bc-1654432481","listenUrl":"https://parusproject.bandcamp.com/track/ru-ovyja-viaty","artist":"Parus"},
      {"id":"bc-473050417","listenUrl":"https://parusproject.bandcamp.com/track/oj-uhom-idu","artist":"Parus"},
      {"id":"bc-1082238178","listenUrl":"https://parusproject.bandcamp.com/track/zara-live-version","artist":"Parus"},
    ],
  },
  {
    sourceUrl: "https://prorva.bandcamp.com/album/recha",
    url: "https://f4.bcbits.com/img/a3281450371_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Recha",
    publisher: "Prorva",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2675028084","listenUrl":"https://prorva.bandcamp.com/track/mury","artist":"Prorva"},
      {"id":"bc-3472089515","listenUrl":"https://prorva.bandcamp.com/track/turma","artist":"Prorva"},
      {"id":"bc-4102929650","listenUrl":"https://prorva.bandcamp.com/track/nieba","artist":"Prorva"},
      {"id":"bc-1621030002","listenUrl":"https://prorva.bandcamp.com/track/rosta","artist":"Prorva"},
      {"id":"bc-264013297","listenUrl":"https://prorva.bandcamp.com/track/u-puste-y","artist":"Prorva"},
      {"id":"bc-4175271848","listenUrl":"https://prorva.bandcamp.com/track/y-nasupor-bonus-track","artist":"Prorva"},
    ],
  },
  {
    sourceUrl: "https://prorva.bandcamp.com/album/u-cieni-impieryj",
    url: "https://f4.bcbits.com/img/a2320547811_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "U cieni impieryj",
    publisher: "Prorva",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2925559163","listenUrl":"https://prorva.bandcamp.com/track/smuha","artist":"Prorva"},
      {"id":"bc-3736671927","listenUrl":"https://prorva.bandcamp.com/track/dryhva","artist":"Prorva"},
      {"id":"bc-512324351","listenUrl":"https://prorva.bandcamp.com/track/u-cieni-impieryj","artist":"Prorva"},
    ],
  },
  {
    sourceUrl: "https://purplesunsetband.bandcamp.com/album/--2",
    url: "https://f4.bcbits.com/img/a1428634989_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Фіялетавы закат",
    publisher: "Purple Sunset",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-617389935","listenUrl":"https://purplesunsetband.bandcamp.com/track/-","artist":"Purple Sunset"},
      {"id":"bc-2835388969","listenUrl":"https://purplesunsetband.bandcamp.com/track/--2","artist":"Purple Sunset"},
      {"id":"bc-3036829622","listenUrl":"https://purplesunsetband.bandcamp.com/track/--3","artist":"Purple Sunset"},
      {"id":"bc-2705888892","listenUrl":"https://purplesunsetband.bandcamp.com/track/--4","artist":"Purple Sunset"},
      {"id":"bc-2967674573","listenUrl":"https://purplesunsetband.bandcamp.com/track/--5","artist":"Purple Sunset"},
      {"id":"bc-1526118790","listenUrl":"https://purplesunsetband.bandcamp.com/track/--6","artist":"Purple Sunset"},
      {"id":"bc-440551917","listenUrl":"https://purplesunsetband.bandcamp.com/track/--7","artist":"Purple Sunset"},
      {"id":"bc-3912578282","listenUrl":"https://purplesunsetband.bandcamp.com/track/--8","artist":"Purple Sunset"},
      {"id":"bc-1293602219","listenUrl":"https://purplesunsetband.bandcamp.com/track/--9","artist":"Purple Sunset"},
      {"id":"bc-2536151638","listenUrl":"https://purplesunsetband.bandcamp.com/track/--10","artist":"Purple Sunset"},
      {"id":"bc-4080814864","listenUrl":"https://purplesunsetband.bandcamp.com/track/--12","artist":"Purple Sunset"},
      {"id":"bc-3367695236","listenUrl":"https://purplesunsetband.bandcamp.com/track/--13","artist":"Purple Sunset"},
    ],
  },
  {
    sourceUrl: "https://purplesunsetband.bandcamp.com/album/novy-dzie",
    url: "https://f4.bcbits.com/img/a3880860240_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Novy dzień",
    publisher: "Purple Sunset",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3046238116","listenUrl":"https://purplesunsetband.bandcamp.com/track/skarb","artist":"Purple Sunset"},
      {"id":"bc-229924503","listenUrl":"https://purplesunsetband.bandcamp.com/track/idealny-a-aviek","artist":"Purple Sunset"},
      {"id":"bc-2046678827","listenUrl":"https://purplesunsetband.bandcamp.com/track/horad-zda","artist":"Purple Sunset"},
      {"id":"bc-4197998306","listenUrl":"https://purplesunsetband.bandcamp.com/track/pala-ni-y-ci-achviara","artist":"Purple Sunset"},
      {"id":"bc-34899693","listenUrl":"https://purplesunsetband.bandcamp.com/track/ko-namu-svajo","artist":"Purple Sunset"},
      {"id":"bc-1158228510","listenUrl":"https://purplesunsetband.bandcamp.com/track/dziakuj-to-ty-jo","artist":"Purple Sunset"},
      {"id":"bc-106998399","listenUrl":"https://purplesunsetband.bandcamp.com/track/ciahnik-u-vyraj","artist":"Purple Sunset"},
      {"id":"bc-932237776","listenUrl":"https://purplesunsetband.bandcamp.com/track/skarb-alternative-version","artist":"Purple Sunset"},
    ],
  },
  {
    sourceUrl: "https://radioplato.bandcamp.com/album/amal",
    url: "https://f4.bcbits.com/img/a3351826994_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Amal",
    publisher: "Vapna",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2895991220","listenUrl":"https://radioplato.bandcamp.com/track/la-mora","artist":"Vapna"},
      {"id":"bc-3573038616","listenUrl":"https://radioplato.bandcamp.com/track/1000-krain-2","artist":"Vapna"},
      {"id":"bc-2238042935","listenUrl":"https://radioplato.bandcamp.com/track/voziera-sloz","artist":"Vapna"},
      {"id":"bc-2740609283","listenUrl":"https://radioplato.bandcamp.com/track/try-kancy","artist":"Vapna"},
      {"id":"bc-1539953314","listenUrl":"https://radioplato.bandcamp.com/track/mama-kazala","artist":"Vapna"},
      {"id":"bc-2497107544","listenUrl":"https://radioplato.bandcamp.com/track/amal","artist":"Vapna"},
      {"id":"bc-2696061877","listenUrl":"https://radioplato.bandcamp.com/track/skul","artist":"Vapna"},
      {"id":"bc-520423310","listenUrl":"https://radioplato.bandcamp.com/track/redki-vid-2","artist":"Vapna"},
      {"id":"bc-3203739073","listenUrl":"https://radioplato.bandcamp.com/track/orny-smo","artist":"Vapna"},
      {"id":"bc-1639874323","listenUrl":"https://radioplato.bandcamp.com/track/palohka","artist":"Vapna"},
    ],
  },
  {
    sourceUrl: "https://relikt-belarus.bandcamp.com/album/ramantyzm",
    url: "https://f4.bcbits.com/img/a0958237917_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Ramantyzm",
    publisher: "Relikt",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-546126279","listenUrl":"https://relikt-belarus.bandcamp.com/track/kiparys","artist":"Relikt"},
      {"id":"bc-1050406220","listenUrl":"https://relikt-belarus.bandcamp.com/track/scizoryk-2","artist":"Relikt"},
      {"id":"bc-1983439804","listenUrl":"https://relikt-belarus.bandcamp.com/track/chrusta","artist":"Relikt"},
      {"id":"bc-3950787447","listenUrl":"https://relikt-belarus.bandcamp.com/track/niekrafon","artist":"Relikt"},
      {"id":"bc-2849734238","listenUrl":"https://relikt-belarus.bandcamp.com/track/sivyya-valasy","artist":"Relikt"},
      {"id":"bc-3077763073","listenUrl":"https://relikt-belarus.bandcamp.com/track/bursoniki-2","artist":"Relikt"},
      {"id":"bc-2991968932","listenUrl":"https://relikt-belarus.bandcamp.com/track/losk-2","artist":"Relikt"},
      {"id":"bc-320884769","listenUrl":"https://relikt-belarus.bandcamp.com/track/anemoia","artist":"Relikt"},
    ],
  },
  {
    sourceUrl: "https://shumaduo.bandcamp.com/album/bahna",
    url: "https://f4.bcbits.com/img/a3037982863_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Bahna",
    publisher: "Shuma",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-718277530","listenUrl":"https://shumaduo.bandcamp.com/track/maslenica","artist":"Shuma"},
      {"id":"bc-624787804","listenUrl":"https://shumaduo.bandcamp.com/track/koleda","artist":"Shuma"},
    ],
  },
  {
    sourceUrl: "https://shumaduo.bandcamp.com/track/niuka",
    url: "https://f4.bcbits.com/img/a3037982863_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Bahna",
    publisher: "Shuma",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"shuma-niuka-2025","listenUrl":"https://shumaduo.bandcamp.com/track/niuka","artist":"Šuma"},
    ],
  },
  {
    sourceUrl: "https://shumaduo.bandcamp.com/track/zamova",
    url: "https://f4.bcbits.com/img/a3996278568_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Bahna",
    publisher: "Shuma",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"shuma-zamova-2025","listenUrl":"https://shumaduo.bandcamp.com/track/zamova","artist":"Šuma"},
    ],
  },
  {
    sourceUrl: "https://syndromsamazvanca.bandcamp.com/album/mahajba",
    url: "https://f4.bcbits.com/img/a0710377558_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Mahajba",
    publisher: "Syndrom Samazvanca",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1014416643","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/kosmische-walatschobniken","artist":"Syndrom Samazvanca"},
      {"id":"bc-1677788206","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/pa-za-hajem","artist":"Syndrom Samazvanca"},
      {"id":"bc-3517737969","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/masty","artist":"Syndrom Samazvanca"},
      {"id":"bc-405291580","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/dudka","artist":"Syndrom Samazvanca"},
      {"id":"bc-977754909","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/maslienica-bop","artist":"Syndrom Samazvanca"},
      {"id":"bc-971481883","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/biaskoncy-tala-yn","artist":"Syndrom Samazvanca"},
    ],
  },
  {
    sourceUrl: "https://syndromsamazvanca.bandcamp.com/album/sonk",
    url: "https://f4.bcbits.com/img/a4163019518_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Sonk",
    publisher: "Syndrom Samazvanca",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1948226814","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/novy-kosmas","artist":"Syndrom Samazvanca"},
      {"id":"bc-423350096","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/mliava","artist":"Syndrom Samazvanca"},
      {"id":"bc-3376537947","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/karahod","artist":"Syndrom Samazvanca"},
      {"id":"bc-4203592985","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/alimpijada-20","artist":"Syndrom Samazvanca"},
      {"id":"bc-1898729632","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/darmajed","artist":"Syndrom Samazvanca"},
    ],
  },
  {
    sourceUrl: "https://syndromsamazvanca.bandcamp.com/album/vostra-skarha",
    url: "https://f4.bcbits.com/img/a0054605423_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Vostraŭ skarhaŭ",
    publisher: "Syndrom Samazvanca",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1668394091","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/kvietki-zla","artist":"Syndrom Samazvanca"},
      {"id":"bc-830230361","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/promni","artist":"Syndrom Samazvanca"},
      {"id":"bc-1463187380","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/na-dno","artist":"Syndrom Samazvanca"},
      {"id":"bc-1868493956","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/halijaf","artist":"Syndrom Samazvanca"},
      {"id":"bc-3224914933","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/aliena-k","artist":"Syndrom Samazvanca"},
      {"id":"bc-2824721335","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/i-h-d","artist":"Syndrom Samazvanca"},
      {"id":"bc-1177160760","listenUrl":"https://syndromsamazvanca.bandcamp.com/track/liod-kryhalom","artist":"Syndrom Samazvanca"},
    ],
  },
  {
    sourceUrl: "https://tradycyja.bandcamp.com/album/male-singing-tradition",
    url: "https://f4.bcbits.com/img/a1567102369_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Мужчынская традыцыя спеву / Male singing tradition",
    publisher: "TRADYCYJA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-3430133731","listenUrl":"https://tradycyja.bandcamp.com/track/mowers-are-mowing-the-wind-is-blowing","artist":"Hlushkavichy male singing group"},
      {"id":"bc-1845303247","listenUrl":"https://tradycyja.bandcamp.com/track/dont-walk-by-the-river-bank-cossack","artist":"Hlushkavichy male singing group"},
      {"id":"bc-674752580","listenUrl":"https://tradycyja.bandcamp.com/track/i-will-go-up-the-hill-where-my-love-began","artist":"Hlushkavichy male singing group"},
      {"id":"bc-687217648","listenUrl":"https://tradycyja.bandcamp.com/track/the-sun-arises-over-siberia","artist":"Hlushkavichy male singing group"},
      {"id":"bc-1051204598","listenUrl":"https://tradycyja.bandcamp.com/track/5-my-dad-will-not-let-me-go","artist":"Hlushkavichy male singing group"},
      {"id":"bc-1677576914","listenUrl":"https://tradycyja.bandcamp.com/track/in-the-meadow-on-the-pond-on-the-water","artist":"Hlushkavichy male singing group"},
      {"id":"bc-404206721","listenUrl":"https://tradycyja.bandcamp.com/track/in-the-meadow-in-the-meadow-in-an-oak-tree","artist":"Hlushkavichy male singing group"},
      {"id":"bc-2876364464","listenUrl":"https://tradycyja.bandcamp.com/track/hey-mommy-cherry","artist":"Stsiapan Dubieika"},
      {"id":"bc-2735617307","listenUrl":"https://tradycyja.bandcamp.com/track/other-girls-are-like-berries-like-roses-in-bloom","artist":"Stsiapan Dubieika"},
      {"id":"bc-3778600087","listenUrl":"https://tradycyja.bandcamp.com/track/nothing-blossoms-in-the-fields-of-turkey","artist":"Stsiapan Dubieika"},
      {"id":"bc-294468836","listenUrl":"https://tradycyja.bandcamp.com/track/i-will-but-go-through-the-dark-woods","artist":"Stsiapan Dubieika"},
      {"id":"bc-1004977820","listenUrl":"https://tradycyja.bandcamp.com/track/hey-fog-good-old-fog","artist":"Stsiapan Dubieika"},
      {"id":"bc-106544161","listenUrl":"https://tradycyja.bandcamp.com/track/when-a-dark-cloud-was-coming-out","artist":"Stsiapan Dubieika"},
      {"id":"bc-848276350","listenUrl":"https://tradycyja.bandcamp.com/track/hey-you-sorrow-little-sorrow","artist":"Plytahony"},
      {"id":"bc-4145080774","listenUrl":"https://tradycyja.bandcamp.com/track/along-the-road-young-boys-were-going-song-of-recruits","artist":"Plytahony"},
      {"id":"bc-2063099038","listenUrl":"https://tradycyja.bandcamp.com/track/two-pigeons-hum-the-dove-coos","artist":"Mokhau male singing group"},
      {"id":"bc-3776769155","listenUrl":"https://tradycyja.bandcamp.com/track/grey-bulls-yellow-bulls","artist":"Mokhau male singing group"},
      {"id":"bc-1957025266","listenUrl":"https://tradycyja.bandcamp.com/track/18-and-out-of-the-woods-dark-woods-easter-song","artist":"Ryhor Maretski"},
      {"id":"bc-2424286391","listenUrl":"https://tradycyja.bandcamp.com/track/early-sunday-morning-midsummer-night-s-ballad","artist":"Fiodar Klimchuk"},
    ],
  },
  {
    sourceUrl: "https://tradycyja.bandcamp.com/album/sung-by-mum-folk-songs-from-vushachchyna",
    url: "https://f4.bcbits.com/img/a3177431799_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Песні матчыны з Вушаччыны / Sung by Mum: Folk Songs from Vushachchyna",
    publisher: "TRADYCYJA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2504472994","listenUrl":"https://tradycyja.bandcamp.com/track/akulina-andreje-na-baradulina-rada-rada-era-pierapio-ka","artist":"Akulina Andrejeŭna Baradulina"},
      {"id":"bc-1197563403","listenUrl":"https://tradycyja.bandcamp.com/track/vuraj-oj-lata-a","artist":"Vuraj"},
      {"id":"bc-527747000","listenUrl":"https://tradycyja.bandcamp.com/track/folk-band-varhan-hojknu-baravik-a-wedding-song","artist":"Varhan"},
      {"id":"bc-186924125","listenUrl":"https://tradycyja.bandcamp.com/track/ryhor-baradulin-kum-nia-pje-a-christening-party-song","artist":"Ryhor Baradulin"},
      {"id":"bc-1521233985","listenUrl":"https://tradycyja.bandcamp.com/track/rmonic-style-project-chre-binnaja-a-christening-party-song","artist":"Harmonic Style Project"},
      {"id":"bc-1388192953","listenUrl":"https://tradycyja.bandcamp.com/track/folk-band-varhan-kupalskaja-a-midsummer-s-day-song","artist":"Varhan"},
      {"id":"bc-2034688005","listenUrl":"https://tradycyja.bandcamp.com/track/viktar-siama-ka-maksim-i-kin-a-ciomnym-lesie","artist":"Viktar Siamaška, Maksim Iŭkin"},
      {"id":"bc-2999777117","listenUrl":"https://tradycyja.bandcamp.com/track/rmonic-style-project-siem-arak-a-drinking-song","artist":"Harmonic Style Project"},
      {"id":"bc-511177895","listenUrl":"https://tradycyja.bandcamp.com/track/folk-band-varhan-va-a-obnaja","artist":"Varhan"},
      {"id":"bc-2511386819","listenUrl":"https://tradycyja.bandcamp.com/track/re1ikt-drobnienki-do-d-yk","artist":"Re1ikt"},
      {"id":"bc-3887032303","listenUrl":"https://tradycyja.bandcamp.com/track/choir-salutaris-oj-lata-a","artist":"Choir Salutaris"},
      {"id":"bc-1272203683","listenUrl":"https://tradycyja.bandcamp.com/track/ryhor-baradulin-pierapio-ka","artist":"Ryhor Baradulin"},
    ],
  },
  {
    sourceUrl: "https://viasna.bandcamp.com/album/-",
    url: "https://f4.bcbits.com/img/a2212147459_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "ПАЗНАЧАНЫЯ ЖОЎТЫМ",
    publisher: "VIASNA",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-1286258235","listenUrl":"https://viasna.bandcamp.com/track/-","artist":"Angst"},
      {"id":"bc-1350202714","listenUrl":"https://viasna.bandcamp.com/track/--2","artist":"Andrej Novik, ZHEUZHIK"},
      {"id":"bc-1638501910","listenUrl":"https://viasna.bandcamp.com/track/--3","artist":"Andrej Novik, Alana Hebremaryjam, Krystsina Drobysh"},
      {"id":"bc-1685567117","listenUrl":"https://viasna.bandcamp.com/track/--4","artist":"Ksenija Halubovich, Andrej Novik, Krystsina Drobysh"},
      {"id":"bc-2268022060","listenUrl":"https://viasna.bandcamp.com/track/--5","artist":"Ales Papkovich, ZHEUZHIK"},
      {"id":"bc-3139801025","listenUrl":"https://viasna.bandcamp.com/track/--6","artist":"Uhead"},
    ],
  },
  {
    sourceUrl: "https://vihilija.bandcamp.com/album/amor-fati",
    url: "https://f4.bcbits.com/img/a2759875481_5.jpg",
    provider: "Bandcamp",
    scope: "album",
    releaseTitle: "Amor Fati",
    publisher: "Vihilija",
    metadataField: "og:image",
    checked: "2026-09-12",
    rightsStatus: "source-linked; artwork reuse permission not independently established",
    pairingBasis: "Exact source page; album members matched by published recording URL and platform track ID.",
    bindings: [
      {"id":"bc-2892144943","listenUrl":"https://vihilija.bandcamp.com/track/meta-2","artist":"Vihilija"},
      {"id":"bc-1688688200","listenUrl":"https://vihilija.bandcamp.com/track/kazka-2","artist":"Vihilija"},
      {"id":"bc-1274905782","listenUrl":"https://vihilija.bandcamp.com/track/dzikaje-palavannie-2","artist":"Vihilija"},
      {"id":"bc-2383106803","listenUrl":"https://vihilija.bandcamp.com/track/treciaja-varta-2","artist":"Vihilija"},
      {"id":"bc-3011389831","listenUrl":"https://vihilija.bandcamp.com/track/vada-2","artist":"Vihilija"},
      {"id":"bc-927931107","listenUrl":"https://vihilija.bandcamp.com/track/adzinocz-2","artist":"Vihilija"},
      {"id":"bc-3876150951","listenUrl":"https://vihilija.bandcamp.com/track/stary-zapaviet","artist":"Vihilija"},
    ],
  },
];
export const artworkEvidence = Object.freeze({
  checked: '2026-09-12', sourcePages: 42, recordingBindings: 280,
  imageFilesCopied: 0,
  visuallyReviewedImages: 41,
  visualReview: 'All 41 distinct source-image URLs viewed in five locally served Chrome contact sheets on 2026-09-12; release labels and source links were visible. Album art for Valasy (Skryvaj), Niuka and Zamova (Bahna) was then confirmed on the artist track pages. No image files are copied or rehosted; browsers fetch remote images only after an explicit cover preference.',
  limitations: 'Source metadata and exact release membership checked. Visual review is not a rights clearance, authenticity certificate or child-safety rating. Reuse rights remain unverified and remote images or availability may change.',
});
