import {escapeHTML as e,safeUrl,search,metadataPassport} from './core.js';
import {addCollection,exportCollection,parseCollection,playerFor} from './library.js';
import {readStudyHistory,studyHistoryExport} from './study.js';
import {enhanceStudy} from './study-interface.js';
import {enhanceWorkflows,decorateQueue} from './listener-workflows.js';
import {enhanceSemantic} from './semantic-interface.js';

export const experienceCopy={
 en:{newCollection:'New collection',collections:'Your collections',untitled:'Untitled collection',portable:'Export transferable collection',importCollection:'Import a collection',importHelp:'Paste a Unmute collection JSON export. It creates a new collection without replacing yours. New links remain unverified; no audio or accounts are imported.',importAction:'Preview import',confirmImport:'Add as a new collection',importError:'This is not a valid Unmute collection (maximum 100 records / 1 MB), or your library is full.',importSuccess:'Collection imported. Existing collections are unchanged.',pasteJSON:'Collection JSON',playHere:'Listen here',loadPlayer:'Load official player',playerPrivacy:'Loading this player connects to the music platform. Source covers use a separate saved preference. It receives your IP address and may store cookies. Your search and collection are not sent by Unmute. Playback depends on the platform and your region.',playerFallback:'If the player cannot play, open the original source.',closePlayer:'Close player',playerTitle:'Official listening player',database:'Catalogue & sources',databaseTitle:'Look inside the collection.',databaseIntro:'Recording-level data, visible sources and explicit gaps. No popularity ranking, automatic language verification or claim to cover the whole internet.',recordings:'Recordings',works:'Linked works / groups',belarusian:'Belarusian-language',platformLinks:'Listening links',tableTrack:'Recording / artist',tableSource:'Source',catalogExport:'Export catalogue metadata',catalogHelp:'Includes editorial metadata and source links, not audio or lyrics. A linked version is not another independent work.',matchWhy:'Why this matched',suggestions:'Did you mean…?',saveResults:'Save results to a new collection',loadMore:'Show more results',shown:'shown',branchHelp:'OR separates alternatives; within each alternative the conditions combine. Exclusions mean “not labelled that way in this catalogue”, not a verified absence.',newTitle:'Name your collection',searchHelp:'Search styles, documented themes, artists and titles in EN / BE / RU. Use OR for alternatives and NOT to exclude catalogue labels. Quoted titles stay literal. This is structured search, not an all-internet AI or audio-analysis engine.',feedbackLink:'Test this task',private:'Private working prototype · only on this computer',libraryIntro:'Build separate selections, keep their order, and move them between browsers using the transferable export. Nothing is uploaded.',storageNote:'Saved only in this browser. Export JSON to restore a selection elsewhere; HTML and text are reading copies.'},
 ru:{newCollection:'Новая подборка',collections:'Твои подборки',untitled:'Без названия',portable:'Экспорт для переноса',importCollection:'Импорт подборки',importHelp:'Вставь JSON-файл подборки Unmute. Появится новая подборка — существующие не заменяются. Новые ссылки остаются непроверенными; аудио и аккаунты не импортируются.',importAction:'Проверить импорт',confirmImport:'Добавить новой подборкой',importError:'Нужен корректный экспорт Unmute (до 100 записей / 1 МБ); возможно, библиотека заполнена.',importSuccess:'Подборка импортирована. Прежние подборки сохранены.',pasteJSON:'JSON подборки',playHere:'Слушать здесь',loadPlayer:'Загрузить официальный плеер',playerPrivacy:'Только эта кнопка подключается к музыкальной платформе. Она получит IP-адрес и может сохранять cookies. Unmute не передаёт ей твой запрос и подборку. Прослушивание зависит от платформы и региона.',playerFallback:'Если плеер не воспроизводит запись, открой оригинальный источник.',closePlayer:'Закрыть плеер',playerTitle:'Официальный плеер',database:'Каталог и источники',databaseTitle:'Что внутри коллекции.',databaseIntro:'Данные отдельных записей, видимые источники и честные пробелы. Без рейтинга популярности, автоматической проверки языка и обещания охватить весь интернет.',recordings:'Записи',works:'Связанные произведения / группы',belarusian:'На белорусском',platformLinks:'Ссылки прослушивания',tableTrack:'Запись / исполнитель',tableSource:'Источник',catalogExport:'Экспорт метаданных каталога',catalogHelp:'Редакторские метаданные и ссылки — без аудио и текстов песен. Связанная версия не считается отдельным произведением.',matchWhy:'Почему найдено',suggestions:'Возможно, ты искал…',saveResults:'Сохранить результаты новой подборкой',loadMore:'Показать ещё',shown:'показано',branchHelp:'ИЛИ разделяет альтернативы; внутри каждой условия объединяются. Исключение означает «нет такой метки в каталоге», а не доказанное отсутствие свойства.',newTitle:'Название подборки',searchHelp:'Стили, темы с источниками, исполнители и названия на EN / BE / RU. ИЛИ — альтернативы, НЕ — исключение меток каталога. Название в кавычках ищется буквально. Это структурированный поиск, не ИИ по всему интернету и не анализ аудио.',feedbackLink:'Проверить это задание',private:'Частный рабочий прототип · только на этом компьютере',libraryIntro:'Собирай отдельные подборки, меняй порядок и переноси их в другой браузер через экспорт. Ничего не загружается на сервер.',storageNote:'Сохранено только в этом браузере. JSON восстанавливает подборку в другом браузере; HTML и текст — копии для чтения.'},
 be:{newCollection:'Новая падборка',collections:'Твае падборкі',untitled:'Без назвы',portable:'Экспарт для пераносу',importCollection:'Імпарт падборкі',importHelp:'Устаў JSON-файл падборкі Unmute. З’явіцца новая падборка — існыя не замяняюцца. Новыя спасылкі застаюцца неправеранымі; аўдыя і акаўнты не імпартуюцца.',importAction:'Праверыць імпарт',confirmImport:'Дадаць новай падборкай',importError:'Патрэбны карэктны экспарт Unmute (да 100 запісаў / 1 МБ); магчыма, бібліятэка запоўненая.',importSuccess:'Падборка імпартаваная. Ранейшыя падборкі захаваныя.',pasteJSON:'JSON падборкі',playHere:'Слухаць тут',loadPlayer:'Загрузіць афіцыйны плэер',playerPrivacy:'Толькі гэтая кнопка падключаецца да музычнай платформы. Яна атрымае IP-адрас і можа захоўваць cookies. Unmute не перадае ёй твой запыт і падборку. Праслухоўванне залежыць ад платформы і рэгіёна.',playerFallback:'Калі плэер не прайграе запіс, адкрый арыгінальную крыніцу.',closePlayer:'Закрыць плэер',playerTitle:'Афіцыйны плэер',database:'Каталог і крыніцы',databaseTitle:'Што ўнутры калекцыі.',databaseIntro:'Даныя асобных запісаў, бачныя крыніцы і сумленныя прабелы. Без рэйтынгу папулярнасці, аўтаматычнай праверкі мовы і абяцання ахапіць увесь інтэрнэт.',recordings:'Запісы',works:'Звязаныя творы / групы',belarusian:'Па-беларуску',platformLinks:'Спасылкі праслухоўвання',tableTrack:'Запіс / выканаўца',tableSource:'Крыніца',catalogExport:'Экспарт метаданых каталога',catalogHelp:'Рэдактарскія метаданыя і спасылкі — без аўдыя і тэкстаў песень. Звязаная версія не лічыцца асобным творам.',matchWhy:'Чаму знойдзена',suggestions:'Магчыма, ты шукаў…',saveResults:'Захаваць вынікі новай падборкай',loadMore:'Паказаць яшчэ',shown:'паказана',branchHelp:'АБО падзяляе альтэрнатывы; унутры кожнай умовы спалучаюцца. Выключэнне азначае «няма такой пазнакі ў каталогу», а не даказаную адсутнасць уласцівасці.',newTitle:'Назва падборкі',searchHelp:'Стылі, тэмы з крыніцамі, выканаўцы і назвы на EN / BE / RU. АБО — альтэрнатывы, НЕ — выключэнне пазнак каталога. Назва ў двукоссі шукаецца літаральна. Гэта структураваны пошук, не ІІ па ўсім інтэрнэце і не аналіз аўдыя.',feedbackLink:'Праверыць гэтае заданне',private:'Прыватны працоўны прататып · толькі на гэтым камп’ютары',libraryIntro:'Збірай асобныя падборкі, змяняй парадак і перанось іх у іншы браўзер праз экспарт. Нічога не загружаецца на сервер.',storageNote:'Захавана толькі ў гэтым браўзеры. JSON аднаўляе падборку ў іншым браўзеры; HTML і тэкст — копіі для чытання.'}
};
let current,limit=24,lastSearch='',pendingImport=null,playerLauncher;
const localText=(value,lang)=>typeof value==='string'?value:value?.[lang]||value?.en||'';
const btn=(label,action,extra='')=>`<button type="button" class="button secondary" data-experience="${action}" ${extra}>${e(label)}</button>`;
function makeCollection(title,ids=[]){const c=current; c.persist();const added=addCollection(c.library,title,ids);if(!added){c.toast(c.t.importError);return false;}c.state.ids=added.ids;c.state.title=added.title;c.persist();c.go('collection');return true;}
function dialog(title,body){const d=document.createElement('dialog');d.className='add-dialog experience-dialog';d.innerHTML=`<button type="button" class="icon-button dialog-close" data-experience="close-dialog" aria-label="${current.t.close}">×</button><h2 id="experience-heading">${e(title)}</h2>${body}`;d.setAttribute('aria-labelledby','experience-heading');const previous=document.activeElement;document.body.append(d);d.addEventListener('close',()=>{d.remove();previous?.focus();});d.showModal();return d;}
function openPlayer(record,queueOrigin){
 const c=current,p=playerFor(record);if(!safeUrl(record.listenUrl))return;
 const dock=document.querySelector('#listening-dock');dock.hidden=false;dock.className='listening-dock';dock.setAttribute('aria-label',c.t.playerTitle);
 dock.innerHTML=`<div class="dock-heading"><div><small>${e(p?.provider||record.listenLabel)} · ${e(c.t.playerTitle)}</small><h2 tabindex="-1">${e(record.artist)} — ${e(record.title)}</h2></div>${btn('×','close-player',`aria-label="${e(c.t.closePlayer)}"`)}</div>${p?`<div class="player-consent"><p>${e(c.t.playerPrivacy)}</p>${btn(c.t.loadPlayer,'load-player',`data-id="${e(record.id)}"`)}</div>`:''}<p class="scope-note">${e(c.t.playerFallback)} <a class="text-link" href="${e(safeUrl(record.listenUrl))}" target="_blank" rel="noopener noreferrer">${e(c.t.listen)} ${e(record.listenLabel)} ↗</a></p>`;
 if(p?.preview){const notes={en:'Apple Music provides a short preview. Full playback may require an account and subscription.',ru:'Apple Music даёт короткий фрагмент. Для полной записи могут потребоваться аккаунт и подписка.',be:'Apple Music дае кароткі фрагмент. Для поўнага запісу могуць спатрэбіцца акаўнт і падпіска.'};dock.querySelector('.player-consent').insertAdjacentHTML('beforebegin',`<p class="scope-note">${e(notes[c.lang])}</p>`);}
 decorateQueue(record,false,queueOrigin);(dock.querySelector('[data-experience="load-player"]')||dock.querySelector('h2')).focus({preventScroll:true});
}
function baseFor(c){let base=c.records.filter(r=>c.view.scope==='personal'?r.personal:c.view.scope==='leads'?!r.personal&&!r.listenUrl:!r.personal&&r.listenUrl);if(c.view.path!==null)return null;return base;}
function database(c){const rs=c.catalog;const counts=[[rs.length,c.t.recordings],[new Set(rs.map(r=>r.workId||r.id)).size,c.t.works],[rs.filter(r=>r.language==='be').length,c.t.belarusian],[rs.filter(r=>r.listenUrl).length,c.t.platformLinks]];document.querySelector('main').innerHTML=`<section class="shell guide"><p class="eyebrow">${e(c.t.database)}</p><h1 tabindex="-1">${e(c.t.databaseTitle)}</h1><p class="intro">${e(c.t.databaseIntro)}</p><div class="catalog-stats">${counts.map(([n,label])=>`<div><strong>${n}</strong><span>${e(label)}</span></div>`).join('')}</div>${btn(c.t.catalogExport,'catalog-export')}<p class="scope-note">${e(c.t.catalogHelp)}</p><div class="catalog-table-wrap"><table class="catalog-table"><caption>${e(c.t.database)}</caption><thead><tr><th>${e(c.t.tableTrack)}</th><th>${e(c.t.language)}</th><th>${e(c.t.tableSource)}</th></tr></thead><tbody>${rs.map(r=>`<tr><td><a href="#track/${e(r.id)}" data-route="track/${e(r.id)}"><strong>${e(r.title)}</strong><br>${e(r.artist)} · ${r.year||'—'}</a></td><td>${e(c.t[r.language]||c.t.unknown)}</td><td><a href="${e(safeUrl(r.sourceUrl||r.listenUrl))}" target="_blank" rel="noopener noreferrer">${e(r.sourceName||r.listenLabel)} ↗</a></td></tr>`).join('')}</tbody></table></div></section>`;}
export function enhanceExperience(c){current=c;c.openPlayer=openPlayer;enhanceSemantic(c);
 const brand=document.querySelector('.brand');if(brand){brand.setAttribute('aria-label','Unmute · '+c.t.navDiscover);brand.innerHTML='<img class="brand-design" src="./assets/cutout-5-e9615d46c666.webp" alt="Unmute · music, memory, connection" width="217" height="59"><img class="brand-design-icon" src="./assets/cutout-6-ae5c10894720.webp" alt="" width="53" height="54">';}
 const heroArt=document.querySelector('.hero-record');if(heroArt)heroArt.innerHTML='<img src="./assets/cutout-18-9f8d234c56b0.webp" alt="" width="458" height="333">';
 const footer=document.querySelector('.footer-links');footer?.insertAdjacentHTML('afterbegin',`<a href="#data" data-route="data">${e(c.t.database)} ↗</a>`);
 const nav=document.querySelector('nav');nav?.insertAdjacentHTML('beforeend',`<a href="#data" data-route="data" ${c.view.route==='data'?'aria-current="page"':''}>${e(c.t.database)}</a>`);
 if(c.view.route==='data'){database(c);document.querySelector('.catalog-table th:nth-child(2)').textContent=c.t.languageFilter;document.title='Unmute · '+c.t.database+' — listening pilot';enhanceWorkflows(c);return;}
 if(c.view.route==='study'){
   enhanceStudy(c);
   const memory=document.querySelector('#task option[value="memory"]');if(memory)memory.disabled=true;
   document.querySelector('#study-form').insertAdjacentHTML('beforeend',btn(c.lang==='ru'?'Скачать отзывы по всем моим заданиям':c.lang==='be'?'Спампаваць водгукі па ўсіх маіх заданнях':'Export all my task notes','study-session'));
 }
 document.querySelectorAll('.music-card,.collection-list li,.detail-actions').forEach(el=>{if(el.closest('.semantic-candidate'))return;const id=el.querySelector('[data-action="save"],[data-action="remove"]')?.dataset.id;const r=c.byId(id);if(r&&playerFor(r)){const destination=el.querySelector('.card-actions')||el;destination.insertAdjacentHTML('beforeend',btn('▷ '+c.t.playHere,'player',`data-id="${e(id)}"`));}});
 if(c.view.route==='collection'){
   const toolbar=`<div class="library-toolbar"><label>${e(c.t.collections)}<select id="collection-switch">${c.library.collections.map(x=>`<option value="${e(x.id)}" ${x.id===c.library.active?'selected':''}>${e(x.title||c.t.untitled)} · ${x.ids.length}</option>`).join('')}</select></label>${btn('+ '+c.t.newCollection,'new-collection')}${btn(c.t.importCollection,'import')}</div>`;
   document.querySelector('.collection-layout').insertAdjacentHTML('beforebegin',toolbar);
   document.querySelector('.share-panel').insertAdjacentHTML('beforeend',btn(c.t.portable,'portable',c.selected.length?'':'disabled'));
 }
 if(c.view.route==='discover'){
   const help=document.querySelector('.search-form>.scope-note');if(help){const details=document.createElement('details');details.className='search-how';const label=c.lang==='ru'?'Как устроен поиск · только по этому каталогу':c.lang==='be'?'Як працуе пошук · толькі па гэтым каталогу':'How search works · this catalogue only';details.innerHTML=`<summary>${e(label)}</summary><p>${e(c.t.searchHelp)}</p>`;help.replaceWith(details);}
   const fingerprint=JSON.stringify(c.view);if(fingerprint!==lastSearch){limit=24;lastSearch=fingerprint;}
   const grid=document.querySelector('.workspace > .music-grid');if(grid&&!c.pagination?.incremental){[...grid.children].forEach((el,i)=>{el.hidden=i>=limit;});if(grid.children.length>limit)grid.insertAdjacentHTML('afterend',`<div class="more-results">${btn(c.t.loadMore,'more')}<span>${Math.min(limit,grid.children.length)} / ${grid.children.length} ${e(c.t.shown)}</span></div>`);}
   const base=baseFor(c);if(base){const result=search(base,c.view.q,c.view);c.searchResult=result;
     if(result.matches.length)document.querySelector('.results-meta').insertAdjacentHTML('beforeend',btn(c.t.saveResults+(result.matches.length>100?' · 100 / '+result.matches.length:''),'save-results'));
     if(result.suggestions?.length)document.querySelector('.results-meta').insertAdjacentHTML('afterend',`<div class="query-readout"><strong>${e(c.t.suggestions)}</strong>${result.suggestions.map(s=>btn(s.label,'suggestion',`data-query="${e(s.query)}"`)).join('')}</div>`);
     if(result.intent.alternatives?.length||result.intent.excluded?.length)document.querySelector('.query-readout')?.insertAdjacentHTML('beforeend',`<span>${e(c.t.branchHelp)}</span>`);
     if(result.intent.diagnostics?.length){const messages={en:'The query includes unsupported lyric recall or conflicting conditions. No result is invented. Try one title, language or date range.',ru:'В запросе есть поиск по строке песни, который ещё не подключён, либо противоречивые условия. Мы не выдумываем ответ: попробуй одно название, язык или диапазон дат.',be:'У запыце ёсць пошук па радку песні, які яшчэ не падключаны, або супярэчлівыя ўмовы. Мы не выдумляем адказ: паспрабуй адну назву, мову ці дыяпазон дат.'};document.querySelector('.results-meta').insertAdjacentHTML('beforebegin',`<p class="query-readout" role="status">${e(messages[c.lang])}</p>`);}
     document.querySelectorAll('.workspace > .music-grid .music-card').forEach(el=>{const id=el.querySelector('[data-action="save"]')?.dataset.id;const reasons=result.explanations?.[id];if(!c.view.q||!reasons?.length)return;el.querySelector('.card-body').insertAdjacentHTML('beforeend',`<details class="match-evidence"><summary>${e(c.t.matchWhy)}</summary>${reasons.map(r=>`<p><strong>${e(c.t[r.value]||r.value)}</strong> · ${e(localText(r.basis,c.lang))}${r.sourceUrl?` <a href="${e(safeUrl(r.sourceUrl))}" target="_blank" rel="noopener noreferrer">↗</a>`:''}</p>`).join('')}</details>`);});
   }
 }
 enhanceWorkflows(c);
}
document.addEventListener('change',event=>{if(event.target.id!=='collection-switch')return;const c=current;c.persist();const chosen=c.library.collections.find(x=>x.id===event.target.value);if(!chosen)return;c.library.active=chosen.id;c.state.ids=chosen.ids.filter(c.byId);c.state.title=chosen.title;c.persist();c.render();document.querySelector('#collection-switch')?.focus({preventScroll:true});});
document.addEventListener('click',event=>{const b=event.target.closest('[data-experience]');if(!b)return;const c=current,action=b.dataset.experience;
 if(action==='new-collection')dialog(c.t.newCollection,`<form id="new-collection-form"><label>${e(c.t.newTitle)}<input name="title" required maxlength="120"></label><button class="button primary" type="submit">${e(c.t.newCollection)}</button></form>`);
 if(action==='close-dialog')b.closest('dialog').close();
 if(action==='portable')c.download(exportCollection(c.state.title,c.selected),'unmute-collection.json','application/json');
 if(action==='import'){pendingImport=null;dialog(c.t.importCollection,`<p>${e(c.t.importHelp)}</p><form id="collection-import-form"><label>${e(c.t.pasteJSON)}<textarea name="json" rows="8" required maxlength="1000000" spellcheck="false"></textarea></label><p id="import-status" role="status"></p><button class="button primary" type="submit">${e(c.t.importAction)}</button></form><div id="import-preview"></div>`);}
 if(action==='confirm-import'&&pendingImport){if(c.library.collections.length>=30||c.state.personal.length+pendingImport.personal.length>100){c.toast(c.t.importError);return;}const value=pendingImport;pendingImport=null;c.state.personal.push(...value.personal);b.closest('dialog').close();if(makeCollection(value.title,value.records.map(r=>r.id)))c.toast(c.state.storageOK?c.t.importSuccess:c.t.storageWarning);}
 if(action==='save-results'){const ids=c.searchResult.matches.slice(0,100).map(r=>r.id);makeCollection(c.view.q||c.t.untitled,ids);}
 if(action==='suggestion')c.go('discover',{q:b.dataset.query,path:''},false);
 if(action==='more'){const scroll=window.scrollY;limit+=24;c.render();window.scrollTo({top:scroll,behavior:'instant'});document.querySelector('.workspace > .music-grid .music-card:nth-child('+Math.max(1,limit-23)+') a')?.focus({preventScroll:true});}
 if(action==='player'){playerLauncher=b;const r=c.byId(b.dataset.id);openPlayer(r,b.dataset.queue);}
 if(action==='close-player'){const dock=document.querySelector('#listening-dock');dock.replaceChildren();dock.hidden=true;(playerLauncher?.isConnected?playerLauncher:document.querySelector('main h1'))?.focus({preventScroll:true});}
 if(action==='load-player'){const r=c.byId(b.dataset.id),p=playerFor(r);if(!p)return;const frame=document.createElement('iframe');frame.src=p.url;frame.title=p.provider+' · '+r.artist+' — '+r.title;frame.className='official-player '+p.shape;frame.allow='encrypted-media; fullscreen';frame.referrerPolicy=p.provider==='YouTube'?'strict-origin-when-cross-origin':'no-referrer';frame.setAttribute('sandbox','allow-scripts allow-same-origin allow-popups allow-presentation');b.closest('.player-consent').replaceWith(frame);frame.focus({preventScroll:true});}
 if(action==='catalog-export')c.download(JSON.stringify({schema:'unmute.catalogue/1',records:c.catalog.map(r=>metadataPassport(r,c.catalog))},null,2),'unmute-catalogue-metadata.json','application/json');
 if(action==='study-session'){const code=document.querySelector('#study-form [name="code"]').value.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40);if(!code||!readStudyHistory(c.storage,code).length){c.toast(c.t.studyError);return;}c.download(studyHistoryExport(c.storage,code),'unmute-session-'+code+'.json','application/json');}
});
document.addEventListener('submit',event=>{const c=current;if(event.target.id==='new-collection-form'){event.preventDefault();const title=new FormData(event.target).get('title');event.target.closest('dialog').close();makeCollection(title);}
 if(event.target.id==='search-form')queueMicrotask(()=>document.querySelector('.workspace h2')?.focus({preventScroll:true}));
 if(event.target.id==='collection-import-form'){event.preventDefault();try{pendingImport=parseCollection(new FormData(event.target).get('json'),c.catalog);if(c.library.collections.length>=30||c.state.personal.length+pendingImport.personal.length>100)throw Error('full');document.querySelector('#import-status').textContent='';document.querySelector('#import-preview').innerHTML=`<h3>${e(pendingImport.title||c.t.untitled)}</h3><p>${pendingImport.records.length} ${e(c.t.recordings)} · ${pendingImport.personal.length} ${e(c.t.personalBadge)}</p>${btn(c.t.confirmImport,'confirm-import')}`;}catch{pendingImport=null;document.querySelector('#import-status').textContent=c.t.importError;document.querySelector('#import-preview').replaceChildren();}}
});
