import {escapeHTML as e} from './core.js';
import {catalogueCoverage} from './workflows-core.js';
import {countArtistIdentities} from './artist-identity.js';
export const pilotCopy={
 en:{private:'Listening pilot · growing catalogue · feedback welcome',title:'Your music. Your way of finding it.',intro:'Think of Belarusian-language music you would genuinely like to find. Try Unmute in your own way. We are testing the product, not your knowledge.',notice:'This is a working pilot, not the whole Belarusian music archive. A missing result may reveal a catalogue gap or a search problem. Tell us which request did not work — there is no preferred answer.',start:'Start with my own search',feedback:'Leave feedback after trying',privacy:'Privacy & local AI',optional:'Need a starting point? Optional examples',code:'Participant code',skip:'You can skip any question or stop at any time. No account, camera or microphone is needed. Please avoid personal or sensitive information.',goal:'After trying: what did you find, what got in the way, and would you return?',privacyTitle:'Your search stays with you.',privacyText:'Search text, filters and participant codes stay in the part of the address after #. They are not sent to the website host, but may appear in your browser history or a link you share. Collections and feedback are saved only in this browser until you explicitly export and share them.',hosting:'GitHub Pages serves the website and may retain ordinary access information such as IP addresses. Unmute adds no analytics or automatic research-data collection. Opening a source, loading its player, or enabling source covers sends requests to that provider under its own policies. Cover loading is a separate, optional browser preference; it is off until chosen.',model:'Meaning search optionally downloads a public AI model to your browser. The model compares catalogue descriptions, not the audio, and does not generate new facts or lyrics. Its download size and device requirements are shown before loading. Exact search works without it.',scope:"This public listening pilot is linked from Research and can be opened without an invitation or password. It asks search engines not to index it; noindex is not access control or a confidentiality guarantee. The wider Research site has not been replaced.",back:'Back to listening',count:(c)=>`${c.listening} listening links · ${c.belarusian} labelled Belarusian · ${c.artists} artists in the catalogue`,taskNote:'Try your own listening need first. This form is for your observations afterward, including unsuccessful searches. Select the actual test round; repeat tests remain separate.'},
 ru:{private:'Слушательский пилот · каталог растёт · ждём обратную связь',title:'Твоя музыка. Твой способ её найти.',intro:'Подумай, какую белорусскоязычную музыку ты действительно хочешь найти. Попробуй Unmute своим способом. Мы проверяем продукт, а не твои знания.',notice:'Это рабочий пилот, не весь архив белорусской музыки. Пустой результат может означать пробел в каталоге или проблему поиска. Расскажи, какой запрос не сработал: нужного ответа нет.',start:'Начать со своего запроса',feedback:'Оставить отзыв после проверки',privacy:'Приватность и локальный ИИ',optional:'Нужна отправная точка? Необязательные примеры',code:'Код участника',skip:'Можно пропустить любой вопрос или остановиться. Аккаунт, камера и микрофон не нужны. Не вводи личные или чувствительные сведения.',goal:'После проверки: что нашлось, что помешало и вернулся бы ты сюда?',privacyTitle:'Твой запрос остаётся у тебя.',privacyText:'Текст поиска, фильтры и код участника находятся в части адреса после #. Они не отправляются хостингу, но могут остаться в истории браузера или в ссылке, которой ты поделишься. Подборки и отзывы сохраняются только в этом браузере, пока ты сам не экспортируешь и не передашь их.',hosting:'GitHub Pages размещает сайт и может сохранять обычные данные доступа, например IP-адрес. Unmute не добавляет аналитику и не собирает исследовательские данные автоматически. Переход к источнику, загрузка плеера или включение обложек отправляют запросы соответствующему сервису по его правилам. Обложки — отдельная настройка браузера; до выбора она выключена.',model:'Поиск по смыслу по желанию загружает открытую ИИ-модель в браузер. Она сравнивает описания каталога, не само аудио, и не создаёт новые факты или тексты песен. Размер загрузки и требования к устройству показаны до запуска. Точный поиск работает без неё.',scope:"Этот открытый слушательский пилот доступен по ссылке из Research без приглашения и пароля. Поисковикам указано не индексировать его; noindex не ограничивает доступ и не гарантирует конфиденциальность. Основной сайт Research не заменён.",back:'Вернуться к музыке',count:(c)=>`${c.listening} ссылок на прослушивание · ${c.belarusian} с меткой белорусского языка · ${c.artists} исполнителей в каталоге`,taskNote:'Сначала попробуй свою реальную задачу. Эта форма — для наблюдений после проверки, включая неудачные поиски. Выбери реальный раунд; повторные тесты сохраняются отдельно.'},
 be:{private:'Слухацкі пілот · каталог расце · чакаем водгукаў',title:'Твая музыка. Твой спосаб яе знайсці.',intro:'Падумай, якую беларускамоўную музыку ты сапраўды хочаш знайсці. Паспрабуй Unmute сваім спосабам. Мы правяраем прадукт, а не твае веды.',notice:'Гэта працоўны пілот, не ўвесь архіў беларускай музыкі. Пусты вынік можа азначаць прабел у каталогу або праблему пошуку. Раскажы, які запыт не спрацаваў: патрэбнага адказу няма.',start:'Пачаць са свайго запыту',feedback:'Пакінуць водгук пасля праверкі',privacy:'Прыватнасць і лакальны ІІ',optional:'Патрэбная адпраўная кропка? Неабавязковыя прыклады',code:'Код удзельніка',skip:'Можна прапусціць любое пытанне або спыніцца. Акаўнт, камера і мікрафон не патрэбныя. Не ўводзь асабістыя або адчувальныя звесткі.',goal:'Пасля праверкі: што знайшлося, што перашкодзіла і ці вярнуўся б ты сюды?',privacyTitle:'Твой запыт застаецца ў цябе.',privacyText:'Тэкст пошуку, фільтры і код удзельніка знаходзяцца ў частцы адраса пасля #. Яны не адпраўляюцца хостынгу, але могуць застацца ў гісторыі браўзера або ў спасылцы, якой ты падзелішся. Падборкі і водгукі захоўваюцца толькі ў гэтым браўзеры, пакуль ты сам не экспартуеш і не перадасі іх.',hosting:'GitHub Pages размяшчае сайт і можа захоўваць звычайныя даныя доступу, напрыклад IP-адрас. Unmute не дадае аналітыку і не збірае даследчыя даныя аўтаматычна. Пераход да крыніцы, загрузка плэера або ўключэнне вокладак адпраўляюць запыты адпаведнаму сэрвісу паводле яго правілаў. Вокладкі — асобная настройка браўзера; да выбару яна выключаная.',model:'Пошук паводле сэнсу па жаданні загружае адкрытую ІІ-мадэль у браўзер. Яна параўноўвае апісанні каталога, не само аўдыя, і не стварае новыя факты або тэксты песень. Памер загрузкі і патрабаванні да прылады паказаныя да запуску. Дакладны пошук працуе без яе.',scope:"Гэты адкрыты слухацкі пілот даступны па спасылцы з Research без запрашэння і пароля. Пошукавікам указана не індэксаваць яго; noindex не абмяжоўвае доступ і не гарантуе канфідэнцыяльнасць. Асноўны сайт Research не заменены.",back:'Вярнуцца да музыкі',count:(c)=>`${c.listening} спасылак на праслухоўванне · ${c.belarusian} з пазнакай беларускай мовы · ${c.artists} выканаўцаў у каталогу`,taskNote:'Спачатку паспрабуй сваю рэальную задачу. Гэтая форма — для назіранняў пасля праверкі, у тым ліку няўдалых пошукаў. Выберы сапраўдны раўнд; паўторныя тэсты захоўваюцца асобна.'}
};
export function enhancePilot(c){
 const t=pilotCopy[c.lang]||pilotCopy.en,coverage=catalogueCoverage(c.catalog);
 coverage.artists=countArtistIdentities(c.catalog);
 document.querySelector('.footer-links')?.insertAdjacentHTML('beforeend',`<a href="${c.url('privacy')}" data-route="privacy">${e(t.privacy)}</a>`);
 if(c.view.route==='discover'){
  const stop=document.querySelector('[data-semantic="stop"]');if(stop)document.querySelector('.search-how')?.append(stop);
  const examples=document.querySelector('.examples');
  if(examples){const wrapper=document.createElement('details');wrapper.className='optional-examples';wrapper.innerHTML=`<summary>${e(t.optional)}</summary>`;examples.before(wrapper);wrapper.append(examples);}
  document.querySelector('.hero')?.insertAdjacentHTML('afterend',`<aside class="shell pilot-boundary"><p>${e(t.notice)}</p><a href="${c.url('study')}" data-route="study">${e(t.feedback)} ↗</a></aside>`);
 }
 if(!['participate','privacy'].includes(c.view.route))return;
 const main=document.querySelector('main');
 main.innerHTML=c.view.route==='participate'?`<section class="shell guide participant-entry"><p class="eyebrow">Unmute · ${e(t.private)}</p><h1 tabindex="-1">${e(t.title)}</h1><p class="intro">${e(t.intro)}</p><p class="pilot-coverage">${e(t.count(coverage))}</p><p>${e(t.notice)}</p><p>${e(t.skip)}</p><div class="detail-actions"><a class="button primary" href="${c.url('discover',{q:'',path:'',genre:'',topic:'',type:'',decade:''})}" data-route="discover" data-own-search>${e(t.start)} →</a><a class="text-link" href="${c.url('privacy')}" data-route="privacy">${e(t.privacy)}</a></div><hr><h2>${e(t.goal)}</h2><a class="text-link" href="${c.url('study')}" data-route="study">${e(t.feedback)} →</a></section>`:`<section class="shell guide participant-entry"><p class="eyebrow">Unmute · ${e(t.privacy)}</p><h1 tabindex="-1">${e(t.privacyTitle)}</h1><p class="intro">${e(t.privacyText)}</p><p>${e(t.hosting)}</p><p>${e(t.model)}</p><p>${e(t.scope)}</p><a class="button primary" href="${c.url('discover')}" data-route="discover">${e(t.back)} →</a></section>`;
}
