// Capability-aligned copy for the private listening prototype.
// Merge after i18n, missionCopy and experienceCopy. No claim of completed user research.
export const productCopy = {
  en: {
    researchReturn:"Back to Research",
    artNote:"Source covers are optional. Where no reviewed cover is available, or an image cannot load, the graphic is Unmute interface artwork — not an official release cover.",
    artworkSessionOnly:"Cover preference applies for this session; this browser could not save it.",
    artworkHeading:"Cover art, with a choice.",
    artworkGuide:"Use “Show source covers” above the recordings to enable reviewed cover images from Bandcamp and Apple. This preference is separate from loading a player and is saved only in this browser. Images stay on their source services, which receive your IP address and may use cookies; Unmute does not send your search or collection. Album and compilation covers are labelled as such. Unavailable covers keep the Unmute graphic. Public artwork metadata is not a grant of reuse rights.",
    navCollection:'My collections',
    private:'Private working prototype · on this computer',
    examples:['lullaby','protest 2010-2020','folk OR electronic'],
    searchHelp:'Search this catalogue by documented style, theme, artist, title or year. AND combines conditions, OR offers alternatives, and NOT excludes catalogue labels. Try “folk OR electronic”. Put a title in quotation marks to keep its words literal. Remembered lyrics and audio similarity are not searchable yet.',
    operatorWarning:'This expression is incomplete or uses unsupported syntax. AND, OR and NOT work; parentheses and repeated negation do not. Put a condition after each operator, or simplify the query.',
    branchHelp:'AND combines conditions within each alternative; OR separates alternatives. Sidebar filters apply to every alternative. NOT excludes matching catalogue labels — it does not prove that an undocumented property is absent.',
    exactTitle:'Literal title or artist lookup, not lyric recall. Words in a recognised title do not become style or topic filters.',
    unmatched:'Matching these words in titles, artist names and recorded aliases:',
    noIntent:'Browse the collection, or search by a known style, source-backed topic, artist, title or release year.',
    empty:'No match for all these conditions.',
    emptyHelp:'This local catalogue may not yet cover your request, or a label may still be unverified. Check the interpreted conditions, try a title or change one filter. An empty result does not mean the music does not exist. We do not silently change the language or invent a result.',
    candidateTitle:'Related recordings — not full matches',
    candidateNote:'These recordings relate to sleep or have a relevant title, but do not satisfy every condition above. Some have a documented lullaby function; that alone does not establish a soft sound. They are suggestions to investigate, not counted matches.',
    scopeHelp:'Open the original recording page, or choose “Listen here” where an official player is available. The player connects only after you press “Load official player”. Internet access is needed; region, platform rules or an account may affect playback. Unmute does not host the audio.',
    checked:'Source pages were reviewed on 11–12 September 2026. Page identity was checked; playback, regional access and correspondence between published lyrics and audio are not guaranteed.',
    countNote:'catalogue records, including separate versions and source-only leads — not a complete archive or a count of unique songs.',
    libraryIntro:'Make separate named collections, arrange their songs and keep the source links. Export a collection as JSON to restore it in another copy of Unmute; HTML and text are reading copies. No account or upload is required.',
    storageNote:'Saved only in this browser. Export each collection as JSON before clearing browser data or moving to another browser. Import creates a new collection; HTML and text cannot restore it. No audio files are stored.',
    playerPrivacy:'“Load official player” connects to the music platform: it receives your IP address and may use cookies. Unmute does not send your query or collection. No player loads before this choice. Source covers use a separate saved preference.',
    guideTitle:'Find a song.\nKeep the connection.',
    guideIntro:'A working, private listening prototype within Unmute: 139 catalogue records, including 129 direct recording links and 10 source-only leads. It includes 19 short traditional lullaby recordings from Tradycyja, with individual performer credits. The public research site has not been replaced.',
    steps:[
      ['Find something for your moment','Try “lullaby”, “protest 2010-2020” or “folk OR electronic”. The search combines documented labels, titles and names in this catalogue — not everything on the internet. Open “Why this matched” and the recording notes to inspect the evidence.'],
      ['Listen on your terms','Open the source recording, or use “Listen here” and explicitly load its official player. No embedded player connects in the background. A source link stays available if an embed cannot play; access depends on the provider and your region.'],
      ['Make it a collection','Save songs to a named collection, reorder them or create another collection for a different purpose. Export JSON for import into another copy of Unmute, or share an HTML/text reading copy. Links and context travel together; audio is not copied.'],
    ],
    bounds:[
      'Search runs locally over a curated index. It supports known EN, BE and RU terms with AND / OR / NOT, not arbitrary conversation or a live all-internet AI search. Parentheses are not supported.',
      'A quoted title is a literal identity lookup, not a remembered lyric. Lyric recall, measured tempo/energy and audio-similarity matching are still future work.',
      'A documented lullaby function, a lyrical theme and a sound description are different things. Neither a title nor an artist’s nationality proves language, mood, rights or authenticity.',
      'Archive leads are kept separate from direct listening links. A working webpage is not proof of successful audio playback. Official players are optional and load only with your action.',
      'Collections and feedback stay in this browser; they are not an online account or shared database. Export JSON to move a collection. A localhost link will not open this prototype on someone else’s computer.',
      'Sources and editorial interpretations remain visible. We do not host music or lyric texts, grant reuse rights, or claim that this prototype has already passed representative-user evaluation.',
    ],
    tryText:'Search for a lullaby, open its source and inspect why it has that label. Then make a three-song collection for a purpose of your own. Could you find, listen and save without help? Tell us what failed as well as what worked.',
    taskNote:'The lullaby, missing-result and collection tasks can be tried now. The remembered-line task is disabled until a permissioned text index exists. Agree with the moderator which task you are doing; any timing is recorded separately, with your consent.',
    tasks:['Find a source-classified lullaby and check the evidence','Remembered lyric — not enabled yet','Try a query the catalogue does not cover','Make a named collection and inspect linked versions',
      'Describe the music you want, try local AI if needed, and check one candidate against its source',
      'Compare documented versions of the same song',
      'Export a collection as JSON and import it as a separate collection',
      'Suggest a source-backed correction without changing the catalogue'],
    feedbackDraft:'Different tasks are saved as separate notes under your participant code. Saving the same code and task updates that note. Export all task notes to keep or share a session; nothing is sent automatically.',
    savedFeedback:'Task note saved on this computer — not sent. You can export this note or all saved tasks for your participant code.',
    roadmapIntro:'One mission, with a working listener prototype and clearly marked next steps. These are product directions, not completed capabilities or results from a user study.',
    directionNotes:[
      'Now: a source-linked Belarusian-language index with structured search. Next: broader verified coverage, better topic labels and a permissioned remembered-lyric index.',
      'Now: short source-linked explanations and some explicitly related versions. Next: volunteer-reviewed translation and richer cultural context.',
      'Later: short, permissioned language examples with reviewed pronunciation and explanations.',
      'A separate historical context mode can include other languages. Keep historic geography and musical evidence distinct.',
      'Later: combine music, language and contextual teaching materials; test with actual learners.',
      'Later: a separate consent, access and privacy workflow for family recordings and oral history.',
      'Now: multiple named collections, ordering and JSON import/export. Broaden evidence-backed choices for family, travel, dance and other listening needs.',
      'Later: batch intake and duplicate candidates, with clear distinctions between a work, a recording and an exact file.',
      'Keep Archive Passport and the restoration/version lab separate from everyday listening. A source link is not an audio fingerprint.',
      'Now: inspect sources and export local feedback. Later: reviewed contributions and a conversational assistant that can route to the right tool.',
    ],
    corpusText:'The current 139 records are a starting collection, not the coverage goal. Next, fill gaps by listening task: more independently sourced performers, eras, regional traditions, dance versions and music about everyday life. Check each recording’s language and links, separate publisher labels from editorial readings, and give every advertised task several useful choices across artists. Keep genuine no-answer cases; do not inflate the count with near-duplicates or unverified labels.',
    roadmapBoundary:'Not built yet: continuous web monitoring, public artist submissions, volunteer accounts, remembered-lyric retrieval, measured tempo/energy, automatic audio matching or an AI chat assistant. The prototype remains private and has not replaced the live research site. Human evaluation is still to be conducted.',
    feedback:'A working feature is not proof of usefulness. Your actual choices, failed searches and difficulties will guide the next iteration; no positive result is assumed.',
    databaseIntro:'Inspect all 139 catalogue records, including direct listening links and source-only leads. A record is not necessarily a unique composition. Sources, language evidence and gaps remain visible; there is no popularity ranking or claim to cover the whole internet.',
    catalogHelp:'Exports editorial metadata and source links, not audio or lyrics. Linked work groups reflect documented relationships, not computed acoustic identity. Unknowns stay unknown.',
  },
  be: {
    researchReturn:"Вярнуцца да Research",
    artNote:"Вокладкі з крыніц уключаюцца па жаданні. Калі праверанай вокладкі няма або яна не загрузілася, паказана афармленне Unmute, а не афіцыйная вокладка рэлізу.",
    artworkSessionOnly:"Выбар вокладак дзейнічае ў гэтай сесіі; браўзер не змог яго захаваць.",
    artworkHeading:"Вокладкі — на твой выбар.",
    artworkGuide:"Кнопка «Паказаць вокладкі з крыніц» над запісамі ўключае правераныя выявы з Bandcamp і Apple. Гэтая настройка асобная ад загрузкі плэера і захоўваецца толькі ў гэтым браўзеры. Выявы застаюцца на сэрвісах-крыніцах: яны атрымліваюць IP-адрас і могуць выкарыстоўваць cookies; Unmute не перадае запыт або падборку. Вокладкі альбомаў і зборнікаў адпаведна пазначаныя. Калі вокладка недаступная, застаецца графіка Unmute. Публічныя метаданыя выявы не даюць права на яе паўторнае выкарыстанне.",
    navCollection:'Мае падборкі',
    private:'Прыватны працоўны прататып · на гэтым камп’ютары',
    examples:['калыханка','пратэст 2010-2020','фолк АБО электроніка'],
    searchHelp:'Шукай у гэтым каталогу паводле пацверджанага стылю, тэмы, выканаўцы, назвы ці года. І спалучае ўмовы, АБО прапануе альтэрнатывы, НЕ выключае пазнакі каталога. Напрыклад: «фолк АБО электроніка». Назву ў двукоссі шукаем літаральна. Пошук паводле згаданага радка ці падабенства аўдыя яшчэ не працуе.',
    operatorWarning:'Выраз няпоўны або мае непадтрыманы сінтаксіс. І, АБО і НЕ працуюць; дужкі і паўторнае адмаўленне — не. Дадай умову пасля кожнага аператара або спрасці запыт.',
    branchHelp:'І спалучае ўмовы ў межах аднаго варыянта; АБО падзяляе варыянты. Бакавыя фільтры дзейнічаюць для ўсіх варыянтаў. НЕ выключае адпаведныя пазнакі каталога, але не даказвае адсутнасць неапісанай уласцівасці.',
    exactTitle:'Літаральны пошук назвы ці выканаўцы, а не згаданага радка песні. Словы ў распазнанай назве не ператвараюцца ў фільтры стылю ці тэмы.',
    unmatched:'Гэтыя словы шукаем у назвах, імёнах выканаўцаў і захаваных варыянтах напісання:',
    noIntent:'Пагартай калекцыю або ўкажы вядомы стыль, тэму з крыніцай, выканаўцу, назву ці год рэлізу.',
    empty:'Няма супадзення з усімі гэтымі ўмовамі.',
    emptyHelp:'Магчыма, у лакальным каталогу яшчэ няма патрэбнай музыкі або яе пазнакі не правераныя. Паглядзі, як распазнаны ўмовы, паспрабуй назву ці змяні адзін фільтр. Пусты вынік не азначае, што такой музыкі не існуе. Мы не падмяняем мову і не выдумляем адказ.',
    candidateTitle:'Блізкія запісы — не поўныя супадзенні',
    candidateNote:'Гэтыя запісы звязаныя з тэмай сну або маюць блізкую назву, але не адпавядаюць усім умовам вышэй. Некаторыя маюць пацверджаную функцыю калыханкі; гэта само па сабе не пацвярджае мяккага гучання. Гэта падказкі для далейшага пошуку, не залічаныя вынікі.',
    scopeHelp:'Адкрый арыгінальную старонку запісу або выберы «Слухаць тут», калі ёсць афіцыйны плэер. Ён падключыцца толькі пасля націску «Загрузіць афіцыйны плэер». Патрэбны інтэрнэт; доступ можа залежаць ад краіны, правілаў платформы ці акаўнта. Unmute не захоўвае аўдыя.',
    checked:'Старонкі крыніц прагледжаныя 11–12 верасня 2026. Праверана адпаведнасць старонак запісам; прайграванне, доступ у розных краінах і адпаведнасць апублікаванага тэксту аўдыя не гарантаваныя.',
    countNote:'запісаў каталога, у тым ліку асобныя версіі і крыніцы без прамога аўдыя, — не поўны архіў і не колькасць унікальных песень.',
    libraryIntro:'Стварай асобныя падборкі з назвамі, змяняй парадак песень і захоўвай крыніцы. Экспартуй падборку ў JSON, каб аднавіць яе ў іншай копіі Unmute; HTML і тэкст — копіі для чытання. Рэгістрацыя і загрузка на сервер не патрэбныя.',
    storageNote:'Захавана толькі ў гэтым браўзеры. Экспартуй кожную падборку ў JSON перад ачысткай даных ці пераходам у іншы браўзер. Імпарт стварае новую падборку; HTML і тэкст яе не аднаўляюць. Аўдыяфайлы не захоўваюцца.',
    playerPrivacy:'Кнопка загрузкі падключыць музычную платформу: яна атрымае твой IP-адрас і можа выкарыстоўваць cookies. Unmute не перадае ёй запыт ці падборку. Да націскання плэер не загружаецца. Вокладкі выкарыстоўваюць асобную захаваную настройку.',
    guideTitle:'Знайдзі песню.\nЗахавай сувязь.',
    guideIntro:'Прыватны працоўны прататып Unmute для слухачоў: 139 запісаў каталога, сярод іх 129 прамых спасылак на запісы і 10 крыніц без пацверджанай спасылкі на аўдыя. Тут ёсць 19 кароткіх запісаў традыцыйных калыханак Tradycyja з імёнамі выканаўцаў. Публічны даследчы сайт не заменены.',
    steps:[
      ['Знайдзі музыку для свайго моманту','Паспрабуй «калыханка», «пратэст 2010-2020» або «фолк АБО электроніка». Пошук спалучае пацверджаныя пазнакі, назвы і імёны ў гэтым каталогу, а не ва ўсім інтэрнэце. Адкрый «Чаму знойдзена» і нататкі пра запіс, каб паглядзець на доказы.'],
      ['Слухай так, як табе зручна','Адкрый арыгінальны запіс або націсні «Слухаць тут» і асобна дазволь загрузку афіцыйнага плэера. Плэеры не падключаюцца ў фоне. Калі ўбудаваны плэер не працуе, застаецца спасылка на крыніцу; доступ залежыць ад платформы і краіны.'],
      ['Збяры сваю падборку','Захоўвай песні ў падборку з назвай, змяняй іх парадак або ствары яшчэ адну пад іншую задуму. Экспартуй JSON для імпарту ў іншую копію Unmute або падзяліся копіяй HTML ці тэкстам. Спасылкі і кантэкст захоўваюцца разам; аўдыя не капіруецца.'],
    ],
    bounds:[
      'Пошук працуе лакальна па рэдакцыйным каталогу. Ён распазнае вядомыя тэрміны EN, BE і RU з І / АБО / НЕ, але не вядзе адвольную размову і не шукае праз ШІ ва ўсім інтэрнэце. Дужкі не падтрымліваюцца.',
      'Назва ў двукоссі шукаецца літаральна, а не як згаданы радок песні. Пошук па тэкстах, вымярэнне тэмпу і энергічнасці, супастаўленне аўдыя — наступныя этапы.',
      'Пацверджаная функцыя калыханкі, тэма тэксту і апісанне гучання — розныя рэчы. Ні назва, ні нацыянальнасць артыста не даказваюць мову, настрой, правы ці сапраўднасць запісу.',
      'Архіўныя знаходкі аддзеленыя ад прамых спасылак на слуханне. Даступная старонка не даказвае, што аўдыя прайграваецца. Афіцыйныя плэеры неабавязковыя і загружаюцца толькі з твайго дзеяння.',
      'Падборкі і водгукі застаюцца ў гэтым браўзеры: гэта не анлайн-акаўнт і не агульная база. Для пераносу падборкі экспартуй JSON. Спасылка localhost не адкрые гэты прататып на чужым камп’ютары.',
      'Крыніцы і рэдактарскія тлумачэнні бачныя. Мы не захоўваем музыку ці тэксты песень, не выдаём дазволаў на іх выкарыстанне і не сцвярджаем, што прататып ужо прайшоў ацэнку з мэтавымі карыстальнікамі.',
    ],
    tryText:'Знайдзі калыханку, адкрый яе крыніцу і паглядзі, чым абгрунтаваная пазнака. Потым збяры тры песні пад сваю задуму. Ці атрымалася знайсці, паслухаць і захаваць без дапамогі? Раскажы і пра тое, што спрацавала, і пра цяжкасці.',
    taskNote:'Заданні пра калыханку, адсутны вынік і падборку ўжо можна выканаць. Заданне пра згаданы радок адключанае, пакуль няма дазволенага для пошуку корпуса тэкстаў. Узгадні з мадэратарам заданне; час ён запісвае асобна, з тваёй згоды.',
    tasks:['Знайсці калыханку з пацверджанай пазнакай і праверыць крыніцу','Згаданы радок песні — яшчэ не працуе','Праверыць запыт, якога каталог не ахоплівае','Стварыць падборку з назвай і прагледзець звязаныя версіі',
      'Апісаць жаданую музыку, пры патрэбе паспрабаваць лакальны ШІ і праверыць адзін варыянт па крыніцы',
      'Параўнаць дакументаваныя версіі адной песні',
      'Экспартаваць падборку ў JSON і імпартаваць яе як асобную падборку',
      'Прапанаваць праўку з крыніцай, не змяняючы каталог'],
    feedbackDraft:'Розныя заданні захоўваюцца асобнымі нататкамі пад тваім кодам удзельніка. Паўторнае захаванне таго самага кода і задання абнаўляе гэтую нататку. Экспартуй усе нататкі, каб захаваць сеанс або падзяліцца ім; аўтаматычна нічога не адпраўляецца.',
    savedFeedback:'Нататка пра заданне захаваная на гэтым камп’ютары, але не адпраўленая. Можна экспартаваць яе асобна або ўсе захаваныя заданні пад тваім кодам удзельніка.',
    roadmapIntro:'Адна місія, працоўны прататып для слухачоў і выразна пазначаныя наступныя крокі. Гэта кірункі развіцця, а не спіс гатовых магчымасцяў ці вынікі даследавання з карыстальнікамі.',
    directionNotes:[
      'Цяпер: беларускамоўны каталог з крыніцамі і структураваным пошукам. Далей: шырэйшы правераны ахоп, дакладнейшыя тэмы і дазволены корпус для пошуку па згаданым радку.',
      'Цяпер: кароткія тлумачэнні з крыніцамі і некаторыя яўна звязаныя версіі. Далей: пераклады з валанцёрскай праверкай і глыбейшы культурны кантэкст.',
      'Пазней: кароткія моўныя прыклады з дазволам на выкарыстанне, правераным вымаўленнем і тлумачэннямі.',
      'Асобны рэжым гістарычнага кантэксту можа ўключаць іншыя мовы. Гістарычную геаграфію і музычныя сведчанні трэба размяжоўваць.',
      'Пазней: спалучыць музыку, мову і культурныя матэрыялы; праверыць з тымі, хто сапраўды вучыцца.',
      'Пазней: асобны парадак згоды, доступу і абароны прыватнасці для сямейных запісаў і вуснай гісторыі.',
      'Цяпер: некалькі падборак з назвамі, парадак песень, імпарт і экспарт JSON. Пашыраць абгрунтаваны выбар для сям’і, падарожжаў, танцаў і іншых патрэбаў.',
      'Пазней: пакетнае даданне і пошук магчымых дубляў з выразным адрозненнем твора, запісу і канкрэтнага файла.',
      'Archive Passport і лабараторыя апрацоўкі застаюцца асобнымі ад штодзённага слухання. Спасылка на крыніцу — не адбітак аўдыя.',
      'Цяпер: прагляд крыніц і экспарт лакальных водгукаў. Далей: правераныя ўнёскі супольнасці і суразмоўца-памочнік, які накіруе да патрэбнага інструмента.',
    ],
    corpusText:'Цяперашнія 139 запісаў — пачатковая калекцыя, а не канчатковая мэта. Далей запаўняем прабелы паводле задач слухача: больш розных выканаўцаў з незалежнымі крыніцамі, эпох, рэгіянальных традыцый, танцавальных версій і песень пра штодзённае жыццё. Для кожнага запісу правяраем мову і спасылкі, адрозніваем пазнакі выдаўца ад рэдактарскага прачытання і даём некалькі карысных варыянтаў розных артыстаў для кожнага заяўленага задання. Захоўваем сумленныя выпадкі без адказу; не нарошчваем лічбы амаль дублямі ці неправеранымі пазнакамі.',
    roadmapBoundary:'Яшчэ не зробленыя: бесперапынны маніторынг інтэрнэту, публічны прыём музыкі ад артыстаў, акаўнты валанцёраў, пошук па згаданым радку, вымярэнне тэмпу і энергічнасці, аўтаматычнае супастаўленне аўдыя і ШІ-суразмоўца. Прататып застаецца прыватным і не замяняе публічны даследчы сайт. Ацэнку з людзьмі яшчэ трэба правесці.',
    feedback:'Працоўная функцыя яшчэ не даказвае карысці. Твой рэальны выбар, няўдалыя пошукі і цяжкасці вызначаць наступныя змены; станоўчы вынік не закладзены загадзя.',
    databaseIntro:'Паглядзі ўсе 139 запісаў каталога: прамыя спасылкі на слуханне і крыніцы без пацверджанага аўдыя. Запіс не абавязкова азначае асобны твор. Крыніцы, доказы мовы і прабелы бачныя; няма рэйтынгу папулярнасці ці абяцання ахапіць увесь інтэрнэт.',
    catalogHelp:'Экспартуе рэдактарскія метаданыя і спасылкі, а не аўдыя ці тэксты песень. Групы твораў паказваюць дакументаваныя сувязі, не вылічанае падабенства аўдыя. Невядомае застаецца невядомым.',
  },
  ru: {
    researchReturn:"Вернуться к Research",
    artNote:"Обложки из источников включаются по желанию. Если проверенной обложки нет или она не загрузилась, показано оформление Unmute, а не официальная обложка релиза.",
    artworkSessionOnly:"Выбор обложек действует в этой сессии; браузер не смог его сохранить.",
    artworkHeading:"Обложки — по твоему выбору.",
    artworkGuide:"Кнопка «Показать обложки из источников» над записями включает проверенные изображения с Bandcamp и Apple. Эта настройка отдельна от загрузки плеера и сохраняется только в этом браузере. Изображения остаются на сервисах-источниках: они получают IP-адрес и могут использовать cookies; Unmute не передаёт запрос или подборку. Обложки альбомов и сборников так и обозначены. Если обложка недоступна, остаётся графика Unmute. Публичные метаданные изображения не дают права на его повторное использование.",
    navCollection:'Мои подборки',
    private:'Частный рабочий прототип · на этом компьютере',
    examples:['колыбельная','протест 2010-2020','фолк ИЛИ электроника'],
    searchHelp:'Ищи в этом каталоге по документированному стилю, теме, исполнителю, названию или году. И объединяет условия, ИЛИ предлагает альтернативы, НЕ исключает метки каталога. Например: «фолк ИЛИ электроника». Название в кавычках ищется буквально. Поиск по запомнившейся строке или сходству аудио ещё не работает.',
    operatorWarning:'Выражение неполное или использует неподдерживаемый синтаксис. И, ИЛИ и НЕ работают; скобки и повторное отрицание — нет. Добавь условие после каждого оператора или упрости запрос.',
    branchHelp:'И объединяет условия внутри одного варианта; ИЛИ разделяет варианты. Боковые фильтры действуют для всех вариантов. НЕ исключает соответствующие метки каталога, но не доказывает отсутствие неописанного свойства.',
    exactTitle:'Буквальный поиск названия или исполнителя, не запомнившейся строки. Слова в распознанном названии не превращаются в фильтры стиля или темы.',
    unmatched:'Эти слова ищем в названиях, именах исполнителей и сохранённых вариантах написания:',
    noIntent:'Полистай коллекцию или укажи известный стиль, тему с источником, исполнителя, название либо год релиза.',
    empty:'Нет совпадения со всеми этими условиями.',
    emptyHelp:'Возможно, локальный каталог ещё не охватывает твой запрос или метки записи не проверены. Посмотри, как распознаны условия, попробуй название или измени один фильтр. Пустой результат не означает, что такой музыки не существует. Мы не подменяем язык и не выдумываем ответ.',
    candidateTitle:'Близкие записи — не полные совпадения',
    candidateNote:'Эти записи связаны с темой сна или имеют близкое название, но не отвечают всем условиям выше. У некоторых подтверждена функция колыбельной; сама по себе она не подтверждает мягкое звучание. Это подсказки для дальнейшего поиска, не засчитанные совпадения.',
    scopeHelp:'Открой оригинальную страницу записи или выбери «Слушать здесь», если есть официальный плеер. Он подключится только после нажатия «Загрузить официальный плеер». Нужен интернет; доступ может зависеть от страны, правил платформы или аккаунта. Unmute не хранит аудио.',
    checked:'Страницы источников просмотрены 11–12 сентября 2026. Проверено соответствие страниц записям; воспроизведение, доступ в разных странах и соответствие опубликованных текстов аудио не гарантированы.',
    countNote:'записей каталога, включая отдельные версии и источники без прямого аудио, — не полный архив и не количество уникальных песен.',
    libraryIntro:'Создавай отдельные подборки с названиями, меняй порядок песен и сохраняй источники. Экспортируй подборку в JSON для восстановления в другой копии Unmute; HTML и текст — копии для чтения. Регистрация и загрузка на сервер не нужны.',
    storageNote:'Сохранено только в этом браузере. Экспортируй каждую подборку в JSON до очистки данных или перехода в другой браузер. Импорт создаёт новую подборку; HTML и текст её не восстанавливают. Аудиофайлы не сохраняются.',
    playerPrivacy:'Кнопка загрузки подключит музыкальную платформу: она получит твой IP-адрес и может использовать cookies. Unmute не передаёт ей запрос и подборку. До нажатия плеер не загружается. Обложки используют отдельную сохранённую настройку.',
    guideTitle:'Найди песню.\nСохрани связь.',
    guideIntro:'Частный рабочий прототип Unmute для слушателей: 139 записей каталога, среди них 129 прямых ссылок на записи и 10 источников без подтверждённой ссылки на аудио. Здесь есть 19 коротких записей традиционных колыбельных Tradycyja с именами исполнителей. Публичный исследовательский сайт не заменён.',
    steps:[
      ['Найди музыку для своего момента','Попробуй «колыбельная», «протест 2010-2020» или «фолк ИЛИ электроника». Поиск объединяет документированные метки, названия и имена в этом каталоге, а не во всём интернете. Открой «Почему найдено» и заметки о записи, чтобы проверить основания.'],
      ['Слушай так, как тебе удобно','Открой оригинальную запись или нажми «Слушать здесь» и отдельно разреши загрузку официального плеера. Плееры не подключаются в фоне. Если встроенный плеер не работает, остаётся ссылка на источник; доступ зависит от платформы и страны.'],
      ['Собери свою подборку','Сохраняй песни в подборку с названием, меняй их порядок или создай ещё одну под другую задачу. Экспортируй JSON для импорта в другую копию Unmute или поделись HTML-копией либо текстом. Ссылки и контекст сохраняются вместе; аудио не копируется.'],
    ],
    bounds:[
      'Поиск работает локально по редакционному каталогу. Он распознаёт известные термины EN, BE и RU с И / ИЛИ / НЕ, но не ведёт произвольный разговор и не ищет через ИИ по всему интернету. Скобки не поддерживаются.',
      'Название в кавычках ищется буквально, не как запомнившаяся строка песни. Поиск по текстам, измерение темпа и энергичности, сопоставление аудио — следующие этапы.',
      'Подтверждённая функция колыбельной, тема текста и описание звучания — разные вещи. Ни название, ни национальность артиста не доказывают язык, настроение, права или подлинность записи.',
      'Архивные находки отделены от прямых ссылок на прослушивание. Доступная страница не доказывает, что аудио воспроизводится. Официальные плееры необязательны и загружаются только по твоему действию.',
      'Подборки и отзывы остаются в этом браузере: это не онлайн-аккаунт и не общая база. Для переноса подборки экспортируй JSON. Ссылка localhost не откроет этот прототип на чужом компьютере.',
      'Источники и редакторские трактовки видны. Мы не храним музыку или тексты песен, не выдаём разрешений на их использование и не утверждаем, что прототип уже прошёл оценку с целевыми пользователями.',
    ],
    tryText:'Найди колыбельную, открой её источник и посмотри, чем обоснована метка. Затем собери три песни под свою задачу. Получилось найти, послушать и сохранить без помощи? Расскажи и о том, что сработало, и о трудностях.',
    taskNote:'Задания про колыбельную, отсутствующий результат и подборку уже можно выполнить. Задание про запомнившуюся строку отключено, пока нет разрешённого для поиска корпуса текстов. Согласуй с модератором задание; время он записывает отдельно, с твоего согласия.',
    tasks:['Найти колыбельную с подтверждённой меткой и проверить источник','Запомнившаяся строка песни — ещё не работает','Проверить запрос, которого каталог не охватывает','Создать подборку с названием и посмотреть связанные версии',
      'Описать желаемую музыку, при необходимости попробовать локальный ИИ и проверить один вариант по источнику',
      'Сравнить документированные версии одной песни',
      'Экспортировать подборку в JSON и импортировать её как отдельную подборку',
      'Предложить правку с источником, не изменяя каталог'],
    feedbackDraft:'Разные задания сохраняются отдельными заметками под твоим кодом участника. Повторное сохранение того же кода и задания обновляет эту заметку. Экспортируй все заметки, чтобы сохранить сессию или поделиться ей; автоматически ничего не отправляется.',
    savedFeedback:'Заметка о задании сохранена на этом компьютере, но не отправлена. Можно экспортировать её отдельно или все сохранённые задания под твоим кодом участника.',
    roadmapIntro:'Одна миссия, рабочий прототип для слушателей и явно обозначенные следующие шаги. Это направления развития, не список готовых возможностей или результаты исследования с пользователями.',
    directionNotes:[
      'Сейчас: белорусскоязычный каталог с источниками и структурированным поиском. Дальше: более широкий проверенный охват, точнее темы и разрешённый корпус для поиска по запомнившейся строке.',
      'Сейчас: короткие пояснения с источниками и некоторые явно связанные версии. Дальше: переводы с волонтёрской проверкой и более глубокий культурный контекст.',
      'Позже: короткие языковые примеры с разрешением на использование, проверенным произношением и пояснениями.',
      'Отдельный режим исторического контекста может включать другие языки. Историческую географию и музыкальные свидетельства нужно разграничивать.',
      'Позже: объединить музыку, язык и культурные материалы; проверить с теми, кто действительно учится.',
      'Позже: отдельный порядок согласия, доступа и защиты приватности для семейных записей и устной истории.',
      'Сейчас: несколько подборок с названиями, порядок песен, импорт и экспорт JSON. Расширять обоснованный выбор для семьи, поездок, танцев и других потребностей.',
      'Позже: пакетное добавление и поиск возможных дублей с чётким различием произведения, записи и конкретного файла.',
      'Archive Passport и лаборатория обработки остаются отдельно от повседневного прослушивания. Ссылка на источник — не отпечаток аудио.',
      'Сейчас: просмотр источников и экспорт локальных отзывов. Дальше: проверенные материалы сообщества и разговорный помощник, направляющий к нужному инструменту.',
    ],
    corpusText:'Нынешние 139 записей — начальная коллекция, а не конечная цель. Дальше заполняем пробелы по задачам слушателя: больше разных исполнителей из независимых источников, эпох, региональных традиций, танцевальных версий и песен о повседневной жизни. Для каждой записи проверяем язык и ссылки, отличаем метки издателя от редакторского прочтения и даём несколько полезных вариантов разных артистов для каждого заявленного задания. Сохраняем честные случаи без ответа; не наращиваем цифры почти дублями или непроверенными метками.',
    roadmapBoundary:'Ещё не сделаны: непрерывный мониторинг интернета, публичный приём музыки от артистов, аккаунты волонтёров, поиск по запомнившейся строке, измерение темпа и энергичности, автоматическое сопоставление аудио и ИИ-собеседник. Прототип остаётся частным и не заменяет публичный исследовательский сайт. Оценку с людьми ещё предстоит провести.',
    feedback:'Работающая функция ещё не доказывает пользу. Твой реальный выбор, неудачные поиски и трудности определят следующие изменения; положительный результат не предполагается заранее.',
    databaseIntro:'Посмотри все 139 записей каталога: прямые ссылки на прослушивание и источники без подтверждённого аудио. Запись не обязательно означает отдельное произведение. Источники, доказательства языка и пробелы видны; нет рейтинга популярности или обещания охватить весь интернет.',
    catalogHelp:'Экспортирует редакторские метаданные и ссылки, а не аудио или тексты песен. Группы произведений отражают документированные связи, не вычисленное сходство аудио. Неизвестное остаётся неизвестным.',
  },
};

// Shared taxonomy keys stay machine-readable; labels are human-facing only.
// EN / BE / RU. A translated label is not new classification evidence.
const taxonomyLabels = {
  acoustic:['Acoustic','Акустычная музыка','Акустическая музыка'],
  aging:['Aging','Старэнне','Старение'],
  'anti-violence':['Against violence','Супраць гвалту','Против насилия'],
  'anti-war':['Against war','Супраць вайны','Против войны'],
  anxiety:['Anxiety','Трывога','Тревога'],
  autumn:['Autumn','Восень','Осень'],
  'avant-pop':['Avant-pop','Авангардны поп','Авангардный поп'],
  'bedtime-and-care':['Bedtime and care','Укладванне спаць і клопат','Укладывание спать и забота'],
  chernobyl:['Chernobyl','Чарнобыль','Чернобыль'],
  christmas:['Christmas / Kalyady','Каляды','Рождество / Коляды'],
  city:['City life','Гарадское жыццё','Городская жизнь'],
  club:['Club music','Клубная музыка','Клубная музыка'],
  coldwave:['Coldwave','Колдвэйв','Колдвейв'],
  'comfort-and-hope':['Comfort and hope','Суцяшэнне і надзея','Утешение и надежда'],
  cover:['Cover version','Кавер-версія','Кавер-версия'],
  dance:['Dance purpose','Для танцаў','Для танцев'],
  'dancing-and-desire':['Dancing and desire','Танцы і жаданне','Танцы и желание'],
  dreamy:['Dreamy · publisher description','Летуценнае гучанне · апісанне выдаўца','Мечтательное звучание · описание издателя'],
  'easter-ritual':['Easter ritual','Велікодны абрад','Пасхальный обряд'],
  electronic:['Electronic','Электроніка','Электроника'],
  escape:['Escape','Уцёкі','Побег'],
  ethno:['Ethno','Этна','Этно'],
  eurovision:['Eurovision','Еўрабачанне','Евровидение'],
  experimental:['Experimental','Эксперыментальная музыка','Экспериментальная музыка'],
  family:['Family','Сям’я','Семья'],
  fear:['Fear','Страх','Страх'],
  folk:['Folk / traditional','Фолк / традыцыйная музыка','Фолк / традиционная музыка'],
  'folk-fusion':['Folk fusion','Фолк-ф’южн','Фолк-фьюжн'],
  'folk-pop':['Folk pop','Фолк-поп','Фолк-поп'],
  'folk-punk':['Folk punk','Фолк-панк','Фолк-панк'],
  folktronica:['Folktronica','Фолктроніка','Фолктроника'],
  friendship:['Friendship','Сяброўства','Дружба'],
  grunge:['Grunge','Гранж','Гранж'],
  'harvest-and-work':['Harvest and work','Жніво і праца','Жатва и труд'],
  'hip-hop':['Hip-hop','Хіп-хоп','Хип-хоп'],
  history:['Historical memory','Гістарычная памяць','Историческая память'],
  home:['Home','Дом','Дом'],
  'home-and-belonging':['Home and belonging','Дом і пачуццё прыналежнасці','Дом и чувство принадлежности'],
  hope:['Hope','Надзея','Надежда'],
  'hypnotic-techno':['Hypnotic techno','Гіпнатычнае тэхна','Гипнотическое техно'],
  indie:['Indie','Індзі','Инди'],
  'indie-folk':['Indie folk','Індзі-фолк','Инди-фолк'],
  'indie-pop':['Indie pop','Індзі-поп','Инди-поп'],
  insomnia:['Insomnia','Бяссонніца','Бессонница'],
  isolation:['Isolation','Ізаляцыя','Изоляция'],
  jazz:['Jazz','Джаз','Джаз'],
  loneliness:['Loneliness','Адзінота','Одиночество'],
  longing:['Longing','Туга','Тоска'],
  loss:['Loss','Страта','Утрата'],
  love:['Love','Каханне','Любовь'],
  lullaby:['Lullaby · documented function','Калыханка · пацверджаная функцыя','Колыбельная · подтверждённая функция'],
  'lullaby-derived':['Reworking of a lullaby','Пераасэнсаванне калыханкі','Переосмысление колыбельной'],
  'medieval-folk':['Medieval folk','Сярэднявечны фолк','Средневековый фолк'],
  metal:['Metal','Метал','Метал'],
  migration:['Migration','Міграцыя','Миграция'],
  nature:['Nature','Прырода','Природа'],
  neofolk:['Neofolk','Неафолк','Неофолк'],
  nightlife:['Nightlife','Начное жыццё','Ночная жизнь'],
  'nursery-rhyme':['Nursery rhyme','Дзіцячая пацешка','Детская потешка'],
  'pagan-folk':['Pagan folk','Паганскі фолк','Пейган-фолк'],
  pop:['Pop','Поп','Поп'],
  'pop-punk':['Pop punk','Поп-панк','Поп-панк'],
  'post-punk':['Post-punk','Постпанк','Постпанк'],
  'post-rock':['Post-rock','Построк','Построк'],
  prayer:['Prayer','Малітва','Молитва'],
  'progressive-rock':['Progressive rock','Прагрэсіўны рок','Прогрессивный рок'],
  'protecting-family':['Protecting family','Абарона сям’і','Защита семьи'],
  protest:['Protest','Пратэст','Протест'],
  'protest-2020':['2020 protest context','Кантэкст пратэстаў 2020','Контекст протестов 2020'],
  punk:['Punk','Панк','Панк'],
  'punk-rock':['Punk rock','Панк-рок','Панк-рок'],
  relationships:['Relationships','Стасункі','Отношения'],
  remembrance:['Remembrance','Ушанаванне памяці','Память и поминовение'],
  remix:['Remix','Рэмікс','Ремикс'],
  resistance:['Resistance','Супраціў','Сопротивление'],
  reworking:['Reworking','Пераасэнсаванне','Переосмысление'],
  'ritual-chant-reworking':['Reworking of a ritual chant','Пераасэнсаванне абрадавага спеву','Переосмысление обрядового напева'],
  rock:['Rock','Рок','Рок'],
  'round-dance':['Traditional round dance','Традыцыйны карагод','Традиционный хоровод'],
  samba:['Samba','Самба','Самба'],
  'self-reflection':['Self-reflection','Самаасэнсаванне','Самоосмысление'],
  shrovetide:['Shrovetide','Масленіца','Масленица'],
  'singer-songwriter':['Singer-songwriter','Аўтарская песня','Авторская песня'],
  sleep:['Sleep · lyrical theme','Сон · тэма тэксту','Сон · тема текста'],
  solidarity:['Solidarity','Салідарнасць','Солидарность'],
  song:['Song / recording','Песня / запіс','Песня / запись'],
  spring:['Spring','Вясна','Весна'],
  summer:['Summer','Лета','Лето'],
  synthpop:['Synth-pop','Сінт-поп','Синти-поп'],
  time:['Passing time','Плынь часу','Течение времени'],
  traditional:['Traditional','Традыцыйная музыка','Традиционная музыка'],
  trance:['Trance','Транс','Транс'],
  travel:['Travel','Падарожжы','Путешествия'],
  uncertainty:['Uncertainty','Няпэўнасць','Неопределённость'],
  war:['War','Вайна','Война'],
  water:['Water imagery','Вобраз вады','Образ воды'],
  'weather-and-protection':['Weather and protection','Надвор’е і абарона','Погода и защита'],
  wedding:['Marriage / wedding','Шлюб / вяселле','Брак / свадьба'],
  winter:['Winter','Зіма','Зима'],
  'winter-carol':['Winter carol','Калядная песня','Колядная песня'],
};
for (const [key, values] of Object.entries(taxonomyLabels)) {
  ['en','be','ru'].forEach((lang, index) => { productCopy[lang][key] = values[index]; });
}

const round2Labels={
 'electroacoustic':['Electroacoustic','Электраакустыка','Электроакустика'],
 'black-metal':['Black metal','Блэк-метал','Блэк-метал'],
 'post-metal':['Post-metal','Постметал','Постметал'],
 'dark-cabaret':['Dark cabaret','Дарк-кабарэ','Дарк-кабаре'],
 'pop-rock':['Pop rock','Поп-рок','Поп-рок'],
 harvest:['Harvest','Жніво','Жатва'],
 addiction:['Addiction','Залежнасць','Зависимость'],
 literature:['Literature','Літаратура','Литература'],
 folklore:['Folklore','Фальклор','Фольклор'],
 death:['Death','Смерць','Смерть'],
 violence:['Violence','Гвалт','Насилие'],
 imprisonment:['Imprisonment','Зняволенне','Заключение'],
 freedom:['Freedom','Свабода','Свобода'],
 'wedding-song':['Wedding song · documented function','Вясельная песня · пацверджаная функцыя','Свадебная песня · подтверждённая функция'],
 'christening-song':['Christening song','Хрэсьбінная песня','Крестильная песня'],
 'midsummer-ritual':['Midsummer ritual','Купальскі абрад','Купальский обряд'],
 'drinking-song':['Drinking song','Застольная песня','Застольная песня'],
 'rain-calling':['Calling for rain','Выкліканне дажджу','Закликание дождя'],
};
for(const [key,values] of Object.entries(round2Labels))['en','be','ru'].forEach((lang,i)=>productCopy[lang][key]=values[i]);
