import {catalog} from './catalog.js';
import {catalogueCoverage} from './workflows-core.js';
const coverage=catalogueCoverage(catalog);
// Product directions agreed on 11 September; implementation snapshot updated 12 September 2026 UTC.
export const decisions={
 date:'2026-09-12',originalDecisionDate:'2026-09-11',mission:'Belarusian-language music discovery by real listener needs, with cultural context and traceable recording versions. Not an artist-nationality catalogue or a popularity chart.',
 implementationSnapshot:{status:'Listener pilot prepared for a separate unlisted website path; no completed representative-user study.',catalogueRecords:coverage.records,directListeningLinks:coverage.listening,sourceOnlyLeads:coverage.leads,belarusianLabelledRecords:catalog.filter(r=>r.language==='be').length,strictBelarusianListeningLinks:coverage.belarusian,languageBoundary:'Source/editorial language assertions, not independent audio-language verification.',collections:'Multiple named collections, ordering, copy, HTML/text reading copies and JSON import/export. Imported new links remain unverified; no cloud sync.',players:'Optional official Bandcamp and YouTube embeds connect only after a separate explicit load action. Source links remain available; page availability does not guarantee playback.',feedback:'Explicit local participant codes. Different tasks are saved separately; revisions append a new observation without overwriting the earlier one. Per-task and full-session export, no remote submission or hidden timing.'},
 rules:[
  'The main corpus filters the language of each recording, not citizenship, residence, popularity or the language of its title.',
  'Interface language and recording language are independent. Historical multilingual material belongs in a clearly separate context mode.',
  'Cultural function (lullaby), topic (family/protest), sound (soft/energetic), rhythm, genre and release year are separate fields. Every claim has a source or a labelled human assessment.',
  'A work, a recording, a file and a release are different objects. Original, remix, remake, cover, adaptation and instrumental versions use typed relationships; SHA-256 checks exact bytes only.',
  'A larger index is built through source-linked discovery and creator contributions, then review. New sources and corrections update the catalogue; this is not unsupervised retraining of AI.',
  'A missing lyric match must remain missing. Lyric recall is not implemented until permissioned texts exist. Optional semantic metadata candidates are separate from strict matches; never show similarity as confidence, factual proof or a lyric match.',
  'Volunteer author and reviewer are different people; disagreements remain visible. Translation, interpretation and poetic adaptation are distinct.',
  'No automatic uploads, paid integration or replacement of the existing Research. A separate unlisted pilot is authorized for review; participant invitations and competition submissions remain separate actions.'
 ],
 directions:[
  {id:1,phase:'now',title:'Find my music in Belarusian',scope:'Now: structured local AND/OR/NOT search over documented styles, themes, functions, identities and dates; separate optional local semantic metadata candidates. Explain source evidence and missing coverage. Next: independently evaluated relevance and permissioned remembered-lyric retrieval, not invented audio features.'},
  {id:2,phase:'now',title:'Understand a song',scope:'Now: source-linked editorial explanations and explicitly documented version groups. Next: independent cultural/language review, richer context and reviewed translation. Metadata passport is not a rights certificate or audio fingerprint.'},
  {id:3,phase:'next',title:'One minute of language',scope:'Permissioned fragments, repetition and reviewed language explanations. Complement existing Belarusian learning tools; do not claim LingQ lacks Belarusian.'},
  {id:4,phase:'next',title:'How an era sounded',scope:'A separate historical lens by period and place; century playlists, other languages when context warrants. Distinguish composition, recording/release, event and historical period dates. MAPA is attributed contextual heritage work, not proof of all-original authorship.'},
  {id:5,phase:'next',title:'Cultural mini-lessons',scope:'Combine with language learning: educators assemble recordings, explanations, discussion prompts and sources.'},
  {id:6,phase:'later',title:'Family voices and oral history',scope:'Consented family stories, audio interviews, archived broadcasts, searchable memories and bilingual excerpts. Separate privacy and consent workflow.'},
  {id:7,phase:'now',title:'A collection for any listener',scope:'Multiple named collections, ordering and JSON import/export now preserve links and context without copying audio. Grow task coverage for family, travel, dance, learning or protest history, not DJs only. A documented lullaby function does not establish soft sound; do not conflate a dance remix with sleep music.'},
  {id:8,phase:'later',title:'Organize my archive',scope:'Professional batch ingest, duplicate candidates, missing metadata, file/recording/work distinctions. No claim that a byte hash identifies covers or remixes.'},
  {id:9,phase:'existing separate lab',title:'What AI changed in music',scope:'Keep the existing version/restoration lab and owned Suno comparisons. Develop controlled listening evaluation later; do not rebuild a second DAW or force it into the listener journey.'},
  {id:10,phase:'now + later',title:'Trust now; a guide later',scope:'Evidence, uncertainty, provenance and corrections are required now. The user-proposed conversational assistant comes later: clarify the task, retrieve actual records and route people between tools, never invent missing catalogue items.'}
 ],
 corpusPlan:{current:'See the live catalogue coverage above. The corpus includes short traditional Tradycyja recordings with individual performer credits alongside contemporary artist releases. Counts are not unique compositions, guaranteed playback or comprehensive cultural coverage.',target:'Fill qualitative coverage gaps by listener task: independently sourced performers, eras, regional traditions, themes, documented dance versions and everyday listening needs. No fixed small-count target or promise that adding records alone improves usefulness.',coverage:'Aim for at least three useful choices across different artists per advertised positive task, independently reviewed; retain unknown-language, wrong-function and missing-answer negative cases. If a task is not covered, narrow or disable it rather than inflate counts or fabricate classifications.',ingest:['Discover official artist/label/archive recording','Keep the exact source URL, release date and permission/access scope','Separate work, recording, version and release; do not merge by title alone','Record language and cultural claims with evidence; distinguish publisher labels and editorial readings','Independent volunteer review and visible disagreement handling remain a planned workflow','Publish approved metadata in a versioned index only after permission','Future scheduled refresh creates review candidates; it never silently rewrites human decisions']},
 semanticExperiment:{status:'Real local inference implemented; experimental metadata retrieval, not validated search effectiveness. See integrations/semantic-search/README.md.',model:'Quantized multilingual E5-small; the private development build uses a local CPU Python worker; the hosted pilot adds consent-gated browser WASM inference, no fine-tuning and no model trained on this music corpus.',scope:'Checked-in source-linked, Belarusian-labelled recording metadata only; no audio, lyric index, source-only leads, unknown-language entries or personal links.',activation:'Separate opt-in search. Model/environment installation is deliberate; no automatic setup on page visit or query and no remote inference fallback.',output:'Exact matched metadata chunk, source link and recording ID. Show as possible matches outside the strict result count, never as generated facts or probability.',constraints:'Preserve dropdowns and recognised language/date constraints. Boolean, malformed, exact-title and remembered-lyric requests use the structured path or abstain rather than silently widen.',evaluation:'Developer-authored diagnostics and heuristic thresholds are not human relevance judgments, a held-out evaluation or contest study evidence. Some paraphrases miss and some suggestions drift. Independent EN/BE/RU relevance review, held-out descriptions and real-user sessions remain necessary.'},
 studyPlan:{status:'Planned, not conducted. Technical/semantic diagnostics are not participant sessions or study results.',participants:'Recruit 6 listeners: 2 strong Belarusian users, 2 general listeners, 2 learners/infrequent speakers. Separate metadata reviewers are not counted as usability participants.',currentTasks:['Find a source-classified Belarusian lullaby and explain why a title or soft-sound claim alone is insufficient','Try a genuine missing-catalogue query and recognise the absence of a supported answer','Build a cross-artist named collection, inspect a documented version relationship, export JSON and restore it without overwriting another collection'],disabledTasks:['Approximate remembered-lyric retrieval, including positive and missing-line controls, until permissioned texts are available'],semanticTasks:'Evaluate optional meaning-based candidates separately with held-out EN/BE/RU descriptions and independent relevance judgments; distinguish possible relevance from confirmed cultural function.',baseline:'Compare with each participant’s usual search; alternate prototype-first and baseline-first order with equivalent but different tasks.',metrics:['Task completion without help','Time to first relevant listening link','Independently judged relevant result in top 3 for known-answer cases','No incorrectly language-labelled recording in strict BE results; source labels still require linguistic review','False positive in absent-answer task','Comprehension of sources, candidate uncertainty and version relationships','Specific errors and changes followed by retest'],neutralIntro:'This is a pilot, not a finished archive. Missing music and failed queries are useful feedback. You are assessing the tool, not your knowledge; praise is not required. Participation is voluntary. Do not enter personal or sensitive information.',privacy:'Local participant code, optional nickname, language comfort and task feedback only. Notes for different tasks remain separate; revisions append a new observation without overwriting the earlier one. Export one note or the local session for the moderator. No hidden tracking, remote submission or authentication.'},
 delivery:{status:'Not submission-ready by assertion. No application has been submitted from this pilot, and technical QA is not representative-user evidence.',wudc:'Previously checked deadline: 18 September 2026. Requires a meaningful prototype, representative-user evaluation, documented design changes, ethical framework and accurate AI disclosure. Structured search must not be called AI; the separate local semantic experiment can be described precisely with its limitations. Human sessions and competition gates remain incomplete; recheck current official requirements before submission.',audiotool:'Previously checked LetsBuild landing page stated 28 September 2026 and included Listening. Full live FAQ was unavailable during that check. Nexus/integration requirements and project eligibility are not established. Recheck primary rules; no forced integration or automatic submission.',stanford:'Demonstrate an honest research prototype, corpus methodology, evidence and observed technical iterations in the user-planned week after 16 September. Label planned human research and experimental AI clearly. Do not claim completed doctoral research, awards not received or causal cultural/learning impact.'},
 sources:['https://worldusabilityday.org/design-challenge/','https://www.audiotool.com/LetsBuild/','https://www.lingq.com/en/learn-belarusian-online/','https://cyanite.ai/faq/','https://www.wipo.int/en/web/copyright/faq-copyright']
};
